### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by lfarah** [Orderella/PopupDialog#10]
`CocoaPods` and `Carthage` are awesome tools and make our life really easier, but there are some devs who still don't know how to use them. 

It would be cool to add the _Manual installation_ guide in your `README.md`. You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by mwfire** [comment]
@lfarah Agreed. I have added the following to the Readme. Not very sophisticated, but it should do.

### Manually

If you prefer not to use either of the above mentioned dependency managers, you can integrate PopupDialog into your project manually by adding the files contained in the [Classes](https://github.com/Orderella/PopupDialog/tree/master/PopupDialog/Classes)
folder to your project.

Pushed to development branch, commit b544152 by now.

**Comment by mwfire** [comment]
Pushed to master
