### ISSUE TITLE
Add custom ViewController without .xib file

### ISSUE THREAD

**Issue by moonvader** [Orderella/PopupDialog#105]
I installed PopupDialog manually. Xcode 8. Swift 3

When use standard code to create PopupDialog - I have no problems. But I do have problems trying to use it with custom view.

I have class CustomViewController and this class is used for ViewController that is created in Storyboard. 

So when I try this code

```
        let customVC = CustomViewController()
        let popup = PopupDialog(viewController: customVC)
        let button = DefaultButton(title: "OK", action: nil)
        popup.addButton(button)
        self.present(popup, animated: true, completion: nil
```

I can see only one button. Maybe I am doing something wrong?

P.S. I also created file for separate ViewController and checked "add xib file" when it was created - if I use it - i can see some part of it in PopupDialog but I don't understand how can I set up size of this Dialog and also I don't understand why I see only UIs that were added to xib file - not those that were added to ViewController on StoryBoard

**Comment by moonvader** [comment]
I finally found out that I needed to add constraints to top and bottom parts of ViewController 
and with this code I could make it work !)

        let StoryBoard = UIStoryboard.init(name: "Main", bundle: nil)
        let customVC = StoryBoard.instantiateViewController(withIdentifier: "customVC")
        customVC.modalPresentationStyle = UIModalPresentationStyle.custom

        let popup = PopupDialog(viewController: customVC)
        let button = DefaultButton(title: "OK", action: nil)
        popup.addButton(button)
        self.present(popup, animated: true, completion: nil

**Comment by nuclearghost** [comment]
In case anyone ever comes across this again, I needed to set a height constraint on my view controller.

```swift
NSLayoutConstraint(item: customVC.view, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1.0, constant:550.0).isActive = true
```
