### ISSUE TITLE
Custom popupDialog breaks when VC is presented above it SOLVED

### ISSUE THREAD

**Issue by pooya511** [Orderella/PopupDialog#107]
According to issue #38 I could solve the problem by adding this line of code to init method of PopupDialog.swif line 161:

change this:
if gestureDismissal {
            let panRecognizer = UIPanGestureRecognizer(target: interactor, action: #selector(InteractiveTransition.handlePan))
            popupContainerView.stackView.addGestureRecognizer(panRecognizer)
            let tapRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTap))
            popupContainerView.addGestureRecognizer(tapRecognizer)
        }

to 

if gestureDismissal {
            let panRecognizer = UIPanGestureRecognizer(target: interactor, action: #selector(InteractiveTransition.handlePan))
            popupContainerView.stackView.addGestureRecognizer(panRecognizer)
            let tapRecognizer = UITapGestureRecognizer(target: self, action: #selector(handleTap))
            tapRecognizer.cancelsTouchesInView = false
            popupContainerView.addGestureRecognizer(tapRecognizer)
        }

it will send touches to tableView and cell didSelectRowAt will work correctly!

**Comment by ahmedAlmasri** [comment]
![simulator screen shot feb 17 2017 1 55 28 pm](https://cloud.githubusercontent.com/assets/14888785/23064453/d558ee6a-f518-11e6-8f4a-d75867667390.png)

this same problem 

add this line tapRecognizer.cancelsTouchesInView = false
 not solved 
plz help

**Comment by mwfire** [comment]
Ready for testing on develop: `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

**Comment by ahmedAlmasri** [comment]
@mwfire thank you, it's working

**Comment by mwfire** [comment]
Released with v. 0.5.4
