### ISSUE TITLE
need of changing examples

### ISSUE THREAD

**Issue by yjb94** [Orderella/PopupDialog#108]
i think to change corner radius or shadowenalbled (i didn't check)

>  let pcv = PopupDialogContainerView.appearance()
    pcv.cornerRadius = 4

you will need a code like this.

not the 

>  let pv = PopupDialogDefaultView.appearance()
>             pv.cornerRadius = 4

version. i think it is deprecated

**Comment by mwfire** [comment]
@yjb94 Thanks for reporting, I have updated the README accordingly!

**Comment by ergunkocak** [comment]
For the ones who are not using default view, how can we disable round corners?

**Comment by ergunkocak** [comment]
This works :)
    let pcv = PopupDialogContainerView.appearance()
    pcv.cornerRadius = 0

**Comment by Hamna21** [comment]
@mwfire I am unable to modify the corner radius. PopupDialogContainerView.appearance() has no option for corner radius.

I am using a custom view controller for Popup.
