### ISSUE TITLE
Question: Obj-C compatibility?

### ISSUE THREAD

**Issue by oferRounds** [Orderella/PopupDialog#11]
Thanks for this library - looks great!

Would love to know if it's compatible also with obj-c?

Thanks!

**Comment by mwfire** [comment]
Thanks, @oferRounds!

Unfortunately, the latest version of this library uses Swift only features, namely Generics for adding custom view controllers to the dialog. I am not entirely happy with that decision, as it makes PopupDialog not Objective-C compatible. I am still evaluating if it makes sense to change this back, but that would break the existing API.

However, up to version 0.1.6, PopupDialog is ObjC compatible. You could specify this version in your Podfile like this:

``` ruby
pod 'PopupDialog', '~> 0.1.6'
```

Example:

``` objective-c
#import <PopupDialog/PopupDialog-Swift.h>

PopupDialog *popup = [[PopupDialog alloc] initWithTitle:@"Test" message:@"Test" image:nil transitionStyle: PopupDialogTransitionStyleBounceUp buttonAlignment:UILayoutConstraintAxisHorizontal];
DefaultButton *button = [[DefaultButton alloc] initWithTitle:@"Title" action:^{
    // Test action
}];
[popup addButton:button];
[self presentViewController:popup animated:YES completion:nil];
```

I'll keep you updated on this!

**Comment by mwfire** [comment]
Hey there, @oferRounds!

I have pushed the ObjC compatibility changes to the development branch, that is "ready for implementation". API changes are minor, that is why I am planning on releasing it as V 0.3.0 asap.

Would you mind giving it a quick try?

``` ruby
pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'
```

Thanks!

**Comment by animaonline** [comment]
+1

**Comment by oferRounds** [comment]
@mwfire Thank you for being so responsive!
I'll try it first thing tomorrow morning (it's night here already), and let you know!
Thanks again!

**Comment by mwfire** [comment]
Ok, did a few tests and released it this morning as v0.3.0. I would love you guys to test it and give me feedback :)

``` ruby
pod 'PopupDialog', '~> 0.3'
```

I will keep this thread open for now.

**Comment by oferRounds** [comment]
@mwfire - great, trying it now!

**Comment by oferRounds** [comment]
Oh @mwfire - I didn't notice the library requires iOS 9+...
And currently I support also iOS 8.
I'm sorry for not noticing it :(

**Comment by oferRounds** [comment]
Again, I really appreciate your effort and responsiveness! Iopefully I'll move soon iOS9+, then I'll try it again

**Comment by mwfire** [comment]
@oferRounds Thanks, mate! I am considering iOS8 compatibility at the moment, I will keep you updated.

Related issue #13
