### ISSUE TITLE
Width based on Autolayout constraints

### ISSUE THREAD

**Issue by kerry** [Orderella/PopupDialog#110]
Can PopupDialog determine its width based on Autolayout constraints of the custom view controller's view?

**Comment by mwfire** [comment]
Hey @kerrygrover! Unfortunately this is not possible at the moment. The width is adjusted to fit the given viewport. I can see this might be useful in some cases, though. I will keep this in mind with future releases.

**Comment by yjb94** [comment]
@kerry, @mwfire  i think you can adjust settings in PopupDialogContainerView.swift.
the constraints codes in  `internal func setupViews()`

**Comment by yjb94** [comment]
![2017-02-15 4 34 18](https://cloud.githubusercontent.com/assets/6838787/22964561/a2bf9f08-f39c-11e6-9671-19bc84638ee2.png)
`        constraints += NSLayoutConstraint.constraints(withVisualFormat: "H:|-(>=10,==20@900)-[shadowContainer(<=340,>=300)]-(>=10,==20@900)-|", options: [], metrics: nil, views: views)
        constraints += [NSLayoutConstraint(item: shadowContainer, attribute: .centerX, relatedBy: .equal, toItem: self, attribute: .centerX, multiplier: 1, constant: 0)]
        centerYConstraint = NSLayoutConstraint(item: shadowContainer, attribute: .centerY, relatedBy: .equal, toItem: self, attribute: .centerY, multiplier: 1, constant: 0)
        constraints.append(centerYConstraint!)`


` constraints += NSLayoutConstraint.constraints(withVisualFormat: "H:|[shadowContainer(<=375,>=300)]|", options: [], metrics: nil, views: views)
        constraints += [NSLayoutConstraint(item: shadowContainer, attribute: .centerX, relatedBy: .equal, toItem: self, attribute: .centerX, multiplier: 1, constant: 0)]
        centerYConstraint = NSLayoutConstraint(item: shadowContainer, attribute: .bottom, relatedBy: .equal, toItem: self, attribute: .bottom, multiplier: 1, constant: 0)
        constraints.append(centerYConstraint!)`

i switched the code like this. would this help? @kerry

**Comment by kerry** [comment]
@yjb94 Hey, yes, I think that would work. Thanks so much.

**Comment by kerry** [comment]
@yjb94 By the way, just curious. Is it a good idea to change the library's code generally? Would not that be a problem while updating the library (if using cocoapods or something like that).

**Comment by yjb94** [comment]
@kerry I don't know in general terms....but in my case, I sometimes change codes in library. For me there were no problems. It would have been nice to fork and pull request...but I am in a hurry, so I just managed to change codes directly.

**Comment by kerry** [comment]
ok. Thanks for the comment
