### ISSUE TITLE
Wrong way to add custom child view controller 

### ISSUE THREAD

**Issue by NyxReloaded** [Orderella/PopupDialog#112]
According to Apple's doc :
[https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html#//apple_ref/doc/uid/TP40007457-CH11-SW1](url)  (Adding a Child View Controller to Your Content)

You should call addChildViewController() and didMoveToController() when adding the view of the custom child view controller in the view hierarchy. Otherwise, this will break the appearance callbacks (viewWillAppear, viewDidAppear, viewWillDisappear and viewDidDisappear). 

When we present the dialog, the viewDidLoad, viewWillAppear and viewDidAppear are called event if the animation if is not finished yet. The correct appearance flow is :

1)  viewDidLoad
2) viewWillAppear
3) viewDidAppear : on animation completion

I created a pull request that fix the issues : #111.

**Comment by mwfire** [comment]
Thx, I will look into this!

**Comment by mwfire** [comment]
Ready for testing on develop: `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

**Comment by mwfire** [comment]
Released with v. 0.5.4
