### ISSUE TITLE
Make gesture dismissal a global appearance setting.

### ISSUE THREAD

**Issue by nick-iCars** [Orderella/PopupDialog#113]
Not sure about other users, but we use this as a replacement for UIAlert and the expectation with the alert is that the user has to select a choice before continuing. I like having the option to have gesture dismissal but feel like it should not be the default behavior. Either way, please give us a way to turn it off globally.

**Comment by mwfire** [comment]
Gesture dismissal is just an alternative to tapping cancel. As in our use cases the cancel button is present more often than not, we chose to default it to true and turn it off explicitly if needed. There are no plans of changing this behaviour at this point, so I would suggest to
- either turn it off at initialisation (gestureDismissal: false) or
- write a small wrapper that does this

**Comment by nick-iCars** [comment]
Just wrote the wrapper, now just find/replacing (#superfun) all over. In case it makes a difference we have an app that drivers use in a car and they are dismissing by accident when they attempt to select a response.

**Comment by mwfire** [comment]
Hey @nick-iCars, I am not sure when I can release this, but if you have a good solution, feel free to do a PR!

**Comment by nick-iCars** [comment]
Ok, will do, I'm trying to think of a good way to handle it but as to not break the legacy functionality. My first idea would be to add an appearance property, or some kind of global property, that is aware of if the gesture dismissal flag was set explicitly or whether it just defaulted to true. still thinking tho. Thank you.
