### ISSUE TITLE
CocoaPods warning

### ISSUE THREAD

**Issue by quver** [Orderella/PopupDialog#115]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version: 10.12.3
- Xcode version: 8.2.1.
- PopupDialog version: 0.5.3
- Minimum deployment target: 9.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0.1

## Dependency management
- Dependency manager: CocoaPods
- Version: 1.2.0

## What did you do?

`pod install`

## What did you expect to happen?

nothing :)

## What happened instead?

I get warning
`[!] Unable to read the license file ----/Pods/PopupDialog/LICENSE for the spec PopupDialog (0.5.3)`

**Comment by mwfire** [comment]
Hey there @quver, unfortunately I cannot reproduce this :( Maybe you can try `pod deintegrate` and `pod install` subsequently?

**Comment by quver** [comment]
Thx this two steps removed this warning
