### ISSUE TITLE
Version 0.4 give errors for Swift 2.3

### ISSUE THREAD

**Issue by waseefakhtar** [Orderella/PopupDialog#116]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.12.3
- Xcode version (e.g. 8.0): 8.2.1
- PopupDialog version (e.g. 0.5.0): 0.4
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 2.3

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.2.0

## What did you do?

I tried installing in three ways like:

pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => ‘Swift2.3’
pod ‘PopupDialog’, ‘0.4’
pod ‘PopupDialog’, ‘~> 0.4'

## What did you expect to happen?

To install PopupDialog for Swift 2.3

## What happened instead?

It gives me around 104 errors.

**Comment by mwfire** [comment]
Hey @waseefakhtar,

unfortunately, active support for Swift 2.3 was dropped a while ago, the branch is now maintained by the community only and was reported stable back then. If you have fixes for these issues, feel free to do a pull request, it is very much appreciated.

Cheers
Martin
