### ISSUE TITLE
Custom View Controller

### ISSUE THREAD

**Issue by indiesk** [Orderella/PopupDialog#12]
Hi, I may be the only one not being able to replicate the Custom View Controller example from your repository, but when I try to initiate the PopUpDialog with a custom view controller, the custom view does not get created above the buttons, but it seems to be created at the buttons position, ending up with something like the screenshot below:

![screen shot 2016-07-25 at 11 18 24 pm](https://cloud.githubusercontent.com/assets/9728019/17125042/258d36a0-52be-11e6-817d-534e674c2914.png)

This is how I set up my custom view controller in xib file:

![screen shot 2016-07-25 at 11 18 37 pm](https://cloud.githubusercontent.com/assets/9728019/17125049/39c19d64-52be-11e6-9040-a2d607f487ec.png)

I tried to replicate every single step - even the view sizes and constraints - but it just doesn't work as your existing example.

I would appreciate it if you can let me know what I'm missing

Thank you in advance!

**Comment by mwfire** [comment]
Hey @indiesk!

Are you getting any Autolayout related errors in the console? Make sure to satisfy all constraints needed. I did a quick demo project with roughly your layout and it works as expected.

Here is a rough Interface Builder overview:

<img src="http://www.mwfire.de/github/autolayout.png" width="350"  />

Here is what the result looks like:

<img src="http://www.mwfire.de/github/result.png" width="350" />

The code:

``` swift
let vc = SliderViewController(nibName: "SliderViewController", bundle: nil)
let popup = PopupDialog(viewController: vc)
let button = DefaultButton(title: "OK", action: nil)
popup.addButton(button)
presentViewController(popup, animated: true, completion: nil)
```

Hope that helps :)

**Comment by indiesk** [comment]
Thank you for the prompt response.

I do not have any errors related to Autolayout. I literally tried to replicate the structure, sizes and constraints as your example, but I still get the same result..

![screen shot 2016-07-26 at 11 41 31 am](https://cloud.githubusercontent.com/assets/9728019/17144856/3c474738-5326-11e6-811a-6aaacad2571c.png)

And I just called my view controller in the same code:

``` swift
// Create a custom view controller
//let ratingVC = RatingViewController(nibName: "RatingViewController", bundle: nil)
let ratingVC = TestViewController(nibName:"TestViewController", bundle:nil)

// Create the dialog
let popup = PopupDialog(viewController: ratingVC, transitionStyle: .BounceDown, buttonAlignment: .Horizontal, gestureDismissal: false)

// Create first button
let buttonOne = CancelButton(title: "CANCEL") {
    self.label.text = "You canceled the rating dialog"
}

// Create second button
let buttonTwo = DefaultButton(title: "RATE") {
    //self.label.text = "You rated \(ratingVC.cosmosStarRating.rating) stars"
}

// Add buttons to dialog
popup.addButtons([buttonOne, buttonTwo])

// Present dialog
presentViewController(popup, animated: true, completion: nil)
```

What I ended up doing was I copied the RatingViewController.swift and RatingViewController.xib files from your example to my project and edited from there to my needs. Interestingly, it worked.

Anyhow, I'm able to move on from here, but I guess it would still be nice to know what I'm missing in the steps, if possible..

Thank you :)

**Comment by mwfire** [comment]
@indiesk Hm, it is hard to tell what the problem might be... Glad it works, though!

I'll keep this issue open, let's see if someone else hits this.
Just out of curiosity: did you build for iOS 9.3 or some version below?

**Comment by indiesk** [comment]
@mwfire I did find my problem.. how stupid. It is indeed Autolayout related problem. I forgot to add the constraint from the slider to the bottom of the container. 

![screen shot 2016-07-26 at 12 16 02 pm](https://cloud.githubusercontent.com/assets/9728019/17146024/c0b24e56-532a-11e6-8270-15afe720293e.png)

Hope my mistake helps anyone else who's encountering similar problem!

**Comment by mwfire** [comment]
@indiesk Perfect! I'll close that for now and will refer to it if any questions come up.
Thanks!

**Comment by zh-wowtv** [comment]
I think bottom layout constraint is a must.
