### ISSUE TITLE
No such module 'Popup dialog'

### ISSUE THREAD

**Issue by timotheeduran** [Orderella/PopupDialog#120]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.12.3
- Xcode version (e.g. 8.0): 8.2.1
- PopupDialog version (e.g. 0.5.0): 0.5.3
- Minimum deployment target (e.g. 9.0): 8.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): none
- Version (e.g. 1.1.0): none

## What did you do?

I opened the example project and tried to run it. I didn't modify anything.

## What did you expect to happen?

I expected that the app would launch.

## What happened instead?

I get an error : "No such module 'PopupDialog'" for "import PopupDialog" in ViewController.swift. What should I do ? I tried to clean (Shift + ⌘ + K) and build (⌘ + B) again.

<img width="908" alt="capture d ecran 2017-03-09 a 15 07 10" src="https://cloud.githubusercontent.com/assets/26303997/23753532/1a2c7bd0-04da-11e7-98c1-cdba3d65ed87.png">

**Comment by timotheeduran** [comment]
Found ! Opening xcodeproj instead of xcworkspace will cause an error like this... Sorry

**Comment by francisrod01** [comment]
I have the same problem using the same version of Xcode and Swift but it not working.

I tried this steps: How can I choose Swift compiler version
https://stackoverflow.com/a/43142147/3332734

This specify the git repository as mentioned here:
https://stackoverflow.com/a/40186194/3332734

And the entire environment on MacOS:

$ pod env

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9cc1682f79961949907b00436eb07335bae47574
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.3'
# Uncomment this line if you're using Swift
use_frameworks!

target 'my-Project' do

    pod 'Alamofire', '~> 4.0'
    pod 'MBProgressHUD'
    pod 'PromiseKit', '~> 4.0'
    pod 'MBAutoGrowingTextView', '~> 0.1.0'
    pod 'PusherSwift', '~> 3.0'
    pod 'PopupDialog', '~> 4.0'
    pod 'SwiftMessages'
    pod 'Bugsnag'
    pod 'AutoCompleteTextField'

    pod 'Fabric'
    pod 'Crashlytics'

    target 'my-ProjectTests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```
