### ISSUE TITLE
Dynamically increasing Height.

### ISSUE THREAD

**Issue by Aviral190694** [Orderella/PopupDialog#121]
Hi. Is it possible to increase the height of the popup? like adding a new button to the popup and adding the height .

**Comment by mwfire** [comment]
Hey @Aviral190694,

the height is defined by the content you display. Using a custom view controller, you should be able to achieve what you want. At the moment, buttons have to be defined before displaying the dialog, just as UIAlertController.

**Comment by Aviral190694** [comment]
Yes. that is super cool. I used the popup dialod extensively in my app. The issue I am facing is if I have a custon cell which needs to load when user click on a button and I have to increase the Height of the table how will I do this? 
or if I have to add a button in the container view. How will I do this?
