### ISSUE TITLE
Any way can change dialog width and height ?

### ISSUE THREAD

**Issue by icefox57** [Orderella/PopupDialog#122]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report
Any way can change dialog width and height ? 

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.11.6
- Xcode version (e.g. 8.0): 8.2.1
- PopupDialog version (e.g. 0.5.0): 0.5.3
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): ℹ
- Version (e.g. 1.1.0): ℹ 

## What did you do?

want to change dialog width

## What did you expect to happen?

customer width and height 

## What happened instead?

unless unlock the pod file, can't find way to change it

## Project that demonstrates the issue

**Comment by mwfire** [comment]
Hey @icefox57,

the idea of this dialog is to mimic the UIAlert behavior. The width adapts to screens (e.g. iPhone 4 dialog is smaller). The height is defined by the content. This way, the complexity can be kept to a minimum. However, if you have a good idea on how to achieve this without breaking the current API, feel free to file a Pull Request!

Thanks!

**Comment by KyleXie** [comment]
For change the width, probably after #109 merged to master, you could reinstall constraints for the container view. I think it might work.

**Comment by mwfire** [comment]
I will close this for now. Until version 1.0, there is no plans for custom width, to keep it simple. Height depends on the content. Pull requests that take into account iPhone 4 and iPad screen sizes are welcome!
