### ISSUE TITLE
Change contentMode of imageView to ScaleAspectFit in Swift 2.3

### ISSUE THREAD

**Issue by bizibizi** [Orderella/PopupDialog#124]
please add it

**Comment by mwfire** [comment]
Hey @bizibizi,

I am not maintaining Swift 2.3 actively. If you want to see changes there, please do a PR. Make sure that people who don't need this don't experience any breaking changes, plz :)

**Comment by alkanyunus** [comment]
Temporary solution is 
`
if let vc = popup.viewController as? PopupDialogDefaultViewController {
            vc.view.subviews.forEach { (item) in
                if let imgView = item as? UIImageView {
                    imgView.contentMode = .scaleAspectFit
                }
            }
        }
`
