### ISSUE TITLE
Custom View Controller does not appear

### ISSUE THREAD

**Issue by felixchan** [Orderella/PopupDialog#125]
Swift 3, master branch

```
        let VC = UIViewController() //Also tried a custom VC
        let popup = PopupDialog(viewController: VC, buttonAlignment: UILayoutConstraintAxis.horizontal, transitionStyle: PopupDialogTransitionStyle.bounceUp, gestureDismissal: true, completion: nil) //Also tried the short version
        self.present(popup, animated: true, completion: nil)
```

The black blur view appears, but the view controller does not.

**Comment by mwfire** [comment]
Hey @felixchan ,

in order to display content views correctly, all constraints have to be satisfied. In particular, height has to be set correctly. As this cannot be debugged remotely:

- Do you get any auto layout related console logs?
- Can you attach a sample project that showcases your use case?

Thanks!

Related topics:
#12 #79 #28 #118

**Comment by jordimares** [comment]
I am having the same issue. In my case I do not see any auto layout problem in the console.

This is the view controller I want to show:

```
import UIKit

class CommentPopupViewController : UIViewController {
    
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var commentTextArea: UITextView!
    @IBOutlet weak var sendButton: UIButton!
    @IBOutlet weak var cancelButton: UIButton!
    
    var delegate : NewCommentCreatedProtocol!
    
    @IBAction func sendComment(_ sender: Any) {
        
    }
    
    @IBAction func cancel(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
}
```

And this is how I call it:

```
let vc = CommentPopupViewController()
            let popup = PopupDialog(viewController: vc)
            self.present(popup, animated: true, completion: nil)
```

**Comment by mwfire** [comment]
Hey @jordimares,

no console output does not necessarily mean the constraints are laid out correctly. Have a look at the example project, the rating view controller is a custom view controller with autolayout constraints laid out in a XIB.

Related topics:
#12 #79 #28 #118

**Comment by jordimares** [comment]
@mwfire Thanks, I will check and I will get back to you

**Comment by jordimares** [comment]
These are the constraints I have for auto layout

```
<constraints>
                            <constraint firstAttribute="bottom" secondItem="uNE-OJ-Br9" secondAttribute="bottom" constant="20" symbolic="YES" id="1I9-E5-Rqf"/>
                            <constraint firstItem="XBc-91-G7Z" firstAttribute="trailing" secondItem="Ghr-a6-fcb" secondAttribute="trailingMargin" id="9GI-rf-5gP"/>
                            <constraint firstItem="XBc-91-G7Z" firstAttribute="top" secondItem="5xS-4J-Z1J" secondAttribute="bottom" id="A5D-sv-gmZ"/>
                            <constraint firstItem="XBc-91-G7Z" firstAttribute="leading" secondItem="Ghr-a6-fcb" secondAttribute="leadingMargin" id="B8R-dv-wGv"/>
                            <constraint firstItem="f3H-2l-FIu" firstAttribute="top" secondItem="XBc-91-G7Z" secondAttribute="bottom" constant="8" symbolic="YES" id="Erd-a5-vNh"/>
                            <constraint firstItem="XBc-91-G7Z" firstAttribute="leading" secondItem="f3H-2l-FIu" secondAttribute="leading" id="OlQ-cY-XGG"/>
                            <constraint firstItem="XBc-91-G7Z" firstAttribute="trailing" secondItem="f3H-2l-FIu" secondAttribute="trailing" id="RgG-8g-4dO"/>
                            <constraint firstItem="uNE-OJ-Br9" firstAttribute="top" secondItem="0N8-ay-LOJ" secondAttribute="bottom" constant="8" symbolic="YES" id="VaH-IM-BKJ"/>
                            <constraint firstItem="0N8-ay-LOJ" firstAttribute="trailing" secondItem="uNE-OJ-Br9" secondAttribute="trailing" id="WLv-Y8-T7C"/>
                            <constraint firstItem="0N8-ay-LOJ" firstAttribute="leading" secondItem="uNE-OJ-Br9" secondAttribute="leading" id="l68-qX-J9H"/>
                            <constraint firstItem="f3H-2l-FIu" firstAttribute="trailing" secondItem="0N8-ay-LOJ" secondAttribute="trailing" id="l86-DF-OMt"/>
                            <constraint firstItem="f3H-2l-FIu" firstAttribute="leading" secondItem="0N8-ay-LOJ" secondAttribute="leading" id="plZ-zi-Lqc"/>
                            <constraint firstItem="0N8-ay-LOJ" firstAttribute="top" secondItem="f3H-2l-FIu" secondAttribute="bottom" constant="8" symbolic="YES" id="zhV-gh-P3y"/>
                        </constraints>
```

And this is how the VC looks like:

![screen shot 2017-03-21 at 20 19 42](https://cloud.githubusercontent.com/assets/1529118/24168909/cdf85db2-0e73-11e7-87bd-9ed2b242fa9d.png)

I cannot see anything wrong. Can you?

**Comment by AhmedAmineZribi** [comment]
I have the same probleme 
![img_0382](https://cloud.githubusercontent.com/assets/15227156/24258927/83d965be-0fef-11e7-83f9-b050a7a38b80.PNG)

**Comment by mwfire** [comment]
Please have a look at the example project. The rating dialog is a custom view controller instantiated from Storyboard. It is important to end up with the a definite height. I am trying to support here as much as I can, but this is usually not a PopupDialog issue.

If you need further assistance, please provide an example project. Thanks!

**Comment by ghost** [comment]
@mwfire I came across this same issue (even with autolayout) until I read that I needed to explicitly set the `height` as well. Maybe adding that height is also necessary to the README would help future users resolve this problem easier?

**Comment by mwfire** [comment]
Hey @callodacity. Constraints need to be satisfied. It is the same for scroll views, for example, and not unique to popup dialog.

There's definitely room for improvement in the README regarding custom view controllers, though. I'll take that into account!

**Comment by hecool108** [comment]
Hi, @jordimares. Hope my experience will help. @mwfire mentioned that all the display views in the VC should have non-ambiguous constraints working on them. I made a sample code to demonstrate.
https://github.com/hecool108/PopupDialogCustomVC.
