### ISSUE TITLE
Scrollview for long messages

### ISSUE THREAD

**Issue by ghost** [Orderella/PopupDialog#127]
Awesome project. But it needs a scrollview that contains the message. If a message is long for view, the popup dialog view is out of bounds. If a scrollview contains the message, everything will be OK. :)

**Comment by mwfire** [comment]
Thanks, @ferdibayrak.

I considered this in the beginning, however left it to a custom view controller implementation. This is mainly as the image (if there is one) would scroll out of the dialog view, which might look awkward. Only scrolling text might be weird as well. What would your preferred solution be?

**Comment by mrgradyed** [comment]
Hi,
I think it would be a nice feature to have just the message text scrollable if too long to fit.  
Thanks for your great work.
