### ISSUE TITLE
Possible to change the background opacity?

### ISSUE THREAD

**Issue by Dbigshooter** [Orderella/PopupDialog#128]
Hi there,

I was wondering; is it possible to change the opacity of the background? I find it, in some cases, a bit too dark.

**Comment by mwfire** [comment]
Hey @Dbigshooter,

have a look at https://github.com/Orderella/PopupDialog#overlay-view-appearance-settings
Appearance is the preferred way of changing dialog styles, as they affect all instances of PopupDialog.

Also, the example project showcases all of the settings (dark mode) in AppDelegate.
