### ISSUE TITLE
Disappearing when clicked outside the popup?

### ISSUE THREAD

**Issue by Dbigshooter** [Orderella/PopupDialog#129]
When I click outside the popup it close, which makes my post-logic not getting executed, am I missing something? I don't want the user to be able to click outside and thereby close the popup.

**Comment by mwfire** [comment]
If you want to disable gesture and background tap dismissal, you can do that at initialization time, parameter would be `gestureDismissal: false`. Further details can be found in README https://github.com/Orderella/PopupDialog#gesture-dismissal
