### ISSUE TITLE
iOS 8 support

### ISSUE THREAD

**Issue by animaonline** [Orderella/PopupDialog#13]
Hi, is there a reason why iOS is not supported? :)

**Comment by mwfire** [comment]
@animaonline Yes, the UI is based on [StackViews](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIStackView_Class_Reference/), which are only available in iOS 9.0 and later. I know that this is a harsh cut, but with iOS 10 just around the corner, this is an investment in the future as well :)

**Comment by animaonline** [comment]
Well, you could just use https://github.com/tomvanzummeren/TZStackView on iOS 8 

A lot of users still run iOS 8 for some reason

**Comment by mwfire** [comment]
@animaonline I wanted to minimize dependencies, however I can see that there is potential for iOS8 compatibility. This would not only affect stack views but animations as well.

I will keep you updated on this!

**Comment by mwfire** [comment]
@animaonline Did a test branch with TZStackView. Although it has the same API as UIStackView, it behaves differently and leads to some weird layout issues. Not an easy port, unfortunately. I will look into that over the next days...

**Comment by mwfire** [comment]
Published the first version to https://github.com/Orderella/PopupDialog/tree/feature/iOS8
I have prepared everything and replaced the stack views with the iOS8 compatible TZStackView.
It does not work out of the box, though. There is still work to do.

Feel free to help me out here :)

**Comment by iCyberon** [comment]
Hey @mwfire, managed to make it work with TZStackView (https://github.com/iCyberon/PopupDialog). There is a problem with pan gesture handling, though. For some reason it breaks constraints. Using symbolic breakdown find out that the reason is `TZStackView.updateConstraints()`. From the first look, it seems TZStackView observes changes to alpha and updates accordingly, but I didn't managed to find how to fix it. Could you please take a look?

**Comment by mwfire** [comment]
@iCyberon Thanks! I also replaced the regular stack view with TZStackView, on the `iOS8` branch

> Published the first version to https://github.com/Orderella/PopupDialog/tree/feature/iOS8

I hit the same problem as you, but did not have the time to check on it yet, so thanks for investigating. I will have a look asap.

**Comment by iCyberon** [comment]
@mwfire So disabling pan gesture makes it workable. I was thinking to typealias TZStackView to UIStackView for iOS 8 and make pan gesture available for iOS 9 and forward only. This way it'll continue to work for iOS 9 the way it works now and will optionally support iOS 8 w/o pan gesture. Not prefect, but users can still benefit from it.

**Comment by mwfire** [comment]
@iCyberon Sorry for my late reply and thanks so much for your efforts! I will go through this this weekend, if I could only buy myself time ;)

Cheers
Martin

**Comment by sansari** [comment]
@iCyberon would your branch work with a codebase that already has TZStackView included as a pod, or would that cause conflicts? I'm currently using it to allow usage of UIStackViews in our app, while still maintaining 8.x compatibility.

**Comment by iCyberon** [comment]
@sansari Should work just fine, if you included TZStackView as pod it should be in another module. But don't forget to remove the pan gesture.

**Comment by mwfire** [comment]
I made some progress this weekend: TLZStackView now works without any restrictions on iOS9. Ironically, it does not work with the default view on iOS8 yet. I'll keep you updated.

**Comment by mwfire** [comment]
Hi everyone! I have published a new `iOS8` branch today.

You can test this branch by adding the following to your Podfile `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'iOS8'`

All functionality of iOS 9 should now work as expected on iOS 8. Please give it a try and let me know what you think, if you experience any errors or glitches.

Carthage support has yet to be tested.

Thanks!

**Comment by iCyberon** [comment]
@mwfire Works fine 👍 Tested on iOS 8.1, 8.4, 9.3, 9.1. Guess you can merge with master 😉 Good job!

_P.S. Didn't test Carthage support._

**Comment by mwfire** [comment]
@iCyberon Thanks for testing! I just updated the readme for Carthage. Everything seems to be ok by now. I will release this branch asap.

**Comment by mwfire** [comment]
Pushed to master, commit 65f7a13, V 0.4.0.

**Comment by tnfelipe** [comment]
@mwfire I can't seem to build this version with carthage. Any idea why? (I need ios8 support in my project)

> github "Orderella/PopupDialog" ~> 0.4
> The following build commands failed:
>     Check dependencies
> (1 failure)
> A shell task (/usr/bin/xcrun xcodebuild -workspace "/Carthage/Checkouts/PopupDialog/Example/PopupDialog.xcworkspace" -scheme PopupDialog -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
> *\* CLEAN FAILED **

**Comment by leogeng** [comment]
I import this lib to Objective-c by pod 
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks
target ‘BaseProject’ do
pod 'PopupDialog', '~> 0.3'
end
```

 and always failed  as the following error:

> Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Then I try to add the following code:
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end
```

And it failed. Anybody can help me?

Thanks
