### ISSUE TITLE
navigationController will be hidden

### ISSUE THREAD

**Issue by smemamian** [Orderella/PopupDialog#131]
I have a custom view control to show my popup.

in this popup I have a button and I want to open another controller (`ContentAJobViewController `):

onClick my button:
```
        let vc = self.storyboard!.instantiateViewController(withIdentifier: "ContentAJobViewController") as! ContentAJobViewController
        vc.job_id = self.gh.id
        self.navigationController?.pushViewController(vc, animated: true)
```

I got an error because popup have not any navigation.

another way is to use this code:

```
       let controller = storyboard?.instantiateViewController(withIdentifier: "ContentAJobViewController") as! ContentAJobViewController
       controller.job_id = self.gh.id
        self.present(controller, animated: true, completion: nil)
```
but above code hide my navigation and I cannot come back to my popup.

I think I have to close my popup then open `ContentAJobViewController`.

Is there any solution?

**Comment by mwfire** [comment]
Hey @smemanian, does the example at #94 help?

**Comment by smemamian** [comment]
I don't want to use navigation in my popup! but second controller have a popup. 
I don't want to show the second controller in popup.

**Comment by mwfire** [comment]
Just like UIAlertController, PopupDialog is a view controller presented modally.
In theory you can present a view controller on a PopupDialog via `popup.present(viewController, animated: true, completion: nil)`. The `viewController` can be either a UINavigationController or a UIViewController.

It would not consider it best practice to present a view controller above the dialog. Therefore, your approach, dismissing the dialog and presenting the next view controller in the completion handler, is preferred.

**Comment by S-Masoud-Emamian** [comment]
"Therefore, your approach, dismissing the dialog and presenting the next view controller in the completion handler, is preferred."

How to finish current popup with click on a button and presenting another view controller?
please give me an example of `completion handler`.

**Comment by mwfire** [comment]
Are you using the PopupDialog buttons?

**Comment by S-Masoud-Emamian** [comment]
No. I'm using my custom buttons in popup.

**Comment by mwfire** [comment]
For code examples please see #66. Moreover, see the example project at https://github.com/mwfire/PopupDialogCustomExample
You can pass a reference to your PopupDialog to your view controller. This way, you can dismiss it from your custom button. The completion handler is documented in the readme and passed at initialization time.
