### ISSUE TITLE
Will it support NSMutableAttributedString

### ISSUE THREAD

**Issue by icefox57** [Orderella/PopupDialog#132]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report
Will it support NSMutableAttributedString?

at PopupDialogDefaultViewController
line 68  standardView.messageLabel.text = newValue
if change it to 

if newValue is NSMutableAttributedString {
                standardView.messageLabel.attributedText = newValue
 }else{
standardView.messageLabel.text = newValue
}

and set param to Any maybe is more better

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.11
- Xcode version (e.g. 8.0): 8.2.1
- PopupDialog version (e.g. 0.5.0): 0.5.4
- Minimum deployment target (e.g. 9.0): 9.3
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): pods
- Version (e.g. 1.1.0): ℹ 

## What did you do?
message with different color

## What did you expect to happen?

message with different color

## What happened instead?

did not support  NSMutableAttributedString

**Comment by mwfire** [comment]
Hey @icefox57,

You are talking about different colors within a single String right? Of course this does work with custom view controllers. One option would be to have a dedicated initializer for the default view controller. Would you mind doing a PR?

**Comment by icefox57** [comment]
My pleasure
