### ISSUE TITLE
Popup gets pushed partially off screen when a photo the size of the screen is added to the popup. 

### ISSUE THREAD

**Issue by arelenglish** [Orderella/PopupDialog#134]
# Report

## Environment
- Mac OS version: 10.12.4
- Xcode version: 8.3.1
- PopupDialog version: 0.5.4
- Minimum deployment target: 10.3
- Language: Swift 3.1

## Dependency management

- Dependency manager : CocoaPods 1.2.0

## What did you do?
I have a camera app. If a users portrait photo is added to a popup, it causes the popup to extend off the screen so you can't see the button(s). 

## What did you expect to happen?

I guess I was hoping the photo would get constrained some other way so that the popup wouldn't extend off the screen. 

## What happened instead?

See above.

**Comment by mwfire** [comment]
Hi @arelenglish, 

current logic is that is your responsibility to use an image that fits the screen/popup. For now, it is pinned to top, left, right while maintaining aspect ratio.

> I guess I was hoping the photo would get constrained some other way so that the popup wouldn't extend off the screen.

Please define "some other way".

Cheers
Martin

**Comment by arelenglish** [comment]
I was thinking the easiest way to resolve this type of issue would be to constrain the max height of the ImageView so the popup never extends off the screen, then the image could just use `Aspect Fill`, or you could pass the image display property as a parameter? 

I believe the above approach wouldn't affect any image that isn't too tall, and the occasional tall image would get appropriately scaled.

**Comment by mwfire** [comment]
That would mean image max height had to be aware of title and message height, I guess...
There is also plans on making the message scrollable if it would expand beyond screen size, which would have to be taken into account as well...

I am not entirely sure whether common usage justifies this level of complexity for edge cases, but if you could do a Pull Request for this, I'd be more than happy to implement this!

**Comment by arelenglish** [comment]
Good points. It might be a couple weeks, but I'll take a look and open a PR if I can figure something out that makes sense. 

Thanks!
