### ISSUE TITLE
Dismiss the popup while presenting another view controller

### ISSUE THREAD

**Issue by MaikoHermans** [Orderella/PopupDialog#135]
I want to present a view controller from a nib when I press a certain button from the `PopupDialog`

This is no problem it will present the viewcontroller just fine. But then this viewController gets dismissed when you press a certain button and the popup will still be open on the previous page which it should not be.

When I put dismiss to true when creating the popupdialog it will dismiss the view I'm trying to present instead of the popupdialog.

Is there any fix for this? Am I doing something wrong here?

**Comment by mwfire** [comment]
Hey @MaikoHermans,

PopupDialog is a view controller, it will be there until you dismiss it. The standard buttons can do it automatically, if you use your own in a custom view controller, you can pass a weak reference to popup dialog to your custom view controller. See https://github.com/mwfire/PopupDialogCustomExample
This way, you can dismiss the dialog once you touch up your custom buttons.

However, displaying view controllers on top of popup dialog is generally not a good idea. Just as with UIAlertController, you can dismiss the popup dialog and open the next VC in the completion handler. Make sure to present this VC on the same VC you presented the popup before.

**Comment by MaikoHermans** [comment]
Did not think about that. used the completion handler to present my view thanks!
