### ISSUE TITLE
ERROR ITMS-90087, 90635 and 90209

### ISSUE THREAD

**Issue by Jaspur** [Orderella/PopupDialog#138]
# Report
Failing when uploading to iTunes

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.12.4
- Xcode version (e.g. 8.0): 8.3.2
- PopupDialog version (e.g. 0.5.0): 
- Minimum deployment target (e.g. 9.0):  9.0
- Language (Objective-C / Swift):  Swift
- In case of Swift - Version (e.g. 3.0): Latest, just started project this week (where to check this?)

## Dependency management
- Dependency manager: carthage
- Version: 0.22.0

## What did you do?

Implemented to PopupDialog.

## What did you expect to happen?

It works when I run it via Xcode directly via USB to my iPhone, but when I try to upload it to iTunes it'll fail.

## What happened instead?

Fail when uploading to iTunes

```
ERROR ITMS-90087: "Unsupported Architectures. The executable for QRCodeReader.app/Frameworks/PopupDialog.framework contains unsupported architectures '[x86_64, i386]'."
ERROR ITMS-90087: "Unsupported Architectures. The executable for QRCodeReader.app/Frameworks/PopupDialog.framework contains unsupported architectures '[x86_64, i386]'."
```

```
ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "QRCodeReader.app/Frameworks/PopupDialog.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "QRCodeReader.app/Frameworks/PopupDialog.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(bitcode) and arm64(bitcode), while the nested bundle Mach-O contains X86_64ALL(machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
```

```
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'QRCodeReader.app/Frameworks/PopupDialog.framework/PopupDialog' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'QRCodeReader.app/Frameworks/PopupDialog.framework/PopupDialog' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
```

**Comment by mwfire** [comment]
Hey there,

as you are using carthage, please read through https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos

It sounds like you might be missing the `copy-frameworks` build phase.

Hope that helps :)

**Comment by mwfire** [comment]
Closed as of missing feedback.
