### ISSUE TITLE
using slider "WARangeSlider" in dialog

### ISSUE THREAD

**Issue by ahmedAlmasri** [Orderella/PopupDialog#139]
# Report

using slider "WARangeSlider" in dialog swipe not working 

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version 10.12
- Xcode version  8.0
- PopupDialog version 0.5.4
- Minimum deployment target 9.0
- Language (Swift)
- In case of Swift 3.1

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager  CocoaPods
- Version (1.1.0)

![untitled-1](https://cloud.githubusercontent.com/assets/14888785/25774377/10582cbe-3296-11e7-93a4-c1bd46bc20f9.gif)
.

**Comment by mwfire** [comment]
Hey there! Could you please provide a small example project. I cannot reproduce this right now.

Many thanks!

**Comment by ChanchalW** [comment]
Hi i am also facing this issue. My range slider is hanging.

**Comment by mwfire** [comment]
Hi @ChanchalW, could you please provide a small sample project showcasing the error?

Thanks!

**Comment by ChanchalW** [comment]
Sure

**Comment by ChanchalW** [comment]
Could you please check mail

**Comment by mwfire** [comment]
Thanks @ChanchalW, I will look into this over the coming days!

**Comment by ChanchalW** [comment]
Can you please suggest me any workaround for now, else i have to remove these classes, its very urgent. I committed to give delivery today.

**Comment by mwfire** [comment]
Ok, one thing we can try is:

Look up `tapRecognizer.cancelsTouchesInView = false` in PopupDialog source
Add `panRecognizer.cancelsTouchesInView = false` below, while unlocking the file.

Does that help?

**Comment by ChanchalW** [comment]
Ok thanks , I disabled gesture dismiss and dismiss it on button click. Now its working smooth.
And one more thing its also leg if table view is used in popup, it slow down its scrolling speed.

**Comment by kylebrowning** [comment]
Setting `panRecognizer.cancelsTouchesInView = false` Fixes this issue for your example in the PopupDialog-Example.

**Comment by ChanchalW** [comment]
Yes

**Comment by mwfire** [comment]
Thanks for checking this out, I will add this to the next release.

Cheers
Martin
