### ISSUE TITLE
So good, but do not support 8.0, want the future to support

### ISSUE THREAD

**Issue by LvJianfeng** [Orderella/PopupDialog#14]

**Comment by mwfire** [comment]
I am not sure if I understand, please clarify :)

**Comment by mwfire** [comment]
Do you want PopupDialog to support iOS 8?

**Comment by LvJianfeng** [comment]
Yes，Hope very much. A lot of app needs to support  8.0

**Comment by LvJianfeng** [comment]
I just hope that you can be used as a reference

**Comment by mwfire** [comment]
Thanks for you input!
iOS 8 compatibility is considered.
For further discussion, please refer to #13

Thanks again!

**Comment by mwfire** [comment]
@LvJianfeng Happy to announce that PopupDialog is now iOS8 compatible.
