### ISSUE TITLE
Disable backgound tapped

### ISSUE THREAD

**Issue by codwam** [Orderella/PopupDialog#141]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): ℹ
- Xcode version (e.g. 8.0): ℹ
- PopupDialog version (e.g. 0.5.0): ℹ
- Minimum deployment target (e.g. 9.0): ℹ
- Language (Objective-C / Swift): ℹ
- In case of Swift - Version (e.g. 3.0): ℹ

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): ℹ
- Version (e.g. 1.1.0): ℹ 

## What did you do?

ℹ Please replace this with what you did.  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

ℹ Please replace this with of what happened instead.  

## Project that demonstrates the issue

ℹ In complex cases, it might be useful to link to a sample project. If you don't provide an example, you can delete this section.

Add a property to  disable backgound tapped?

**Comment by mwfire** [comment]
Hey there, please check the README, there is a parameter you can pass on initialization called `gestureDismissal`.

Cheers

**Comment by codwam** [comment]
Thanks
