### ISSUE TITLE
clipsToBounds

### ISSUE THREAD

**Issue by codwam** [Orderella/PopupDialog#142]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): ℹ
- Xcode version (e.g. 8.0): ℹ
- PopupDialog version (e.g. 0.5.0): ℹ
- Minimum deployment target (e.g. 9.0): ℹ
- Language (Objective-C / Swift): ℹ
- In case of Swift - Version (e.g. 3.0): ℹ

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): ℹ
- Version (e.g. 1.1.0): ℹ 

## What did you do?

A content view with a close button pinned to top-right.

## What did you expect to happen?

the close button no be cliped.

## What happened instead?

The superview 

> clipsToBounds = true,

so the contentview clip the close button

## Project that demonstrates the issue

ℹ In complex cases, it might be useful to link to a sample project. If you don't provide an example, you can delete this section.

**Comment by mwfire** [comment]
Hey @codwam, this is expected behavior in order to allow for rounded corners. This does fit all our use cases. Changing this will break layout for previous versions, which is not desired.

Sorry, but there are no plans to change this :(
