### ISSUE TITLE
Installing Library Takes Forever

### ISSUE THREAD

**Issue by indrac** [Orderella/PopupDialog#143]
I try to install this library via cocoapods, but the installing is always get stuck (freeze). 
The version is `pod 'PopupDialog', '~> 0.5'`
Any solution for this issue?

**Comment by mwfire** [comment]
This is most certainly connected to Cocoapods. Please have a look at https://stackoverflow.com/questions/23755974/cocoapods-pod-install-takes-forever and let me know if any of the solutions solve your problem.
