### ISSUE TITLE
Popup sometimes not adjusting centerY when keyboard appears

### ISSUE THREAD

**Issue by jhchong92** [Orderella/PopupDialog#144]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.11.6
- Xcode version (e.g. 8.0): 8.2.1
- PopupDialog version (e.g. 0.5.0): 0.5.4
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.2

## What did you do?

The popup dialog does not shift its position after keyboard appear sometimes when editing a text field.
An easy way to re-create this is to pan downwards slightly, and press on a textfield immediately while the popup dialog bounces back into position. I didn't specifically tested for this behavior (being such an edge case), but I had just been clicking on text views normally and sometimes this problem occurs. I think a combination of drag+clicks will recreate this problem.
Setting gesture dismissal to false will prevent this from happening

## What did you expect to happen?

The popup dialog should move up when keyboard appears.

## What happened instead?

The popup dialog remained at same position and gets covered by the keyboard.

## Project that demonstrates the issue

The example in the project can demonstrate this issue.

<img width="318" alt="screen shot 2017-05-29 at 11 46 35 pm" src="https://cloud.githubusercontent.com/assets/16560316/26555707/169c2950-44c9-11e7-84b2-efef235824a8.png">

**Comment by kylebrowning** [comment]
I can confirm this is happening.

**Comment by alsojin0806** [comment]
我也遇到这个问题 不知道是不是约束 没合理的进行调整?

**Comment by mwfire** [comment]
Addressed with PR #174

**Comment by mwfire** [comment]
Released with V0.6.1
