### ISSUE TITLE
EXC_BAD_ACCESS in FXBlurView.m

### ISSUE THREAD

**Issue by fmatosic** [Orderella/PopupDialog#145]
# Report

## Environment

- Mac OS version (e.g. 10.12): 10.12.5
- Xcode version (e.g. 8.0):  8.3.2 (8E2002)
- PopupDialog version (e.g. 0.5.0): pod 'PopupDialog', '~> 0.5' 
- Minimum deployment target (e.g. 9.0): 9.3
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.1

## Dependency management
- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.2.0ℹ

## What did you do?

In ViewWillAppear calling a method which invokes the popupdialog
but it breaks with : EXC_BAD_ACCESS in FXBlurView.m
line 606:
[underlyingLayer renderInContext:context];

code for popupdialog:
  let pAllreadyLoggedPopup = PopupDialog(title: title, message: message)
  pAllreadyLoggedPopup.buttonAlignment = .horizontal
     let buttonOne = CancelButton(title: "CANCEL") {
         print("You canceled the car dialog.")
         }
         let buttonTwo = DefaultButton(title: "OK") {
         }
         pAllreadyLoggedPopup.addButtons([buttonOne, buttonTwo])
         // Present dialog
         self.present(pAllreadyLoggedPopup, animated: true, completion: nil)

**Comment by mwfire** [comment]
Hey @fmatosic,

just had a look and this might be related: https://github.com/BradLarson/GPUImage/issues/1376
I could not reproduce this so far :(

**Comment by fmatosic** [comment]
Hi @mwfire ,
I could send you the project (part of it) as on some viewcontrollers it works fine but on this
specific one its not. 
What I would like to know is what is the method : 
snapshotOfUnderlyingView
in FXBlurView.m doing
so I can rule out .
I also tried moving the invocation of the popup to run on the main queue but no luck.

**Comment by mwfire** [comment]
You can find info on FXBlurView by Nick Lockwood here: https://github.com/nicklockwood/FXBlurView

**Comment by fmatosic** [comment]
Commented out the blur effect and its fine now. 
PopupDialogOverlayView.swift line 109 addSubview(blurView).
guess this is outdated or problematic with  version we use.

**Comment by shrawan2015** [comment]
I have faced the same issue. Any update on it for the solution ? 
![crash](https://user-images.githubusercontent.com/10405305/30015981-b415e128-9170-11e7-8f1a-6b4fb37abc66.png)
