### ISSUE TITLE
Unwanted 1px line on left and right side of the image

### ISSUE THREAD

**Issue by adamsmaka** [Orderella/PopupDialog#146]
I think those vertical lines shouldn't be visible. They look really ugly.

![img_8735](https://user-images.githubusercontent.com/22574704/27013359-66ccaaf8-4ee2-11e7-8ced-aa11aa5b4b49.PNG)

**Comment by mwfire** [comment]
Hey @adamsmaka,

this is usually not the case. Can you investigate further where these lines come from? Is the image not resized correctly? Does this change when choosing smaller devices, like 5 or 4s?

Thanks,
Martin

**Comment by adamsmaka** [comment]
Thanks for respond @mwfire.
Vertical lines are visible on iPhone 7 screen size. On 7 Plus and SE there is a horizontal line on the top but only during sliding dialog in the case to dismiss it or when it is transitioning in or out.
The image is resized correctly. I tried to change the image size to exactly same dimensions what are in the example but it didn't help either. 

I have customized dialog so maybe it the problem because of it? Lines are the same color what PopupDialogContainerView.appearance() .backgroundColor

**Comment by mwfire** [comment]
Thanks @adamsmaka, that helps a lot. So images might not be resized pixel perfect... If you give the imageView a red background color, will these lines be red? Thanks for testing with me!

**Comment by adamsmaka** [comment]
> 'imageView' is inaccessible due to 'internal' protection level
:(

**Comment by mwfire** [comment]
True, however for finding the reason for this glitch, could you please set the color directly in the pod source code? You will have to unlock it, but you can undo the changes easily. Thanks for your help.

**Comment by adamsmaka** [comment]
Ok I have unlocked source code and yes, when I change bg color of imageView to red, lines are also red. So I changed also contentMode and problem is fixed.
From
`imageView.contentMode = .scaleAspectFit`
To
`imageView.contentMode = .scaleAspectFill`

**Comment by mwfire** [comment]
Thanks for your help! So it would actually make sense to expose the contentMode of the imageView, or the imageView as a whole...
I will add that as a feature to the next release.

**Comment by yfme** [comment]
Maybe it's a better idea to adjust the constraints than the contentMode.

PopupDialogDefaultView.swift
![popup](https://user-images.githubusercontent.com/568285/28928173-2695ec6a-789f-11e7-83eb-76beee58cb0f.png)

**Comment by mwfire** [comment]
@yfme, sorry for my late reply. I will look into this topic soon :)

**Comment by mwfire** [comment]
Released with #163
