### ISSUE TITLE
Any Reason buttons are fileprivate?

### ISSUE THREAD

**Issue by kylebrowning** [Orderella/PopupDialog#148]
Id like to write some extensions on top of this and both  buttonActin and buttons are fileprivate.

Theres no way to remove buttons once added, and no way to custom the button actions.

As an example, id like to change the button text based on a star rating value and its action based on that value. I can do this by adding references to everything but honestly itd be a lot cleaner if I could just be able to remove buttons, and add buttons at my will.

Cant do either via an extension so Im left with manually editing this class files and manually including them instead of building from carthage.

**Comment by mwfire** [comment]
Hey @kylebrowning,

one reason is to keep the API clean. One main goal for this plugin and our use cases is to keep it simple. Once you expose more and more properties, documentation will be more complex and there will be many different ways of doing things.

I agree, however, that there might be the need for more flexibility. That is one reason why we introduced the custom view controller.

Having said that, you are welcome to create a PR for the requested features.

Cheers
Martin

**Comment by kylebrowning** [comment]
@mwfire First of all, thanks so much for your work on this library, this comment is meant to be a discussion on why I think these fileprivates and finals are bad.

Keeping that API clean is completely doable without forcing your library users to not be allowed to modify certain things. Its just so limiting. As an example there are very many "issues" opened for this project requesting the ability to set width. Thats not something you need to maintain, we could just override it but...

We cant even override the constraints  because of the use of `final` in `final public class PopupDialogContainerView: UIView {` and  in my example that I opened as the original issue, Im forced to fork the project to remove `fileprivates` which just seem unnecessary, and plain wrong. 

`final` and `fileprivate` are both inferred on whole module optimization. This means if nobody extends or overrides, then `final` gets inferred and applied and you receive all the performance boost you can get.

It does make sense to use `final` to protect yourself when working with your own code.

If I override/extend a class of a library then I am knowingly going into deep waters, that I have to wade by myself. That risk is on me though, not you a library owner.

The main reason forking is painful is because I lose upstream changes unless I manage it myself. 

Considering you havn't made a change in 5 months this doesn't hurt as bad, but it really makes me, and I'm guessing others, turned off by the accessibility. Finally, If I fork, why would I bother using an extension(its real intended use), I'd just modify the code I need and be done with it. 

Consider removing `final` on top level class definitions and adding to things you think are vital to staying the way they are.

`func setupViews` is not one of them in my opinion and allowing others to work with it vastly increases the usability of this library.
