### ISSUE TITLE
Adding a View / table to popup ?

### ISSUE THREAD

**Issue by abinsmusthafa** [Orderella/PopupDialog#149]
Help Me - how to input a # **_ #Custom CELL TABLEVIEW_** properly in the pop up. I was wondering if you could help me with a problem. 

let title = "THIS IS THE DIALOG TITLE"
let message = "This is the message section of the popup dialog default view"
let image = UIImage(named: "pexels-photo-103290")

popup.addButtons([buttonOne, buttonTwo, buttonThree])
self.present(popup, animated: true, completion: nil)  /**_/ This is Only can Add Button And Present_**

**Comment by mwfire** [comment]
Hi @abinsmusthafa,

have a look at https://github.com/Orderella/PopupDialog/issues/87. You can find a link to a dialog with tableview there. Check it out.

Cheers
Martin
