### ISSUE TITLE
carthage not build dependency for FXBlurView

### ISSUE THREAD

**Issue by pengyunchou** [Orderella/PopupDialog#15]
when build, xcode report "dyld: Library not loaded: @rpath/FXBlurView.framework/FXBlurView"
could you remove FXBlurView from dependency?

**Comment by mwfire** [comment]
@aixinlove Thanks for pointing this out. Seems I did not test the PR for Carthage compatibility thoroughly enough :(

I have pushed the latest version that should fix this issue to the development branch.
Can you confirm that this is fixed?

You should be able to test the development branch by adding the following line to your Cartfile
`github "Orderella/PopupDialog" "development"`

Thanks again!

**Comment by mwfire** [comment]
Fixed with 0.3.1 release.
