### ISSUE TITLE
Gesture Recognizer for uiimage does not work- custom view controller

### ISSUE THREAD

**Issue by wajidp** [Orderella/PopupDialog#151]
gesture recognizer selector does not get fired for tapgesture but for self.view it works
gesture dismissal is false

    self.recordImage.isUserInteractionEnabled = true
        self.recordImage.addGestureRecognizer(
            UITapGestureRecognizer.init(target: self, action:
                #selector(onRecordImage(_:))
            )
        )
    
    
    func onRecordImage(_ sender: UIGestureRecognizer){
       print("tapped")
        }

**Comment by mwfire** [comment]
Hey @wajidp,

does this work for you now? If not, can you pass me a small example project, so I can reproduce it?

Thanks a lot
Martin
