### ISSUE TITLE
How can I  manual set size of xib?

### ISSUE THREAD

**Issue by dekphoenix** [Orderella/PopupDialog#154]
I want to set width and height that depend on screen

how can I manually set the size of xib file.

**Comment by mwfire** [comment]
There is no way of customizing width. Height, however, depends on the content.
This is the same behavior as with UIAlertController.

If you have an idea for a general approach that takes into account all screen sizes (iPhone 4s - iPad X), feel free to share it here :)

**Comment by Mohammed-Elias** [comment]
So there's no way to change the margin of the popup dialog ?

**Comment by mwfire** [comment]
Unfortunately, no. However,

> If you have an idea for a general approach that takes into account all screen sizes (iPhone 4s - iPad X), feel free to share it here :)

**Comment by hpbl** [comment]
A workaround to customizing the xib width would be to have the view with your content be a subview of the main xib view. And then make the main view transparent.
