### ISSUE TITLE
completion is triggered as soon as the dialog presented

### ISSUE THREAD

**Issue by dudil** [Orderella/PopupDialog#157]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.12.6
- Xcode version (e.g. 8.0): 8.3.3
- PopupDialog version (e.g. 0.5.0): 0.5.4
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocaPods
- Version (e.g. 1.1.0): 1.2.1

## What did you do?

I've tried to trigger the completion handler with some dismiss code on gesture enabled (no buttons) dialog

## What did you expect to happen?

Expected the completion function to be called only after the gesture was triggered and before dialog complete

## What happened instead?

completion is fired up as soon as the dialog is presented

This some code example:

```SWIFT
// Create the dialog
let popup = PopupDialog(title: title, message: message, transitionStyle: .fadeIn)
// Present dialog
self.present(popup, animated: true){() in print("completion")}
```
Result - completion is printed while dialog is still presented

**Comment by kylebrowning** [comment]
This is because self.present completion is the completion handler for when the ViewController has completed *showing* the vc. If you want completion of a button press and dismiss, its best to create your own button.
```swift
// Create the dialog
let popup = PopupDialog(title: title, message: message, transitionStyle: .fadeIn)
let button1 = DefaultButton{title: title, message: message, action: {
  print ("button1 completed and view dismissed")
}

popup.addButtons(button1)
// Present dialog
self.present(popup, animated: true){() in print("view displayed completion")}
```

**Comment by mwfire** [comment]
Yes, @kylebrowning is right :) In addition to what @kylebrowning suggested, you can also use the completion handler of the dialog, e.g.

```swift
let popup = PopupDialog(title: title, message: message, image: image) {
    // This will be called whenever Popup Dialog was dismissed
}
```

**Comment by dudil** [comment]
Thanks @mwfire , I understand now my mistake.
I was delegating the present completion handler instead of the init completion handler.

Got you - thank you for amazing utility :)
