### ISSUE TITLE
Change size of Popup?

### ISSUE THREAD

**Issue by the-freshlord** [Orderella/PopupDialog#158]
# Report
I was wondering if the size of the popup can be controlled?

## Environment
- Mac OS version (e.g. 10.12): 10.12.6
- Xcode version (e.g. 8.0): Xcode 9 Beta 4
- PopupDialog version (e.g. 0.5.0): 0.5.4
- Minimum deployment target (e.g. 9.0): 11.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): Swift 3.2

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.2.0

## What did you do?
Tried changing the frame of the controller 

## What did you expect to happen?
The size of the popup should be bigger. 

## What happened instead?
Animation showing the popup comes diagonal.

**Comment by mwfire** [comment]
Hey there!

Can you please specify "bigger": is that in width, height, or both?
Actually, width is fixed and cannot be changed up to now. Height will adapt to the size of the content.

Does that make sense?

**Comment by ThreadPitt** [comment]
Hi, 

would be great if **width** would also be changeable, though :-)

**Comment by mwfire** [comment]
Any suggestions on how to handle this across different device sizes like iPhone 5SE up to iPads?
Would that mean a fixed width for all devices? That would also mean all other screen sizes would have to adapt to the smallest screen width, isn't it?

Defining margins and a max-width might be the way to go, which is the current solution. However, these are not customizable yet. Do you think this would be sufficient?

**Comment by ThreadPitt** [comment]
Well, I have to admit that I'm not an iOS expert yet, that's why I use so many Cocoapods.
Yes, I guess from a user perspective something like max-width and/or margins would be sufficient, maybe in percentage.
And I wouldn't worry too much if the first solution doesn't work perfectly on all devices / rotations, as long as it is an optional parameter and the possible issues are documented!

I searched a lot and I didn't find any other decent popup / modal solution that also works with a custom ViewController...

**Comment by melcug** [comment]
From within of popup is there a way to resize the view specially for height?

**Comment by the-freshlord** [comment]
@mwfire I was thinking really the height

**Comment by mwfire** [comment]
I am really trying to understand the use case for height:
the dialog adapts to the height of the content, just as the regular system dialog.
If you want a specific height, you can use a custom view controller.

If you can see broad usage for setting a specific height while at the same time supporting all devices from iPhone 4s to iPad Air, please contribute with a Pull Request.

Same is true for width: there were some requests so far but no comprehensive solution was provided.

Thanks!

**Comment by mwfire** [comment]
P.S. I will close this for now, feel free to mention PRs here.
