### ISSUE TITLE
Random crash on PopupDialog , not reproducible easily. 

### ISSUE THREAD

**Issue by shrawan2015** [Orderella/PopupDialog#160]
# Report
## Environment

- Mac OS version (e.g. 10.12.5): 10.12.5
- Xcode version (e.g. 8.0): 8.3
- PopupDialog version (e.g. 0.5.0):  0.5
- Minimum deployment target (e.g. 9.0): 8.0
- Language (Objective-C / Swift):  swift 
- In case of Swift - Version (e.g. 3.0): 3 

## Dependency management
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods):  CocoaPods
- Version (e.g. 1.1.0):    1.2.0

## What did you do?
Crash while using the app.

## What did you expect to happen?
Do not crash

## What happened instead?
App crashed while testing.

**Crash reported on the crashlytics log are attached below.** 

![crash](https://user-images.githubusercontent.com/10405305/30020052-2cea3266-9180-11e7-8831-6cfbb582fcfe.png)

**Comment by mwfire** [comment]
Hey there, is there any way you could send me an example project? As you mentioned, it seems not easy to reproduce and I did never hit this case while testing.

**Comment by shrawan2015** [comment]
Currently, we cannot give the client project, But I saw it again while I run the project.
If you could figure out why it is happening by below logs then it will be helpful for us.



![crashimage](https://user-images.githubusercontent.com/10405305/30154983-3da37be8-93d9-11e7-8f0a-b7cd96358aff.png)

**Comment by mwfire** [comment]
Sure, of course I was not expecting the full project, just a small example the in best case would demonstrate the issue.

FXBlurview was not done by me but is included in the lib. afaik, this crash can happen if there is problems with the underlying views.

Btw., what does the console log when crashing?

**Comment by shrawan2015** [comment]
We couldn't get the console log. But it is **reproducing** again. 
Screenshot we got from analytics tool of apple.


![screen shot 2017-09-21 at 16 23 56](https://user-images.githubusercontent.com/10405305/30692496-6c03c9d2-9ee9-11e7-8898-8116737cbffe.png)

**Comment by mwfire** [comment]
This is definitely an issue with FXBlurView: https://github.com/nicklockwood/FXBlurView/issues/120
I will keep an eye on this but so far I was not able to reproduce it.

**Comment by hieutnbk** [comment]
I hit this issue in my project when use PopupDialog to show custom content, hope this issue is fixed soon.

**Comment by mwfire** [comment]
@hieutnbk So far, I cannot reproduce it. Please provide further information, that is, crash logs and most importantly: an example project showcasing this issue. Thanks a lot!

**Comment by mwfire** [comment]
Also, which version of PopupDialog are you currently on?

**Comment by mwfire** [comment]
@shrawan2015, @hieutnbk, do you have have `liveBlur` enabled? As mentioned in #167

**Comment by shrawan2015** [comment]
@mwfire I haven't used liveBlur. Current PopupDialog is latest on, which supports Swift-3. 
i.e 'PopupDialog', '~> 0.5'

**Comment by mwfire** [comment]
FXBlurView was replaced with DynamicBlurView with the latest development version and can be tested on the development branch. Just change your pod file to `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

Please report any findings here. Thanks for testing 👍
