### ISSUE TITLE
Custom PopupDialog click events and TextField not working

### ISSUE THREAD

**Issue by krishnameena** [Orderella/PopupDialog#164]
![simulator screen shot 18-sep-2017 7 55 35 pm](https://user-images.githubusercontent.com/10487399/30546988-c7d7fb10-9cab-11e7-866f-2060abc9e1b5.png)

I have created a custom PopupDialog as above in screenshot but the button click events for Ok and Cancel are not working as well as TextField (comment)  and Stepper are also not working.

Please help me out what wrong I am doing.

**Comment by mwfire** [comment]
Hey @krishnameena,

that sounds like an auto layout issue. If you set your controllers view `clipsToBounds` to `true`, will the views be hidden? Also, you could use the View Hierarchy Debugger and see if your views are layed out as expected.

**Comment by krishnameena** [comment]
Yes, after setting cliksToBounds to true view is hidden.

I have used view hierarchy and it is showing warning as (Height and vertical positions are ambiguous in UiView) in below attached screenshot.

<img width="847" alt="screen shot 2017-09-19 at 11 39 20 am" src="https://user-images.githubusercontent.com/10487399/30578849-a0c82a1c-9d33-11e7-9778-fab487a0f87e.png">


Please let me know what can I do to get rid of this behaviour.

**Comment by krishnameena** [comment]
<img width="1067" alt="screen shot 2017-09-19 at 12 30 55 pm" src="https://user-images.githubusercontent.com/10487399/30579485-7e89a66c-9d36-11e7-8991-7129c5b75578.png">

Hi, you can see the detailed constraints in above screenshot

**Comment by mwfire** [comment]
Phew, I don't think I am good at remote debugging Autolayout. Did you have a look at the example project? Star rating is a custom view controller and showcases how to layout constraints.

**Comment by krishnameena** [comment]
Hi, I have tried using that also but it is not working. Please let me now if some workaround is there, otherwise I will have to go for another option.
Thanks.

**Comment by mwfire** [comment]
Can you please send me an example project showcasing this issue?

**Comment by krishnameena** [comment]
Please give me your email or let me know how should I share with you.

**Comment by krishnameena** [comment]
[PopupDialog Sample.zip](https://github.com/Orderella/PopupDialog/files/1320613/PopupDialog.Sample.zip)

Please find attached sample project

**Comment by mwfire** [comment]
Hi there,

please find attached an updated version that works. I did not update all constraints, as your structure is very complicated. I would recommend opting for stack views instead regular view containers.

[PopupDialogSample.zip](https://github.com/Orderella/PopupDialog/files/1322436/PopupDialogSample.zip)

I also recommend looking at the rating example. The position of the dialog is not customizable.
I will close this issue for now, as this is not a PopupDialog related issue.

Hope that helps.

**Comment by krishnameena** [comment]
Thank you so much for the information. But I would like to ask one thing what exactly you have changed in the sample which I have uploaded? As per me I think you have changed to view controller size to freeform and fixed width as well as height.

**Comment by mwfire** [comment]
No problem. The height of the dialog is inferred from your view. You don't need to set the height explicitly as I did in your case, but you need a seamless chain of constraints from top to button. In your case, the "ok cancel" view would need a constraint to the bottom.

However, width is handled by PopupDialog based on the screen size. That is why you must not set a fixed value for width, but rather make sure to have leading and trailing, that is, left and right margin set.

Setting the view controller size to freeform makes it easier to design and lay out the constraints.

**Comment by krishnameena** [comment]
Thanks a lot again. 👍

**Comment by mwfire** [comment]
Sure thing :)
