### ISSUE TITLE
iOS 8 Support

### ISSUE THREAD

**Issue by olegsehelin** [Orderella/PopupDialog#170]
Guys is it possible to return iOS 8.0 support into version 0.6 ? Thanks.

**Comment by mwfire** [comment]
Hey there, sorry, but there are no plans to do so. We are supporting three major iOS releases, only 2% of all devices are running on iOS 8 and lower.

The 0.5.4 release still supports iOS 8, Swift 3

You can give it a try though, this commit should work for Swift 4 while still supporting a fallback UIStackView:
pod 'popupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :commit => ' 6c8c42b'

Cheers
Martin

**Comment by olegsehelin** [comment]
Thanks guys. Your suggestion works well.

**Comment by mwfire** [comment]
Good to hear! :)
