### ISSUE TITLE
Re-centering Popup after UIPickerView Dismissal

### ISSUE THREAD

**Issue by drewg233** [Orderella/PopupDialog#172]
Having an issue re-centering the popup after dismissal of a UIPickerView. I set a breakpoint in the pod and `centerPopup()` in `PopupDialog+Keyboard.swift` is indeed being called after I press the "DONE" button you see below, but it does not recenter. How can I fix this?

![Alt Text](https://media.giphy.com/media/l378hM4NFsrAkQp7a/giphy.gif)

**Comment by mwfire** [comment]
Hey @drewg233,

can you do a small example project that showcases the issue? I cannot reproduce it with the example project.

![pickercentering](https://user-images.githubusercontent.com/1749092/31407848-b82bef0c-ae06-11e7-9220-aaae7d2fd8e4.gif)

Thanks!

**Comment by drewg233** [comment]
Hey! Thanks for you quick response. Let me see if I can..

**Comment by drewg233** [comment]
Hmm you are right. I implemented this into the example project and do not get the same outcome. Thank you for looking into this! Ill keep digging in my project.

**Comment by mwfire** [comment]
Thanks @drewg233, please let me know about your findings :)

**Comment by drewg233** [comment]
Still cant figure out a ton of information, just know that `centerYConstraint.constant` never changes. Its always 0. Even when `popupCenter` equals something other than 0, the constant never gets set to that value.

**Comment by mwfire** [comment]
Could you please sum up the environment you are on, that is Cocoapods version, PopupDialog version, Simulator device, iOS? Might make it easier to replicate your scenario. Thx!

**Comment by drewg233** [comment]
So ya its my fault. I had a fork of this pod. I added the ability to change the width of the popup (It's a requirement I need in my app). And that seemed to be affecting it. Sorry. Thanks for looking into this though and being so responsive.
