### ISSUE TITLE
Unsupported Swift Version - Xcode 9

### ISSUE THREAD

**Issue by yoterpa** [Orderella/PopupDialog#178]
# Report

## Environment

- Mac OS version (e.g. 10.12): 10.12.6
- Xcode version (e.g. 8.0): 9.0
- PopupDialog version (e.g. 0.5.0): 0.6.0
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Objective-C + Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management

- Dependency manager (e.g. CocoaPods): Cocoapods
- Version (e.g. 1.1.0): 1.3.1

## What did you do?

I tried to integrate `PopupDialog` in my Objective-C+Swift project using Xcode 9.

## What did you expect to happen?

It worked alright when I did it in some other project in Xcode 8. I expected the same smooth integration with Xcode 9 as well.

## What happened instead?

Got the following error:
```
Unsupported Swift Version
The target “PopupDialog” contains source code 
developed with Swift 2.x. Xcode 9 does not support
building or migrating Swift 2.x targets.
Use Xcode 8.x to migrate the code to Swift 3.
```

Since there are no posts regarding this issue, so apparently no one else is experiencing it.

What am I missing here? Is there any other option than to patch the source by unlocking `PopupDialog`'s Pod source files?

**Comment by mwfire** [comment]
Hey @yoterpa,

hmm, that's weird. Does `pod deintegrate` and a reinstall via `pod install` solve this issue?

**Comment by mwfire** [comment]
Hey @yoterpa, any updates on this? Otherwise I would close it...

**Comment by yoterpa** [comment]
Hey @mwfire, sorry for the delay! I resolved this issue a few days ago by changing the `Swift Language Version` to **4.0** in Pods Target for _PopupDialog_. Thanks BTW for this awesome library and also for taking the time to respond 😊

**Comment by mwfire** [comment]
Sure thing! Thanks, cool you could solve it 👍
