### ISSUE TITLE
Custom ViewController Crash

### ISSUE THREAD

**Issue by aabanaag** [Orderella/PopupDialog#180]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): ℹ 11.0
- Xcode version (e.g. 8.0): ℹ 9.0
- PopupDialog version (e.g. 0.5.0): ℹ Latest
- Minimum deployment target (e.g. 9.0): ℹ
- Language (Objective-C / Swift): ℹ Swift
- In case of Swift - Version (e.g. 3.0): ℹ 4.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): ℹ Cocoapods
- Version (e.g. 1.1.0): ℹ 

## What did you do?

Initialized PopupDialog with custom viewcontroller

    let summaryVC = SummaryViewController(nibName: "Summary", bundle: nil)
    let popup = PopupDialog(viewController: summaryVC)
    self.present(popup, animated: true, completion: nil)

## What did you expect to happen?

It should display the nib layout as Popup.

## What happened instead?

![image](https://user-images.githubusercontent.com/2245822/32604009-ddb27970-c586-11e7-9596-446653b2f084.png)

## Project that demonstrates the issue
This is the sample nib or xib

![image](https://user-images.githubusercontent.com/2245822/32604025-ebdb98c4-c586-11e7-9a92-6de034ea71cc.png)

Followed the instructions to add constraints, but will it be possible to disregard the PopupButtons?

**Comment by aabanaag** [comment]
I created the said design because I need to append "check" or "X" on the buttons. If it can be done using the DefaultButton it would gladly help. 👍

**Comment by mwfire** [comment]
@aabanaag Could you please share the console output after the app crashes? Thx!

**Comment by mwfire** [comment]
Hey @aabanaag, any updates on this? Otherwise I will close this...

**Comment by aabanaag** [comment]
sorry just bust from work. will send log over the weekend

-- 
Alexis Banaag
