### ISSUE TITLE
Default Button with image on left

### ISSUE THREAD

**Issue by harshalonerooftech** [Orderella/PopupDialog#183]
![unnamed](https://user-images.githubusercontent.com/17043990/32937852-1f7be4f8-cba0-11e7-85e6-02c43568bdc1.jpg)

I want to create this kind of structure with using DefaultButton
How could I do this

**Comment by mwfire** [comment]
This is not possible with the default buttons, but you could consider using a custom view controller with your own buttons and use PopupDialog only as a container. If you pass a (weak) reference to PopupDialog to your custom VC, you can still dismiss it and access all functionality with your own buttons.

You can get an idea here https://github.com/mwfire/PopupDialogCustomExample
