### ISSUE TITLE
Setting Width

### ISSUE THREAD

**Issue by drewg233** [Orderella/PopupDialog#184]
I know this library has been avoiding being able to set the width of the popup, but it is a requirement for my iPad app would love to continue to use this library for it. I know others have asked for it too. Ever consider have the default to 340 and allowing/telling the developer to change at their own risk?

**Comment by mwfire** [comment]
Hey @drewg233!

> consider have the default to 340 and allowing/telling the developer to change at their own risk?

No, because iPhone 5, 5s, 5c, SE, 4 and 4s have a screen width of 320. Some of these, especially the SE, are still relevant and PopupDialog automatically adapts to those widths.

You are welcome to do a PR that tackles these conditions while providing an accessible way of setting widths. Please also keep in mind that we are trying to avoid breaking changes for Swift and Objective-C. However, if implementation requires breaking changes, we could implemented this with a 0.7 release.

What do you think?

**Comment by drewg233** [comment]
Couldn't do something like?

Sudo code:
`var popupWidth = userSetWidth <= (deviceWidth - 50) ? userSetWidth : 340`

**Comment by mwfire** [comment]
Cool, let me think about this a bit :)

**Comment by drewg233** [comment]
Sounds good :smile:

**Comment by mwfire** [comment]
Hey @drewg233, I published a branch for testing.

You can test by temporarily replacing the standard PopupDialog pod in your Podfile with `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'feature/preferredWidth'`

There's now an additional option `preferredWidth` for the dialog initializer. By default it is 340, which would not introduce any breaking changes. If you actively set it, PopupDialog will try to set the provided width for iPad screens. This does not have any effect on iPhone screens.

Could you please give it a try and see if that works for you?

Thanks!

**Comment by drewg233** [comment]
Sorry I just saw your message. Thanks for this! This is exactly what I need. I was able to test on iPad Mini 2 and my iPhone X so far. Works great on both.

**Comment by drewg233** [comment]
Thanks for doing this! Will you be merging with master?

**Comment by mwfire** [comment]
Hey @drewg233, sure thing! I will push this to master very soonish, as I have a few other changes, but you don't have to wait for long ;)

**Comment by khanskt786** [comment]
I was trying to change prefered width to custom value in landscape mode on iPhone XR simulator, so I was wondering Is this feature available for all iphone models? I tried to set preferedWidth manually to 70% for screen width but its not taking effect. I have checked with breakpoints value of preferedWidth and its showing the correct width value what I am setting it to. When the dialog appears it does not change the width of dialog. I have tested on physical device also (iPhone 6).

**Comment by carlosvalenzuela0193** [comment]
> I was trying to change prefered width to custom value in landscape mode on iPhone XR simulator, so I was wondering Is this feature available for all iphone models? I tried to set preferedWidth manually to 70% for screen width but its not taking effect. I have checked with breakpoints value of preferedWidth and its showing the correct width value what I am setting it to. When the dialog appears it does not change the width of dialog. I have tested on physical device also (iPhone 6).


I've been trying to do the same thing for weeks, just like an iPhone 6 physicist, but I have not been able to change the width, since my app requires dialogues that are smaller.
