### ISSUE TITLE
underlyingLayer is coming out nil and crashes the app upon calling self.present(popup,...)

### ISSUE THREAD

**Issue by ramkashyap17** [Orderella/PopupDialog#186]
snapshotOfUnderlyingView function is throwing an error:
Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

if (self.needsDrawViewHierarchy)
        {
            __strong UIView *underlyingView = self.underlyingView;
            [underlyingView drawViewHierarchyInRect:underlyingView.bounds afterScreenUpdates:YES];
        }
        else
        {
            [underlyingLayer renderInContext:context]; //On this line
        }

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12.8)
- Xcode version (e.g. 9.1)
- PopupDialog version (e.g. 0.5.0)
- Minimum deployment target (e.g. 11.0)
- Language: Swift
- In case of Swift - Version (e.g. 4.0)

**Comment by ramkashyap17** [comment]
Ok.

Doing this: 

let overlayAppearance = PopupDialogOverlayView.appearance()
        
        overlayAppearance.blurEnabled = false
        overlayAppearance.liveBlur    = false

in viewDidLoad solves the problem.

**Comment by mwfire** [comment]
Hey there! Yeah, the error hints to FXBlurView. Can you do me favor and send me a small example project showcasing the bug? It is almost impossible to reproduce, unfortunately...

**Comment by mwfire** [comment]
FXBlurView was replaced with DynamicBlurView with the latest development version and can be tested on the development branch. Just change your pod file to `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

Please report any findings here. Thanks for testing 👍

**Comment by mwfire** [comment]
Released with V0.7.0
