### ISSUE TITLE
Hide status bar issue

### ISSUE THREAD

**Issue by MickaelCruzDB** [Orderella/PopupDialog#187]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.13.1
- Xcode version (e.g. 8.0): 9.1
- PopupDialog version (e.g. 0.5.0): 0.6.2
- Minimum deployment target (e.g. 9.0): 11.1
- Language (Objective-C / Swift): Swift 
- In case of Swift - Version (e.g. 3.0): 4

## What did you do?

```
    @objc func logoPopUpTapped(tapGestureRecognizer: UITapGestureRecognizer)
    {
        
        // Prepare the popup assets
        let title = "Copyright Dominique Viet 2017"
        let message = "Application développée par Digitalblend"
        
        // Create the dialog
        // Create the dialog
        let popup = PopupDialog(title: title,
                                message: message,
                                buttonAlignment: .horizontal,
                                transitionStyle: .zoomIn,
                                gestureDismissal: true,
                                hideStatusBar: true) {
                                    print("Completed")
        }
        
        // Create buttons
        let buttonOne = CancelButton(title: "Fermer") {
            print("You canceled the car dialog.")
        }
        
        popup.addButtons([buttonOne])
        
        // Present dialog
        self.present(popup, animated: true, completion: nil)

    }
```

## What did you expect to happen?

I expected that the status bar doesn't appear.

## What happened instead?

When the popup appears statusbar appears too during 1sec then it disappears without any touch on screen. I would like to never see the statusbar.

**Comment by mwfire** [comment]
Hey there! In your application Info.plist, did you set `UIViewControllerBasedStatusBarAppearance` to `true`?

**Comment by MickaelCruzDB** [comment]
Hi! Thanks for your reactivity! The issue was the Info.plist file! Thanks a lot!

**Comment by mwfire** [comment]
Sure thing! Actually, it might be worth mentioning this in the docs :)
