### ISSUE TITLE
Header file missing declarations for Objective-C

### ISSUE THREAD

**Issue by jasewells** [Orderella/PopupDialog#189]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 9.1
- PopupDialog version (e.g. 0.5.0): 0.6
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): Objective-C

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): Carthage
- Version (e.g. 1.3.1): 0.26.2

## What did you do?

Tried to use PopupDialog 0.6 (0.6.2) in an Objective-C project. However, it seems the PopupDialog-Swift.h resulting from the Carthage framework build doesn't have declarations for initWithTitle and initWithViewController methods. The problem seems specific to 0.6; in the previous version it integrated with Objective-C fine.

To reproduce…

- Created a new project in Xcode using Objective-C.
- In the project folder, created a Cartfile with this line:
github "Orderella/PopupDialog" ~> 0.6
- Ran "carthage update" (PopupDialog framework built fine)
- Dragged PopupDialog.framework into the project Linked Frameworks and Libraries
- In Build Settings added $(PROJECT_DIR)/Carthage/Build/iOS to framework search paths
- In ViewController.m added this line:
#import <PopupDialog/PopupDialog-Swift.h>
- Then in viewDidLoad started typing…
[[PopupDialog alloc] init

…but only "initWithCoder" autosuggests:

<img width="763" alt="screen shot 2017-12-02 at 4 40 16 pm" src="https://user-images.githubusercontent.com/2709381/33521175-8f32c4f2-d77f-11e7-882a-19f67328f950.png">

Looking at PopupDialog-Swift.h, the PopupDialog interface only declares these:

/// Creates a Popup dialog similar to UIAlertController
SWIFT_CLASS("_TtC11PopupDialog11PopupDialog")
@interface PopupDialog : UIViewController
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
/// Replaces controller view with popup view
- (void)loadView;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
@property (nonatomic, readonly) BOOL prefersStatusBarHidden;
@property (nonatomic, readonly) UIStatusBarAnimation preferredStatusBarUpdateAnimation;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end

## What did you expect to happen?

Expected header file to declare methods for initWithTitle… and initWithViewController… methods, so Xcode can autocomplete and build with them in Objective-C files.

## What happened instead?

Those methods don't show up, so there's no way to init a PopupDialog in Objective-C.

If I change my Cartfile to fetch the previous release version (0.5.4) and rebuild/update, then the header file includes the missing methods and Xcode auto-complete and building works.

Not sure if something is wrong in the 0.6 line, or if Objective-C support is discontinued, or I'm just doing something wrong with that version?

**Comment by mwfire** [comment]
Hey @jasewells, thanks for reporting this! I will look into this asap.

**Comment by ice6** [comment]
thanks for this wonderful project :)

@mwfire I encounter the same problem, I am using pod.

~~I will try to fix this.(just add some @objc for swift 4)~~
~~I will do a pull request if I finished, thank you very much.~~

I found that you made some improvement after V 0.6.2 so I think it will be better for you to fix the problem, thanks in advance. just add some `@objc` for the missing part will do a great help for objective-c users.

**Comment by che1404** [comment]
Hi there! I just experienced this when I tried to use the latest (0.7.0) from Objective-C, in a project configured with Swift 4.
I think it'll be a matter of adding some @objc to properly expose the API to Objective-C, as @ice6 said.

**Comment by animaonline** [comment]
Should be easy to fix.

**Comment by mwfire** [comment]
@animaonline Nice! Can you do a PR for this? Thx!

**Comment by mwfire** [comment]
Fixed by @julienpouget in https://github.com/Orderella/PopupDialog/pull/208
Currently on develop branch, can be tested via `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

**Comment by mwfire** [comment]
Included in https://github.com/Orderella/PopupDialog/pull/211
