### ISSUE TITLE
Fade animation duration parameter

### ISSUE THREAD

**Issue by metisdev** [Orderella/PopupDialog#190]
First of all thanks for the library 👍 

It would be nice to have duration parameters for fade animation. In and out values.

Best

**Comment by mwfire** [comment]
Hey @metisdev,

this is something on my roadmap. I am planning to drop Obj-C compatibility with V 1.0. This way, associated values could used for animation duration. However, this will still take a while... :(

**Comment by nick-iCars** [comment]
Have you tried using the speed property of a uiview's layer? Not sure if it would work in this case but definitely something to try.

from https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreAnimation_guide/AdvancedAnimationTricks/AdvancedAnimationTricks.html : 

> When thinking about timing and animations, it is important to understand how layer objects work with time. Each layer has its own local time that it uses to manage animation timing. Normally, the local time of two different layers is close enough that you could specify the same time values for each and the user might not notice anything. However, the local time of a layer can be modified by its parent layers or by its own timing parameters. For example, changing the layer’s speed property causes the duration of animations on that layer (and its sublayers) to change proportionally.
