### ISSUE TITLE
Image requirements

### ISSUE THREAD

**Issue by justdan0227** [Orderella/PopupDialog#192]
What are the image requirements.  I have @1, @2, and @3 in my Assets, and when I use one in the dialog its huge vs just a small icon.

**Comment by mwfire** [comment]
Hey @justdan0227,

just as with any other image view you can provide your assets as you described. From the Readme

> If you provide an image it will be pinned to the top/left/right of the dialog. The ratio of the image will be used to set the height of the image view, so no distortion will occur.

This is the way how the default dialog works. If you want e.g. a centered icon, you have to add the padding to the image. If you do not want to do that, you can use a custom view controller. These can be customized to your needs.

Hope that helps!

**Comment by justdan0227** [comment]
Thanks but should I base the size I want off of the @3 image, so if I want a 50x50 the @3 should be 50x50.  Right now the @1 is 50x50 yet the image in the popup is huge like 200x200

**Comment by mwfire** [comment]
Hey @justdan0227,

the image will be scaled up to fill the imageView. ~320 x ~320 in your case. If you just want a centered icon, you would have to add the padding in the image (maybe sthg. like 320 x 120 for @1) and center the icon. This is how the default dialog works at the moment. For any other use cases, you could use a custom view controller.

Have a look at the example project and how the images are laid out there.

Hope that helps!

**Comment by CristianCardosoA** [comment]
We just want to do this hahaha                 

pvc.standardView.imageHeightConstraint?.constant = 40
