### ISSUE TITLE
Can the background be semi-transparent? 

### ISSUE THREAD

**Issue by ETmanwenhan** [Orderella/PopupDialog#193]
Can the background be set transparent?  can see the contents of the bottom ViewController.
So how do we do that? Thank you!

**Comment by ETmanwenhan** [comment]
> modalPresentationStyle = .overFullScreen

The above Settings can solve this problem, but when using the zoomIn animation, setting the background View with black translucent, the background animation is not very good.
Is there a better solution?

**Comment by mwfire** [comment]
Hey there,

You can adjust the dialog appearance via global appearance settings, as of the README example:

```swift
let overlayAppearance = PopupDialogOverlayView.appearance()
overlayAppearance.color  = .black
overlayAppearance.blurRadius = 20
overlayAppearance.blurEnabled = true
overlayAppearance.liveBlur = false
overlayAppearance.opacity = 0.7
```

If you set blurEnabled to false, you will still be able to adjust the overlay color and opacity.

Hope that helps :)

**Comment by ETmanwenhan** [comment]
@mwfire 
Is it set in the PresentationController?

```swift
final internal class PresentationController: UIPresentationController {

    /*
    fileprivate lazy var overlay: PopupDialogOverlayView = {
        return PopupDialogOverlayView(frame: .zero)
    }()
     */
    
    fileprivate lazy var overlay: PopupDialogOverlayView = {
        
        var overlayAppearance = PopupDialogOverlayView(frame: .zero)
        overlayAppearance.color       = UIColor.yellow
        overlayAppearance.blurRadius  = 20
        overlayAppearance.blurEnabled = true
        overlayAppearance.liveBlur    = false
        overlayAppearance.opacity     = 0.6
        return overlayAppearance
    }()
   ...
```

**Comment by ETmanwenhan** [comment]
Thank you!

**Comment by mwfire** [comment]
Hey there!

As it is global, you could set it in the app delegate. Please have a look at the example project. There is an example that showcases how to use appearance: https://github.com/Orderella/PopupDialog/blob/master/Example/PopupDialog/AppDelegate.swift

It's currently commented but you can uncomment it to give it a try!
