### ISSUE TITLE
Unable to install pod

### ISSUE THREAD

**Issue by tawrahim** [Orderella/PopupDialog#2]
I have been trying to include the library using cocoapods but it appears that there is an error.

![screen shot 2016-06-26 at 11 56 15 am](https://cloud.githubusercontent.com/assets/943594/16363340/2183cbea-3b95-11e6-941c-18ff2d7234b7.png)

**Comment by tawrahim** [comment]
I updated my deployment target and everything seems to be working as expected.

**Comment by mwfire** [comment]
Great you got it working :) Please note that I just pushed V0.1.4 which allows for more control over the transition animation. Whenever you have feedback, just let me know. Thanks :)

**Comment by tawrahim** [comment]
@mwfire  awesome! I am going to run `pod update` to get the new changes.
