### ISSUE TITLE
Swift 3 issues

### ISSUE THREAD

**Issue by Minitour** [Orderella/PopupDialog#20]
I am using the master branch , and it appears that the popup dialog have lost their overlay.
I then configured the pod to use the swift3 branch, however it appeared that the framework was downgraded from 0.3.0 to 0.2.0, and this makes sense because I also lost the functionality of dragging the dialogs.

**Comment by mwfire** [comment]
Thanks @Minitour, I will investigate and keep you updated!

**Comment by Minitour** [comment]
I decided to switch back to the Master branch. After I used "pod install" and launched my project, as expected, Xcode asked me to convert the framework to the latest swift syntax. I converted it and it left me with few syntax issues which I fixed manually. I then ran the project and it worked normally. There were no issues and everything was working fine.

**Comment by mwfire** [comment]
Thanks for your feedback, @Minitour. I will keep an eye on this, let me know if you experience any issues.

Cheers
Martin

**Comment by mwfire** [comment]
Let's further discuss this in #7
