### ISSUE TITLE
gestureDismissal = false in initializer doesn't turn off swipe dismiss

### ISSUE THREAD

**Issue by chanonly123** [Orderella/PopupDialog#201]
gestureDismissal = false in initializer doesn't turn off swipe dismiss

**Comment by mwfire** [comment]
Hey there!

I cannot reproduce this, it works for me so far. Can you please share a demo project showcasing this issue? Thanks!

**Comment by chanonly123** [comment]
Very sorry for late response. The issue is diffrent. gestureDismissal = false is working. The issue is the buttons should have touchUpInside to dismiss, but uses touchUpOutside also. Try touch and drag the button outside the view and release, the popup gets dismissed.

**Comment by mwfire** [comment]
Can't reproduce this either. Our code is actually

```
button.addTarget(self, action: #selector(buttonTapped(_:)), for: .touchUpInside)
```

As the issue title is indicating a problem with _gestureDismissal=false_, I would suggest opening a new issue while attaching an example project showcasing the issue.

Thanks a lot!
