### ISSUE TITLE
PopupDialog Won't Present after First one is Dismissed

### ISSUE THREAD

**Issue by aparande** [Orderella/PopupDialog#203]
## Environment

- Xcode version (e.g. 9.1): 9.2
- PopupDialog version (e.g. 0.5.0): 0.7.0
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.3.1): 1.4.0

## What did you do?

I am using PopupDialog to allow users to login and signup. I have two viewcontrollers, one for logging in and another for signing up. When the user clicks the "Create Account" button in the login dialog, I want to dismiss the login dialog and create the signup dialog. I implemented this in a extension of PopupDialog because it is used several times in my code.

```
extension PopupDialog {
    static func getPopupDialog(for type: String, controlledBy viewController: UIViewController) -> PopupDialog {
        let cancelButton = CancelButton(title: "CANCEL", action: nil)
        if type == "Login" {
            // Create the login dialog
            let lvc = UIStoryboard(name: "Account", bundle: nil).instantiateInitialViewController()! as! LoginViewController
            let loginPopup = PopupDialog(viewController: lvc)
            
            //Create some buttons
            let loginButton = DefaultButton(title: "Login", dismissOnTap: false) {
                //Login
            }
            
            let createButton = DefaultButton(title: "Create Account", dismissOnTap: false) {
                loginPopup.dismiss() {
                        let signupPopup = self.getPopupDialog(for: "Signup", controlledBy: viewController)
                        viewController.present(signupPopup, animated: true, completion: nil)
                }
            }
            
            //Add the buttons
            loginPopup.addButtons([loginButton, createButton, cancelButton])
            return loginPopup
        } else {
            //Create the signup dialog
        }
    }
}
```
## What did you expect to happen?

As I mentioned, I wanted the login popup to dismiss when I click the "Create Account" button and then show the "Create Account" Dialog

## What happened instead?

However, the Login Dialog dismissed, but the "Create Account" Dialog never presented. There are no console errors, and breakpoints verify that the function is being called. Moreover, I can't interact with the view controller that presented the Login Dialog anymore once the Login Dialog dismisses. What is going wrong here?

**Comment by mwfire** [comment]
Hey there!

I am not seeing any specific problem here, but remote debugging is never easy.
Let's give it a try and, as your Login dialog seems to work as expected, just for now change

```
 let signupPopup = self.getPopupDialog(for: "Signup", controlledBy: viewController)
```

to

```
 let signupPopup = self.getPopupDialog(for: "Login", controlledBy: viewController)
```

Does that work as expected?

**Comment by aparande** [comment]
Yes, that worked as expected!

```
//Create the signup dialog
            let svc = UIStoryboard(name: "Account", bundle: nil).instantiateViewController(withIdentifier: "Signup") as! SignupViewController
            let signupPopup = PopupDialog(viewController: svc, transitionStyle: .bounceDown)
            
            let backButton = DefaultButton(title: "Back", dismissOnTap: false) {
                signupPopup.dismiss({
                    let loginPopup = self.getPopupDialog(for: "Login", controlledBy: viewController)
                    viewController.present(loginPopup, animated: true, completion: nil)
                })
            }
            
            let signupButton = DefaultButton(title: "Signup", dismissOnTap: false) {
                //Handle output
            }
            
            signupPopup.addButtons([signupButton, backButton, cancelButton])
            return signupPopup
```

Is how I am creating the signup popup. When i replaced
` let svc = UIStoryboard(name: "Account", bundle: nil).instantiateViewController(withIdentifier: "Signup") as! SignupViewController` with `let svc = UIStoryboard(name: "Account", bundle: nil).instantiateInitialViewController()! as! LoginViewController`, it works as expected

**Comment by mwfire** [comment]
So there might be a problem with the layout constraints in SignupViewController. However, the buttons should be displayed, even if there is a issue with the custom view controller...

**Comment by aparande** [comment]
It turns out that in the ViewDidLoad method of my SignupViewController, I was setting a single UIVIew to be the subview of two different custom text fields. Removing the UIView solve the issue. Thank you for all your help!
