### ISSUE TITLE
How to disable user interaction, if user tap outside the view

### ISSUE THREAD

**Issue by ghost** [Orderella/PopupDialog#206]
am showing one PopupDialog after clicking on a button.
Now popup is visible, now if user tap outside of the popup. the popup is getting disappear.
so, how to achieve this ? 
How to disable user interaction outside of the popup ?

**Comment by mwfire** [comment]
As described in the readme:

```
public convenience init(..., gestureDismissal: false, ...) 
```

> Gesture Dismissal
Gesture dismissal allows your dialog being dismissed either by a background tap or by swiping the dialog down. By default, this is set to true. You can prevent this behavior by setting gestureDismissal to false in the initializer.
