### ISSUE TITLE
Cant get this to work on my project

### ISSUE THREAD

**Issue by ryandailey100** [Orderella/PopupDialog#21]
I have the pod installed, but i can not seem to access anything from the class. Do i have to import anything? Readme is confusing for a first time user.

**Comment by mwfire** [comment]
Hey @ryandailey100, did you have a look at the example app? I did my best to cover common scenarios. As of Swift, you have to `import PopupDialog` in the files where you want to use the dialog. 

What part of the readme do you find confusing? Would you mind creating a pull request with your suggested improvements?

Thanks!
Martin

**Comment by ryandailey100** [comment]
When i tried importing PopupDialog, it does not find it. I've used pods before (my project has firebase and googlemaps), so i am not too sure why this one isnt working. And for the readme, it doesnt say to import PopupDialog.

**Comment by mwfire** [comment]
@ryandailey100 Have you tried to clean (Shift + ⌘ + K) and build (⌘ + B) again?

**Comment by ryandailey100** [comment]
I will try and let you know once i get home, thanks

**Comment by ryandailey100** [comment]
It works after doing the clean. Thanks!!

**Comment by mwfire** [comment]
@ryandailey100 Sure thing! :)
