### ISSUE TITLE
Resize PopupDialog

### ISSUE THREAD

**Issue by ikyh** [Orderella/PopupDialog#210]
- Xcode version :  **9.2**
- PopupDialog version : **0.5**
- Minimum deployment target : **8.0**
- Language (Objective-C / Swift):  **Swift**
- In case of Swift - Version (e.g. 4):  **3/4**

## What did you do?
I have to show a popDialog with a title, a tableView and Cancel/Confirm buttons at the bottom. I have used .xib to design my view. I have set the height constraint to the tableView. 

## What did you expect to happen?
 I want the popupDialog to be of a custom size. The size I want it to be.

## What happened instead?
Instead the popupDialog occupies the whole screen, specially the height. Also the width is not resizable. I tried setting the frame of the view of .xib but it does not work. Please guide on what can be done.

The UI looks somewhat better in iphone 8 simulator, but bad in iphoneSE simulator.

**Comment by mwfire** [comment]
Hey there!

Width is determined automatically and roughly resembles UIAlertController. It will adapt to all devices, but never exceed 340. In newer versions of PopupDialog, you can set a preferredWidth for larger devices. Unfortunately, this is not possible with V0.5.

Height, however, depends on the content of your custom view controller. If your content is larger than the screen, it will be extended beyond the screen. You have to make sure to set a fixed height yourself, as we cannot know what parts of your view controller should scroll and if there should be fixed parts.

Have a look at https://github.com/Orderella/PopupDialog/issues/87
