### ISSUE TITLE
Custom View does appear hidden independent of the size of the container

### ISSUE THREAD

**Issue by breakline87** [Orderella/PopupDialog#212]
# Report

When using a custom nib file even if the size is set the view does or does not appear depending on its content.

## Environment

- Xcode version (e.g. 9.1): 9.2
- PopupDialog version (e.g. 0.5.0): 0.7
- Minimum deployment target (e.g. 9.0): 11.2
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4

## Dependency management

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.3.1): 1.4.0

## What did you do?

I created a nib file based on a suggestion in the closed thread about this issue:

![screen shot 2018-02-23 at 9 13 37 am](https://user-images.githubusercontent.com/7821133/36584403-dbabc406-1879-11e8-89bd-e7a5a75a26e3.png)

This works just fine. However if I delete one element here:

![screen shot 2018-02-23 at 9 14 02 am](https://user-images.githubusercontent.com/7821133/36584422-e94fd890-1879-11e8-91c1-2d81697dc595.png)

The whole dialog disappears. If I set the buttons then only the buttons appear.

## What did you expect to happen?

Dialog size should be only dependent on the view frame size and not on its content/constraint

## What happened instead?

Dialog size seems to be dependent on the content of the dialog

**Comment by katunch** [comment]
Same Issue here... i can't figure out where's the difference to the excample

**Comment by katunch** [comment]
ahh got the trick... you have to pass auto layout constraints from top to bottom... like in an uiscrollview
