### ISSUE TITLE
custom view doesn't show elements

### ISSUE THREAD

**Issue by BhavinBhadani** [Orderella/PopupDialog#213]
Customview doesn't show elements .. just a plain black blur 
![simulator screen shot - iphone 7 - 2018-02-24 at 18 03 26](https://user-images.githubusercontent.com/11731407/36630488-0dc03012-198d-11e8-924c-80a0f66b2731.png)

This is my xib

![screen shot 2018-02-24 at 6 03 53 pm](https://user-images.githubusercontent.com/11731407/36630493-23651ce8-198d-11e8-8775-009fad607d4e.png)

**Comment by BhavinBhadani** [comment]
Customview doesn't show elements .. just a plain black blur 
![simulator screen shot - iphone 7 - 2018-02-24 at 18 03 26](https://user-images.githubusercontent.com/11731407/36630488-0dc03012-198d-11e8-924c-80a0f66b2731.png)


This is my xib

![screen shot 2018-02-24 at 6 03 53 pm](https://user-images.githubusercontent.com/11731407/36630493-23651ce8-198d-11e8-8775-009fad607d4e.png)

**Comment by mohammadabushalhoob** [comment]
make sure you add top and bottom constraint .

**Comment by iqbalprabu** [comment]
hi, i get them same issue with this code ?
can help me 

`class PopupOfficeViewController: UIViewController  {
    
    var vBackground: UIView!
    var tvProjectName: UILabel!
    var tvProjectID: UILabel!
    var ivOffice: UIImageView!
    var ivProject: UIImageView!
    var edtProjectId: UITextField!
    var btnNext: MDCButton!
    
    
    override func viewDidLoad() {
        
        setupView()
    }
    
   
}

extension PopupOfficeViewController {
    
    func setupView() {
        //
        
        let screenSize: CGRect = UIScreen.main.bounds
        
        view.backgroundColor = .white
        
        vBackground = UIView()
        vBackground.backgroundColor = UIColor.init(named: "colorPrimary")
        
        view.addSubview(vBackground)
        
        
        
        initConstraint()
        
    }
    
    func initConstraint() {
        //
        NSLayoutConstraint.activate([
            vBackground.topAnchor.constraint(equalTo: view.topAnchor),
            vBackground.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            vBackground.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            vBackground.bottomAnchor.constraint(equalTo: view.bottomAnchor)
//            ivOffice.topAnchor.constraint(equalTo: view.topAnchor, constant: 10),
//            ivOffice.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 20),
//            tvProjectName.leadingAnchor.constraint(equalTo: ivOffice.trailingAnchor, constant: 10),
//            tvProjectName.trailingAnchor.constraint(equalTo: view.trailingAnchor)
            
        ])
    }
    
}`
