### ISSUE TITLE
UINavigationViewController as the custom content view controller

### ISSUE THREAD

**Issue by mobilinked** [Orderella/PopupDialog#214]
Hello,

I have the problem to present a UINavigationViewController as the content in the popup dialog on the iPad. The popup dialog height is same as the window height and this cause the popup dialog buttons disappeared, although heightAnchor auto-layout is activated to the navigation view. 

There is no problem to present a common UIViewController with heightAnchor added. 

Would you please help to suggest how I can present the navigation view controller? 

Thanks,

**Comment by mwfire** [comment]
Hey there!

Have a look at https://github.com/Orderella/PopupDialog/issues/87. the project linked here uses a tableView, but this also works for navigation controllers. However, you have to give the navigation controller a fixed height. this way, the dialog won't overshoot the screen. This project was meant to be a simple UIAlertView, so this kind of navigation might work, but is not "supported", so to speak...

Cheers
Martin
