### ISSUE TITLE
Callback when dismissing via gesture

### ISSUE THREAD

**Issue by tal** [Orderella/PopupDialog#219]
It'd be useful to be able to run a callback when the dialog is dismissed via a gesture.

I'd make a PR myself but I'm not familiar with the `UIPercentDrivenInteractiveTransition` and how it's being used. I'll do some research and loop back but if it's easy for you add quickly I'd be very grateful.

Thanks

**Comment by mwfire** [comment]
Hey there! A callback is already implemented and called, but for all dismissals, including buttons. Do you mean this should be specifically for gesture dismissals?

**Comment by tal** [comment]
Yes, basically I'm registering the exit of the modal manually when each of the buttons are tapped and need it registered when you dismiss via gesture.

If I put logic in general dismissal logic it ends up firing twice when dismissed via button. I could put in some locking mechanism but that's fairly janky.

That being said not hugely important, and would do myself if I understood the transition api.

Thanks!

**Comment by mwfire** [comment]
Hey @tal, makes sense, I will look into it.
