### ISSUE TITLE
Attempt to present <PopupDialog.PopupDialog: 0x7fef6f416760> on <PopupDialog.PopupDialog: 0x7fef6f502c60> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by herotheone** [Orderella/PopupDialog#220]
I can't present second VC  on the completion handler of firstVC dismiss.

Why is that ? 

**mainVC.swift**
```
import UIKit
import PopupDialog

class mainVC: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()

        
    }

    @IBAction func startButtonPressed(_ sender: Any) {
        
        // Create a custom view controller
        let vc = firstVC(nibName: "firstVC", bundle: nil)
        
        // Create the dialog
        let popup = PopupDialog(viewController: vc, buttonAlignment: .horizontal, transitionStyle: .bounceDown, gestureDismissal: true)
       
        vc.popup = popup
        
        // Present dialog
        present(popup, animated: true, completion: nil)
        
    }
    
}
```

**firstVC.swift**

```


import UIKit
import PopupDialog

class firstVC: UIViewController {

    public weak var popup: PopupDialog?
    
    override func viewDidLoad() {
        super.viewDidLoad()

        
    }

    @IBAction func closeButtonPressed(_ sender: Any) {
        popup?.dismiss()
    }
    
    @IBAction func open2ndVC(_ sender: Any) {
        popup?.dismiss({
            
            let vc2 = secondVC(nibName: "secondVC", bundle: nil)
            let popup2 = PopupDialog(viewController: vc2, buttonAlignment: .horizontal, transitionStyle: .bounceDown, gestureDismissal: true)
            vc2.popupFor2ndVC = popup2
            self.popup?.present(popup2, animated: true, completion: nil)
        })
    }
    }
```

**secondVC.swift**

```
import UIKit
import PopupDialog

class secondVC: UIViewController {
    public weak var popupFor2ndVC: PopupDialog?
    
    override func viewDidLoad() {
        super.viewDidLoad()
            print("SecondVC loaded")
    }
}
```

**Comment by mwfire** [comment]
Hey there!

You have to present the second PopupDialog on the same view controller you present the first one on. It looks to me you are currently trying to present dialog 2 on dialog 1, but that one is dismissed already at that point and must not be accessible anymore.

**Comment by herotheone** [comment]
Can you help me with that ?

**Comment by mwfire** [comment]
Does that change work? Admittedly, I am not the best GitHub comment coder ;)

```swift
@IBAction func open2ndVC(_ sender: Any) {
    popup?.dismiss({
         ...
         present(popup2, animated: true, completion: nil)
    })
}
```

**Comment by herotheone** [comment]
Nope :( Still got same error :(

**Comment by mwfire** [comment]
Phew, in that case: would it be possible to pack up a small project showcasing the error and upload it here? Remote comment debugging is really not too helpful...

**Comment by herotheone** [comment]
Here you go mate : 
https://github.com/herotheone/example

**Comment by mwfire** [comment]
Hey there,

I updated the project accordingly. Essentially, I am passing in a reference to the main view controller to firstVC. This is the view controller to present the 2nd view controller on. As mentioned above, the first PopupDialog is not in the view hierarchy anymore, once dismissed.

[example-master-revisited.zip](https://github.com/Orderella/PopupDialog/files/1849272/example-master-revisited.zip)

A few notes:

- struct, class, protocol, enum names: always uppercase! :)
- Do not set a fixed width on the custom view controller for the PopupDialog. The width will be adapted to the screen size, fixed widths will break the constraints.

Hope that helps :)

**Comment by herotheone** [comment]
Hello again mwfire,
Thank you for your reply. I tried to run your project but i got the error like : 

**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIViewController startButtonPressed:]: unrecognized selector sent to instance 0x7fa22cc0afa0'**

**Comment by mwfire** [comment]
Oops, that was me renaming the classes. This one should work, sry.

[example-master-revisited.zip](https://github.com/Orderella/PopupDialog/files/1849366/example-master-revisited.zip)

**Comment by herotheone** [comment]
All working thank you so much for your support !!! :)

**Comment by mwfire** [comment]
Sure thing! :)
