### ISSUE TITLE
Retain cycle in example code

### ISSUE THREAD

**Issue by ExplosiveBattery** [Orderella/PopupDialog#222]
More information is in #43 (I have given a solution to the old issue)

**Comment by ExplosiveBattery** [comment]
make a pull request #224 which has solved all problem

**Comment by mwfire** [comment]
Hey there! Good catch, actually I just realized I did not merge this change back then. Actually,

```swift
// Create fourth (shake) button
let buttonTwo = DefaultButton(title: "SHAKE", dismissOnTap: false) { [weak popup] in
    popup?.shake()
}
```

is the way to avoid that retain cycle. Regarding the pull request, I will have a look as soon as I can.

**Comment by mwfire** [comment]
Fixed with latest update.
