### ISSUE TITLE
Push to Next View Controller Clicked on Book Now Button.

### ISSUE THREAD

**Issue by Nitinbond** [Orderella/PopupDialog#225]
Hello there,
How to push to next view controller clicked on Book Now PopUp Button
![screen shot 2018-04-05 at 4 23 19 pm](https://user-images.githubusercontent.com/11436995/38362377-40ad732e-38ee-11e8-9db3-194ae143125a.png)

Please resolve my problem.
Thanks 
Nitin Kumar

**Comment by Nitinbond** [comment]
I am Using Custom View Controller with .xib file.

**Comment by sandeepan512** [comment]
Hello Martin Wildfeuer
Can solve my this problem?

**Comment by mwfire** [comment]
Hey there, have a look at https://github.com/mwfire/PopupDialogCustomExample
It is a quick demo on how you would select a city from a tableView, but the use case is the same.

**Comment by Nitinbond** [comment]
i want to push to next view controller while i select city but it's not working.

**Comment by mwfire** [comment]
Please give a bit more detail on what you tried and what is not working, thx!

**Comment by xhidnoda** [comment]
@Nitinbond  please use protocol delegate..... 
1. Create protocol whit one func in your xib file.
2. When you click in your xib file call the protocol delegate.
3. Implement the protocol in your VC where you call your xib file.. (vc.delegate = self)
4. In your implementation execute the func and call another VC (present).

**Comment by Nitinbond** [comment]
Hello can you send me a demo ?

Nitin Kumar
Mob-No : +91-9005976013
Email : nitinbond@live.in<mailto:nitinbond@live.in>

On 16-Apr-2018, at 6:35 PM, xhidnoda <notifications@github.com<mailto:notifications@github.com>> wrote:


@Nitinbond<https://github.com/Nitinbond> please use protocol delegate.....

  1.  Create protocol whit one func in your xib file.
  2.  When you click in your xib file call the protocol delegate.
  3.  Implement the protocol in your VC where you call your xib file.. (vc.delegate = self)
  4.  In your implementation execute the func and call another VC (present).
