### ISSUE TITLE
Can I force an OK key press in custom dialog when enter is pressed in text field?

### ISSUE THREAD

**Issue by kehollin** [Orderella/PopupDialog#227]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 9.2
- PopupDialog version (e.g. 0.5.0): 0.7.0
- Minimum deployment target (e.g. 9.0): 9.3
- Language (Objective-C / Swift): Swift 
- In case of Swift - Version (e.g. 4): 4

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.3.1):  ?

## What did you do?

Created custom dialog with text fields, an OK button and a Cancel button. 

## What did you expect to happen?

When enter/return key is pressed I would like the dialog to respond as if the OK button was pressed.

## What happened instead?

Nothing happens, similar to the custom dialog in your examples.

## Project that demonstrates the issue

ℹ In complex cases, it might be useful to link to a sample project. If you don't provide an example, you can delete this section.

**Comment by mwfire** [comment]
Hey @kehollin, sorry for my late reply. Sure, you can have a weak reference to the PopupDialog in your custom view controller. (See https://github.com/mwfire/PopupDialogCustomExample). This way, you can trigger button taps with

```swift
public func tapButtonWithIndex(_ index: Int)
```

Hope that helps :)

**Comment by kehollin** [comment]
Thanks Martin, will try it out. Also thank you very much for the awesome
library! It may be selective blindness, but I couldn't find a "donate" link
on the GitHub page. Is there another way to buy you a pint (or a few) in
appreciation? :)


Kevin Hollingshead
Research Software Engineer

*Arizona State University*
*College of Health Solutions*
*School of Nutrition and Health Promotion*
602-615-9972 (cell)

On Sun, Apr 29, 2018 at 12:25 AM, Martin Wildfeuer <notifications@github.com

**Comment by mwfire** [comment]
Hey there! Thanks, glad this library helps you :) No donation needed, appreciation in the comments is more than enough :) Cheers!

**Comment by kehollin** [comment]
Working on another piece where this dialog will be extremely useful. Thanks again!
