### ISSUE TITLE
Is it possible to add custom viewController through pure code?

### ISSUE THREAD

**Issue by dlfkid** [Orderella/PopupDialog#229]
I've seen the example but I prefer to coding with out xib or story board because I feel unfamiliar with them.

**Is there an example for pure code user to create an custom viewController?**

Some thing like:

setup your constrains in here:

xxxxx

Many thx!

**Comment by mwfire** [comment]
Hey there!, Sorry for my late reply, back from holidays now :)
Have a look at https://github.com/mwfire/PopupDialogCustomExample
the custom view controller is done entirely in code.

Hope that helps :)

**Comment by dlfkid** [comment]
Well thank you for that ! It's exactly what I need !

Yet I figured out another simple solution like this:

in ViewController.swift

`override func updateViewConstraints() {

      super.updateViewConstraints()

      let widthConstraint:NSLayoutConstraint = NSLayoutConstraint(item: self.view, attribute: .width, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1.0, constant: viewWidth)

      let heightConstraint:NSLayoutConstraint = NSLayoutConstraint(item: self.view, attribute: .height, relatedBy: .equal, toItem: nil, attribute: .notAnAttribute, multiplier: 1.0, constant: VIEWHEIGHT)

      self.view.addConstraints([widthConstraint, heightConstraint])

  }`

But you can't place it in specific position cause it has no superView, so only works if the view is designed to present in the center of the screen.
