### ISSUE TITLE
dismissViewControllerAnimated is not working for custom view controller

### ISSUE THREAD

**Issue by mlight3** [Orderella/PopupDialog#23]
I found the solution for this from issue #16, but I think it should be opened again. 
I use same code as #16 , but it is a little bit tricky. Also in a [Custom View Controller](https://github.com/Orderella/PopupDialog#custom-view-controller) section, you says 

> Being a subclass of view controller, this can be easily done via dismissViewControllerAnimated(flag: Bool, completion: (() -> Void)?).

I found about two solutions for this. 
1. Use addChildViewController in PopupDialog class & use parentViewController in Subclass ViewController.
2. Created class for subclassing that has presenter variable. Then assign presenter inside PopupDialog.

Which one is better? I think first one is simple. 😄

**Comment by mwfire** [comment]
@mlight3 Thanks for your feedback! There are various ways to tackle this, from completion blocks to delegates as well as the ones mentioned by you. The main idea is that you will want to call `dismissViewControllerAnimated` on the dialog at a certain point (Btw., the dialog also exposes a shorthand method called `dismiss()`). How you do it is completely up to you.

Having said that, the intention of this dialog was to be a replacement for UIAlertController and will be used in our production app. It was never meant to be used without adding buttons. Although it is possible, as you know, this is not really a feature. :)

If you are planning to use a dialog as a container for custom views only, I'd suggest having a look at https://github.com/IcaliaLabs/Presentr, which might be more helpful in your case.

Thanks :)
Martin

**Comment by mlight3** [comment]
@mwfire Okay. I understood what you mean. Thanks. :)
