### ISSUE TITLE
Get notified of dismissed popup in view controller

### ISSUE THREAD

**Issue by devwithzachary** [Orderella/PopupDialog#231]
My PopupDialog has a custom view controller and is created following the example project provided like:

```
let ratingVC = PopupViewController(nibName: "PopupViewController", bundle: nil)
        ratingVC.apiKey = self.apiKey
        ratingVC.accountNumberString = accountNumberString        

        let popup = PopupDialog(viewController: ratingVC, buttonAlignment: .horizontal, transitionStyle: .bounceDown, gestureDismissal: true)
        ratingVC.presentedPopup = popup
self.present(popup, animated: true, completion: nil)
```

This works fine however within the viewController in certain conditions the popup will get dismissed with:

`self.dismiss(animated: true)`

How do I know in the launching view controller when the popup dialog has been dismissed in this way?

**Comment by glennposadas** [comment]
I've posted an answer on your SO thread :) https://stackoverflow.com/a/50256605/3231194
