### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by cwestMobile** [Orderella/PopupDialog#232]
Howdy, if this isn't an appropriate question just let me know and I'll close it out.

I have a custom popup with a couple labels and buttons, etc. What i'm hoping to do is set the values of those labels and buttons when calling the popup dialog. Similar to how you can set the default button text.

Can you give me any advice/pointers on how to accomplish this?

Thanks so much.

**Comment by mwfire** [comment]
Hey there,

not sure if I understand correctly, but if you want to change values inside your custom view controller, you should be able to do so by just keeping a reference to it, like

```swift
let customVC = CustomVC(nibName: "CustomVC", bundle: nil)
let popup = PopupDialog(viewController: customVC)
present(popup, animated: true)

// Now you can change the label text
customVC.myLabel.text = "Some text"
```

Does that make sense?

Cheers
Martin

**Comment by cwestMobile** [comment]
That works like a charm, I was trying to change the values too early in the method.

Thanks
