### ISSUE TITLE
Feature request: Only disable pan gesture (so background tap is still enabled)

### ISSUE THREAD

**Issue by kevinvanmierlo** [Orderella/PopupDialog#234]
I have a UIScrollView in the popup, so I wanted to remove the pan gesture. But if I set gestureDismissal to false it also disables the background tap. Since it is not available yet I would like to request this feature to only disable the pan gesture and leave the background tap enabled.

**Comment by mwfire** [comment]
This was addressed in https://github.com/Orderella/PopupDialog/pull/215
I will be looking into this within the next days.

**Comment by kevinvanmierlo** [comment]
Awesome! Looking forward to it

**Comment by mwfire** [comment]
This is now ready to test :) In your Podfile, specify
`pod 'PopupDialog', :git => '/github.com/Orderella/PopupDialog/PopupDialog.git', :branch => 'develop'` to use the develop branch.

**Comment by kevinvanmierlo** [comment]
Sorry, I haven't had the time to test it yet. We've just disabled the background tap for this version and in the next update we'll include this fix.  Thanks for the fix by the way :)
