### ISSUE TITLE
Avg memory usage?

### ISSUE THREAD

**Issue by cwestDev** [Orderella/PopupDialog#237]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 9.4
- PopupDialog version (e.g. 0.5.0): 0.7
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): Cocoapods
- Version (e.g. 1.3.1): Latest

## What did you do?

I am using PopUp dialog to open a custom UIViewController from a tableView cell.

## What did you expect to happen?

Not use too much memory.

## What happened instead?

It goes from 100mb -> 150mb -> 200mb -> 250mb as I scroll the tableView and select cells.

Any ideas? If you need a link to my project let me know.

**Comment by mwfire** [comment]
Hey @cwestDev,

that sounds like PopupDialog and/or your custom view controllers do not get deallocated. Do you have a reference to PopupDialog in your custom view controller that is not weak? For a quick check, you can add a completion block to PopupDialog and see if it gets called.

You can also use Instruments with memory allocations to see if any instances of PopupDialog dialog do not get deallocated as expected.

**Comment by cwestDev** [comment]
Thanks for the quick response. Yeah I feel comfortable saying the popup related views are not being deallocated. I am in over my head trying to wrangle instruments but doing research now in regards to it. This is 99.9% something I'm doing wrong, and not your project so I apologize for opening an issue.

**Comment by cwestDev** [comment]
If there is anyway you could maybe take a look at my project? If not I completely understand, just let me know and I can close this issue out. Cheers!

**Comment by mwfire** [comment]
Hello sir, sorry for my late reply. Let's have a look at this together! If you do not want to share the whole project, you could do a tiny demo showcasing the issue :)

**Comment by cwestMobile** [comment]
Would it be possible for me to send it to you in an email? I have videos showcasing the issue but don't feel all that comfortable showing them here. If it isn't an option that is fine, I will post them here just let me know.

If you want to try to replicate this make a simple project with a View Controller with maybe 15 cells. You can use a default popup dialog without any images or anything. Open the popupdialog in the 'didselectcell' function. As you scroll and open the popupdialog it should not release the popup dialog and memory should grow infinitely.

Let me know if that needs clarification. Thanks.

**Comment by mwfire** [comment]
Hey there! Sure, my email address can be found here: https://github.com/mwfire

**Comment by alkanyunus** [comment]
This is my issue also. But I cannot find the memory leaks
