### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by ryandailey100** [Orderella/PopupDialog#24]
<img width="1367" alt="screen shot 2016-08-16 at 12 40 41 am" src="https://cloud.githubusercontent.com/assets/15038444/17710602/f500fc6a-63bb-11e6-8e8b-23245b61a3b4.png">

After installing this pod, I am unable to debug. Any ideas?

**Comment by mwfire** [comment]
Hey @ryandailey100. Have you tried to clean (Shift + ⌘ + K) and build (⌘ + B) again?
Deleting derived data might be another step. It seems very unlikely that this is related directly to this library.

**Comment by mwfire** [comment]
Closing this now. Let me know if you still experience problems.
