### ISSUE TITLE
Corner radius not working

### ISSUE THREAD

**Issue by calismatest** [Orderella/PopupDialog#242]
the following code block does not work

```
let containerAppearance = PopupDialogContainerView.appearance()
containerAppearance.cornerRadius    = 20
```

**Comment by mwfire** [comment]
Hey @calismatest,

works for me. Does the example project work for you, if you uncomment corner radius appearance in AppDelegate? Where do you set the appearance in your code?

**Comment by joshxplor** [comment]
@mwfire encounter the same thing. if you don't set anything before cornerRadius it won't work. it actually returns 0 for new value, but if you have something like setting the color then corner radius it works properly. I tested it out with the example project

**Comment by StackHelp** [comment]
@mwfire  What to do if radius is changed according to popups means multiple radius for multiple popups?
