### ISSUE TITLE
is it passable show hyper link?

### ISSUE THREAD

**Issue by eyesblue** [Orderella/PopupDialog#245]
Hi
thank your great project.

I have a question, Is it passable show hyper link text as clickable link in the message area.
while user click the link then try to open the web or send mail?

**Comment by mwfire** [comment]
Hey there and sorry for my late reply.

You can achieve this by using a custom view controller. Attributed strings are able to handle links, in some cases even a WKWebView might be a solution.

Hope that hints in the right direction :)
