### ISSUE TITLE
show blur view above keyboard 

### ISSUE THREAD

**Issue by ahmedAlmasri** [Orderella/PopupDialog#246]
- Xcode version 9.4
- PopupDialog version 0.7.0)
- Minimum deployment target 10
- Language Swift
- In case of Swift - Version 4.3

- Dependency manager  CocoaPods
- Version  1.4.0.beta.2

change keyboard from text to numbers   show blur view above keyboard  

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14888785/42724083-a8cbf474-8774-11e8-88e5-895cd7f31d5d.gif)

**Comment by mwfire** [comment]
Hey there. I am not sure if I understand the issue here. Could you please clarify? Thanks!

**Comment by ahmedAlmasri** [comment]
@mwfire  I'm sorry ,  please see this screen 
step reproduce this issue  
1- add tow UITextField  First input type numbers  second input type text 
2- focus on UITextField type number then focus input type test 
The blur layer show above keyboard 

> Note : Test this issue on iphone SE 

<img width="421" alt="screen shot 2018-07-21 at 3 22 48 pm" src="https://user-images.githubusercontent.com/14888785/43035528-2031feb6-8cfa-11e8-9104-4f26f30e752f.png">

**Comment by mwfire** [comment]
Thanks, I will investigate asap.
