### ISSUE TITLE
Issue with Carthage Dependency Manager.

### ISSUE THREAD

**Issue by abdul-rehman** [Orderella/PopupDialog#247]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 9.4.1
- PopupDialog version (e.g. 0.5.0): 0.7.1
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 3

## Dependency management
- Dependency manager (e.g. CocoaPods): Carthage
- Version (e.g. 1.3.1): 0.30.1

## What did you do?
I am an iOS Developer.

## What did you expect to happen?
 App should not crash while creating PopupDialog Instance.

## What happened instead?
App Crashed due to wrong link of Framework.

## Project that demonstrates the issue

**dyld: lazy symbol binding failed: Symbol not found: __T011PopupDialogAACABSo16UIViewControllerC04viewD0_SC22UILayoutConstraintAxisO15buttonAlignmentAA0aB15TransitionStyleO010transitionL0Sb16gestureDismissalyycSg10completiontcfC
  Referenced from: /Users/abdulrehman/Library/Developer/CoreSimulator/Devices/4C0EC2AA-BEFD-4F78-82B9-576655CAECD5/data/Containers/Bundle/Application/23830129-7AC2-4278-8DFA-94B71E5D5EC5/Demo Sandbox.app/Demo Sandbox
  Expected in: /Users/abdulrehman/Library/Developer/CoreSimulator/Devices/4C0EC2AA-BEFD-4F78-82B9-576655CAECD5/data/Containers/Bundle/Application/23830129-7AC2-4278-8DFA-94B71E5D5EC5/Demo Sandbox.app/Frameworks/PopupDialog.framework/PopupDialog

dyld: Symbol not found: 
__T011PopupDialogAACABSo16UIViewControllerC04viewD0_SC22UILayoutConstraintAxisO15buttonAlignmentAA0aB15TransitionStyleO010transitionL0Sb16gestureDismissalyycSg10completiontcfC
  Referenced from: /Users/abdulrehman/Library/Developer/CoreSimulator/Devices/4C0EC2AA-BEFD-4F78-82B9-576655CAECD5/data/Containers/Bundle/Application/23830129-7AC2-4278-8DFA-94B71E5D5EC5/Demo Sandbox.app/Demo Sandbox
  Expected in: /Users/abdulrehman/Library/Developer/CoreSimulator/Devices/4C0EC2AA-BEFD-4F78-82B9-576655CAECD5/data/Containers/Bundle/Application/23830129-7AC2-4278-8DFA-94B71E5D5EC5/Demo Sandbox.app/Frameworks/PopupDialog.framework/PopupDialog**

**Comment by mwfire** [comment]
Hey there, not sure of that specific case, but please note version of PopupDialog is not Swift 3 compatible. Please use 
https://github.com/Orderella/PopupDialog/releases/tag/0.5.4 or lower. Does that work?

**Comment by abdul-rehman** [comment]
Issue Resolved. Actually Carthage and pod were installed at the same time. Removing 'PopupDialog' from Podfile did the trick. Thanks for your swift response.
