### ISSUE TITLE
Feature request: Support long messages

### ISSUE THREAD

**Issue by mskri** [Orderella/PopupDialog#248]
Fantastic library! One thing I'm missing is support for long messages. If I have extra long message it causes the dialog container to extend beyond screen which prevents reading all the text or using the buttons. Limiting the height of the dialog and making the message section scrollable would be great addition.

**Comment by mwfire** [comment]
Hey there, this relates to https://github.com/Orderella/PopupDialog/issues/127
With custom view controllers, this can be achieved. For the default view controller, what should be the scrollable content? Image + title + message, title + message or only the message?

**Comment by mskri** [comment]
Thanks! Custom view controller seem to be the way to go. Scrollable content is just scrollable long message.
