### ISSUE TITLE
Is there a way to put my image in center -  instead of stretching it out - in Image Dialog view?

### ISSUE THREAD

**Issue by manvendrasah** [Orderella/PopupDialog#250]
Using
- Xcode version (e.g. 9.1): 9.1
- PopupDialog version (e.g. 0.5.0): 0.5
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4

I want my image to be centered in the Image dialog view of the PopupDialog. But currently there is no option of changing this. The image is stretched to fill the whole view.

Is there a way i can get my image to be centered with custom size ?

**Comment by mwfire** [comment]
Hey @manvendrasah,

unfortunately, this is currently not possible with the default dialog. You can add the padding to your image, or use your own custom view controller.

Hope that helps :)

**Comment by anonrig** [comment]
How can we add a padding to image ?
