### ISSUE TITLE
Feature request: be able to return custom shadowContainer

### ISSUE THREAD

**Issue by OhadMaor-VIA** [Orderella/PopupDialog#252]
Inside `let pcv = PopupDialogContainerView.appearance()` it would be great if we can also create our custom `shadowContainer` -> currently it is defined as `internal` in `PopupDialogContainerView`.

**Comment by mwfire** [comment]
Hi @OhadMaor-VIA,

I'd rather keep the shadow container internal, as it would clutter the API in my opinion.
I will look into adding additional shadow customization options, if that makes sense :)

**Comment by OhadMaor-VIA** [comment]
Makes total sense. 
Thanks!

**Comment by mwfire** [comment]
This is now ready to test :) In your Podfile, specify
`pod 'PopupDialog', :git => '/github.com/Orderella/PopupDialog/PopupDialog.git', :branch => 'feature/shadowProperties'`to use the feature branch exposing all shadow properties to appearance.

See the example AppDelegate / Readme for how to customize the shadow.

**Comment by mwfire** [comment]
Released with V 0.8.1,  https://github.com/Orderella/PopupDialog/pull/260
