### ISSUE TITLE
How to disable gesture when dialog has shown up.

### ISSUE THREAD

**Issue by sambo-visal** [Orderella/PopupDialog#253]
I really like this framework. But i have one issue which is that when that dialog has shown up i don't want to enable gesture to close that dialog. Do you know how to solve this issue.

Thank in advance.

**Comment by mwfire** [comment]
Hey @SamboVisal,

you can change that in the initializer by setting the following to false.

```swift
tapGestureDismissal: false
panGestureDismissal: false
```

This is the complete list of initializer options, as of the readme

```swift
public convenience init(
    title: String?,
    message: String?,
    image: UIImage? = nil,
    buttonAlignment: UILayoutConstraintAxis = .vertical,
    transitionStyle: PopupDialogTransitionStyle = .bounceUp,
    preferredWidth: CGFloat = 340,
    tapGestureDismissal: Bool = true,
    panGestureDismissal: Bool = true,
    hideStatusBar: Bool = false,
    completion: (() -> Void)? = nil) 
```

Hope that helps :)

**Comment by sambo-visal** [comment]
Thank you so much...
