### ISSUE TITLE
Feature request: completion blocks for tapGestureDismissal & panGestureDismissal

### ISSUE THREAD

**Issue by OhadMaor-VIA** [Orderella/PopupDialog#255]
In order to be able to handle different use-case scenarios it would be great to have a completion blocks for both `tapGestureDismissal` & `panGestureDismissal`.

Thanks.

**Comment by mwfire** [comment]
Hey @OhadMaor-VIA,

makes sense and should be sent back as a parameter in the completion block, instead of two separate  blocks. I will have a look how this will work best with Obj-C.

**Comment by OhadMaor-VIA** [comment]
Exactly, an enum will be great.
Thanks!
