### ISSUE TITLE
The button background color when tapping

### ISSUE THREAD

**Issue by takeshi-1000** [Orderella/PopupDialog#257]
Hi, thank you for the library . 
But i have one problem which is button background color when tapped .Like the below gif, the button is blacked when taping. As possible I wanna the button background color not to change .  
I checked my code and another issues, but I couldn't find solution .  Could you check it ?

Thanks

- Xcode version : 9.4
- PopupDialog version : 0.8.0
- Language (Swift)
- In case of Swift - Version : 4.1.2
- Dependency manager : CocoaPods : 1.5.3 

[![Image from Gyazo](https://i.gyazo.com/0773a746d1d9df1eef35d8bf45d8ea6c.gif)](https://gyazo.com/0773a746d1d9df1eef35d8bf45d8ea6c)

```
import PopupDialog

class TestViewController: UIViewController {
    
    @IBAction func tapBtn(_ sender: Any) {
        let title = "THIS IS THE DIALOG TITLE"
        let message = "This is the message section of the popup dialog default view"
        
        // Create the dialog
        let popup = PopupDialog(title: title, message: message)
        
        // Create buttons
        let buttonOne = CancelButton(title: "CANCEL", height: 50, dismissOnTap: true) {
            print("aaaa")
        }
        // This button will not the dismiss the dialog
        let buttonTwo = DefaultButton(title: "ADMIRE CAR", dismissOnTap: false) {
            print("What a beauty!")
        }
        
        let buttonThree = DefaultButton(title: "BUY CAR", height: 60) {
            print("Ah, maybe next time :)")
        }
        
        // Add buttons to dialog
        // Alternatively, you can use popup.addButton(buttonOne)
        // to add a single button
        popup.addButtons([buttonOne, buttonTwo, buttonThree])
        
        // Present dialog
        self.present(popup, animated: true, completion: nil)
  
    }
```

**Comment by mwfire** [comment]
Hm, I do not see this in the example project. Are you setting UIButton appearance anywhere globally? 
This could have impact on the PopupDialogButtons as well...

**Comment by takeshi-1000** [comment]
Sorry this is my fault , because of UIButton extension I create 🙏
