### ISSUE TITLE
Swift Compile Error from DynamicBlurView

### ISSUE THREAD

**Issue by ikki08** [Orderella/PopupDialog#262]
# Report

## Environment

- Xcode version : 9.4.1
- PopupDialog version : 0.8.1
- Minimum deployment target : 9.0
- Language : Swift
- Version : 4.1

## Dependency management

- Dependency manager : CocoaPods
- Version : 1.5.3

## What did you do?

I run my app

## What did you expect to happen?

The app running on my iPhone

## What happened instead?

The app wasn't running. I got Swift Compiler Error that said the API used by PopupDialog (DynamicBlurView) has an issues. Some of their code is inaccessible due to private protection level.

**Comment by mwfire** [comment]
Hm, that sounds like changes to the protection level introduced with Swift 4. Is it possible you are still using Swift 3 in any of your targets? See https://github.com/KyoheiG3/DynamicBlurView/issues/28
