### ISSUE TITLE
Is there any reason why the viewController never appears

### ISSUE THREAD

**Issue by Smiller193** [Orderella/PopupDialog#265]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): ℹ9
- PopupDialog version (e.g. 0.5.0): ℹ0.8
- Minimum deployment target (e.g. 9.0): ℹ 11.4.1
- Language (Objective-C / Swift): ℹ Swift
- In case of Swift - Version (e.g. 4): ℹ 4

Followed the guide to instantiate a custom view controller in hopes of creating a custom calendar view using the popupdialog. When I run it nothing appears except for the one button that I added. Im super confused.

@objc func presentCalendar(){
    let newCalendar = PresentCalendar()
    let popup = PopupDialog(viewController: newCalendar, buttonAlignment: .horizontal, transitionStyle: .fadeIn, preferredWidth: 90, tapGestureDismissal: true, panGestureDismissal: true, hideStatusBar: true, completion: nil)

    let buttonOne = CancelButton(title: "Close Calendar", height: 60) {
        popup.dismiss()
    }
    
    // Add buttons to dialog
    popup.addButtons([buttonOne])
    
    // Present dialog
    newCalendar.popup = popup
    
    present(popup, animated: true, completion: nil)

}

Code in presentedVC

    import UIKit
    import PopupDialog
    
    
    class PresentCalendar: UIViewController {
        
        /// The PopupDialog this view is contained in
        /// Note: this has to be weak, otherwise we end up
        /// creating a retain cycle!
        public weak var popup: PopupDialog?
        
        lazy var calendarView: UIView = {
            let calendarView = UIView()
            calendarView.backgroundColor = .black
            calendarView.layer.cornerRadius = 8
            calendarView .layer.masksToBounds = false
            calendarView.clearsContextBeforeDrawing = true
            calendarView.autoresizesSubviews = false
            calendarView.setupShadow2()
            return calendarView
        }()
        
        override func viewDidLoad() {
            super.viewDidLoad()
         
    
            // Do any additional setup after loading the view.
        }
        
        @objc func setupViews(){
            view.addSubview(calendarView)
            calendarView.snp.makeConstraints { (make) in
              make.edges.equalTo(view)
            }
        }
    
        override func didReceiveMemoryWarning() {
            super.didReceiveMemoryWarning()
            // Dispose of any resources that can be recreated.
        }
        
    
        /*
        // MARK: - Navigation
    
        // In a storyboard-based application, you will often want to do a little preparation before navigation
        override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
            // Get the new view controller using segue.destinationViewController.
            // Pass the selected object to the new view controller.
        }
        */
    
    }

any idea what's wrong?

**Comment by mwfire** [comment]
Hey there. You have to set an explicit height for your custom view, so the PopupDialog container can wrap it correctly. See https://github.com/Orderella/PopupDialog/issues/125

Hope that helps :)
