### ISSUE TITLE
Feature Request: Present PopupDialog on top of the UIWindow

### ISSUE THREAD

**Issue by OhadMaor-VIA** [Orderella/PopupDialog#266]
There are some cases that a user taps on a button (for example) and has no idea that this button has an async server/mobile request. This is why he can tap on the back button and the current UIVC will get deallocated before the async response.

It means that if the async request finished with error, we won't be able to present the PopupDialog since the error handling was on the previous deallocated UIVC.

In these cases, a static method that can present an alert where-ever we want and when ever we want would solve these cases - for example, presenting the error on top of the UIWindow.

**Comment by mwfire** [comment]
You have full control on where to present the dialog, it does not have to be your view controller.
You can always get the topmost window and present it on such.

Does that make sense?

**Comment by OhadMaor-VIA** [comment]
Of course, I can create an extension and develop it but I thought this feature could be of your interest and perhaps others with demand like mine.

**Comment by mwfire** [comment]
Hi @OhadMaor-VIA and sorry for my late reply.

I totally agree that this is a common use case. However, just as with the UIKit version of the system dialog, the idea is that PopupDialog can be presented on any view/window. As the use cases differ a lot, we would rather keep PopupDialog lightweight and leave the implementation to the developers.

Cheers :)
