### ISSUE TITLE
Can I update dialog's height during presentation?

### ISSUE THREAD

**Issue by kokitang** [Orderella/PopupDialog#267]
## What did you do?

Custom view controller on presented dialog,  which contains multiple childViewController, click "NEXT" / "PREVIOUS" button on each childViewController swap to other childViewController.

## What did you expect to happen?

update the frame (height) of dialog cuz different childViewController having different layout and frame.

**Comment by mwfire** [comment]
Hey there! The container view should adjust to any height changes. If you change the navigation controller height inside PopupDialog, it should adapt. However, I have not done too many experiments there, so please keep me updated if it works for you :)
