### ISSUE TITLE
Swift 4.2 support?

### ISSUE THREAD

**Issue by Dbigshooter** [Orderella/PopupDialog#269]
Any ETA on this?

**Comment by yurihan** [comment]
no.. can't compiled with swift 4.2
so, my podfile is
`
pod 'PopupDialog', git: 'https://github.com/afnanm1999/PopupDialog', branch: 'Swift_4.2'
`

**Comment by mwfire** [comment]
This will be done over the course of this week. The branch is not ready yet and I will communicate once it is ready for testing.

**Comment by blairmacintyre** [comment]
Thanks!  I assume this will change the dependency on DynamicBlurView to use the newer version of that pod, that works with 4.2?

**Comment by balichowdry** [comment]
Hi, 

we are facing the same issue with Xcode10 for ios12, We need to release build can we know when you plan to do it, Thanks in advance for your quick support?

**Comment by zeku2022** [comment]
Thanks for your hard working~

**Comment by mwfire** [comment]
Hey everyone, Swift 4.2 compatibility is ready for testing on the Swift 4.2 branch.
Please have a look and report any findings!

For Cocoapod users, it can be tested by using the following in your Podfile:

```swift
pod 'PopupDialog', :git => '/github.com/Orderella/PopupDialog/PopupDialog.git', :branch => 'Swift4.2'
```

Any Carthage users here?

**Comment by guagnelz** [comment]
> pod 'PopupDialog', :git => '/github.com/Orderella/PopupDialog.git', :branch => 'Swift4.2'

You add a folder more, makes me fail download of branch repo.
But branch works great after download it with XCode10, thank you!

**Comment by mwfire** [comment]
This was released with https://github.com/Orderella/PopupDialog/releases/tag/0.9.0

**Comment by imjn** [comment]
I installed ver 0.9.2 but still got 13 errors ...
Like this

'orientationDidChangeNotification' has been renamed to 'NSNotification.Name.UIDeviceOrientationDidChange'

**Comment by sashakid** [comment]
> I installed ver 0.9.2 but still got 13 errors ...

The same thing
