### ISSUE TITLE
Question: Set width

### ISSUE THREAD

**Issue by szuniverse** [Orderella/PopupDialog#27]
Is it possible to set somehow the popup view's width? 
thanks in advance

**Comment by rgnlax** [comment]
Good question. It will be good to have an ability to set edges or width!

**Comment by mwfire** [comment]
At the moment, this is not possible. The dialog adapts it size to the device size, with a max width of 340. On a iPhone 4s/5, the leading and trailing edges are only 10, whereas they are 20+ on a 6 and bigger, like iPads. This way, the dialog works reliably on all screen sizes, just like the system alert.

Setting the width is not enough, as it might exceed the screen on smaller devices. Setting the edges only would result in weird behavior when changing portrait/landscape or bigger screens.

Even `minWidth` - `maxWidth` alone might not translate well to this problem. I will think about this and keep you updated! Feel free to share your thoughts, just take into account this library has to work accross all Apple devices and orientations :)

Thanks!
