### ISSUE TITLE
Type 'RunLoop' has no member 'Mode'

### ISSUE THREAD

**Issue by puvanarajanm** [Orderella/PopupDialog#272]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10
- PopupDialog version (e.g. 0.5.0): 0.9
- Minimum deployment target (e.g. 9.0): 10
- Language (Objective-C / Swift): swift 4.2
- In case of Swift - Version (e.g. 4): 4.2

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): pod
- Version (e.g. 1.3.1): 

## What did you do?

Type 'RunLoop' has no member 'Mode'  

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  

## What happened instead?

Type 'RunLoop' has no member 'Mode' 

## Project that demonstrates the issue

ℹ In complex cases, it might be useful to link to a sample project. If you don't provide an example, you can delete this section.

**Comment by mwfire** [comment]
Pre Swift 4.2 it used to be `RunLoopMode` instead of `RunLoop.Mode`. So either you are not using the latest version of PopupDialog, or you might be still building with Swift 4.0. Just a guess.

Please try `pod repo update` and `pod update` to make sure you are using the latest PopupDialog library.

Does that help?

**Comment by kambizvb6** [comment]
Doesn't work !!!!!

**Comment by puvanarajanm** [comment]
@kambizvb6 no. Still same error. I check the swift version as well. It's 4.2

**Comment by kambizvb6** [comment]
My xcode is 9.4.1

**Comment by mwfire** [comment]
I cannot replicate this issue. This version was built all green on Travis CI with Xcode 10 and various iOS versions/simulators, see https://travis-ci.org/Orderella/PopupDialog

A few things I am writing from the top of my head:
- In terminal, execute `xcrun swift -version` to show the Swift version you are using and make sure it's 4.2
- Make sure you are using Xcode 10, see https://useyourloaf.com/blog/upgrading-to-swift-4.2/
- RunLoop.Mode is part of an external dependency, called DynamicBlurView. Can you confirm you are also using the latest version of this library? https://github.com/KyoheiG3/DynamicBlurView
See same issue https://github.com/KyoheiG3/DynamicBlurView/issues/39
- Does the example project work for you?

Other than that, please provide an example project showcasing this issue.

**Comment by Kirow** [comment]
I got same problem with **Xcode 9 swift 4.1**. updated to **Xcode 10** - broke everything else, but **PopupDialog** works fine :D

Should check README first...
> This version is Swift 4.2 compatible. For the Swift 3 version, please use V0.5.4.

**Comment by mwfire** [comment]
You can use the previous version 0.8.1 with swift 4.1. There have been no changes other than swift 4.2 compatibility in 0.9, so you are not missing out on features. ;)

**Comment by kaiserdem** [comment]
Hello,  same error with Xcode 10.1 swift 4.2.
