### ISSUE TITLE
Not building at version Swift4

### ISSUE THREAD

**Issue by jobinsjohn** [Orderella/PopupDialog#274]
- Xcode version - 10.0
- PopupDialog version : 0.9.0
- Minimum deployment target : 11.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): Swift4
- Dependency manager : Cocoapods
- Version : 1.5.3

 The project fails after updating the pod to version 0.9.0.

**Comment by mwfire** [comment]
Hey there! The current version of PopupDialog is all green on Travis CI.
However, V 0.9 only works for Swift 4.2 as of the latest syntax changes. Any Swift version lower than 4.2 is supported with version 0.8 of PopupDialog.

If you are still having problems:
- Please refer to https://github.com/Orderella/PopupDialog/issues/272
I summed up some migration hints.
- Please provide the exact error message you are seeing and provide an example project if the above does not help

Cheers,
Martin

**Comment by leftychang** [comment]
Hi, I've got this error building PopupDialog by Carthage using the command `carthage update --platform iOS`.

*** Skipped building PopupDialog due to the error:
Dependency "PopupDialog" has no shared framework schemes for any of the platforms: iOS

Any idea? Thank you.

**Comment by aabanaag** [comment]
Got the same issue.

![image](https://user-images.githubusercontent.com/2245822/46522659-f9c6ef00-c8b5-11e8-8e26-f8b4261c4c54.png)

**Comment by mwfire** [comment]
Hi @leftychang, @aabanaag,

as I am not a Carthage user and on a tight schedule: could you do me a favor and look into this?
Afaik it is about sharing the PopupDialog scheme which can be done via Xcode. Apparently this was lost during one of the latest pull requests. New PRs welcome!

Thanks a lot! Please ping me if you have any questions.

**Comment by aabanaag** [comment]
@mwfire I created a PR #279 let me know if there is something wrong with that I did (this would be my first time contributing in github)

**Comment by mwfire** [comment]
Dear all,

if you are a Carthage user please check out this issue https://github.com/Orderella/PopupDialog/issues/276

Thanks a lot!

**Comment by mwfire** [comment]
For Carthage related issues please check out https://github.com/Orderella/PopupDialog/releases/tag/0.9.1

**Comment by xhidnoda** [comment]
Hi, i got several errors (16) after update to xcode 10 and swift 4.2.   But when i check this library, she use swift 4.0. 
I don't know why, but after change the library swift version to 4.2 is solved 14 issues from 16.  👍
