### ISSUE TITLE
[Carthage] Dependency "PopupDialog" has no shared framework schemes

### ISSUE THREAD

**Issue by dongxiexidu** [Orderella/PopupDialog#276]
- Xcode version 10.0
- PopupDialog version 0.9.0
- Minimum deployment target (9.0):
- Language  Swift: 
- In case of Swift - Version 4.2
- Dependency manager carthage
- Version 0.31.0

Skipped building PopupDialog due to the error:
Dependency "PopupDialog" has no shared framework schemes

**Comment by mwfire** [comment]
Hi @dongxiexidu,

as I am not using Carthage, could you do me a favor and test with the following branch:

```bash
git "https://github.com/Orderella/PopupDialog.git" "bugfix/Carthage"
```

Thanks a lot!

**Comment by dongxiexidu** [comment]
this branch  success ,thanks

**Comment by mwfire** [comment]
Released with https://github.com/Orderella/PopupDialog/releases/tag/0.9.1
