### ISSUE TITLE
Objective C No visible @interface for 'PopupDialog' declares the selector 'initWithTitle

### ISSUE THREAD

**Issue by michael-mansour** [Orderella/PopupDialog#277]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10.0
- PopupDialog version (e.g. 0.5.0): 0.9
- Minimum deployment target (e.g. 9.0): ℹ
- Language (Objective-C / Swift): Objective-C
- In case of Swift - Version (e.g. 4): N/A

## What did you do?

I try to implement PopupDialog in my objective c project following the read me exemple
`PopupDialog *popup = [[PopupDialog alloc] initWithTitle:NSLocalizedString(@"X", nil)
                                                                 message:NSLocalizedString(@"Y", nil)`

## What happened instead?

I get the following error 

> No visible @interface for 'PopupDialog' declares the selector 'initWithTitle:message:image:buttonAlignment:transitionStyle:gestureDismissal:completion:'

Thanks a lot

**Comment by mwfire** [comment]
Hi @skynext,

as this is originally written in Swift, you have to specify the full initializer with Objective-C. Does the following work for you?

```Objective-C
PopupDialog *popup = [[PopupDialog alloc] initWithTitle: @"Title"
                                                message: @"This is a message"
                                                  image: nil
                                        buttonAlignment: UILayoutConstraintAxisVertical
                                        transitionStyle: PopupDialogTransitionStyleBounceUp
                                         preferredWidth: 380
                                    tapGestureDismissal: NO
                                    panGestureDismissal: NO
                                          hideStatusBar: NO
                                             completion: nil];
```

Thanks!
