### ISSUE TITLE
PopupDialog does not work with UIViewController that built from storyboard

### ISSUE THREAD

**Issue by haithngnbak** [Orderella/PopupDialog#28]
```
    // Create a custom view controller
    let editorVC = Storyboards.main.instantiateViewControllerWithIdentifier("TaskEditorViewController")
        as! TaskEditorViewController

    // Create the dialog
    let popup = PopupDialog(viewController: editorVC, transitionStyle: .BounceDown, buttonAlignment: .Horizontal, gestureDismissal: true)

    // Create first button
    let buttonOne = CancelButton(title: "CANCEL") {

    }

    // Create second button
    let buttonTwo = DefaultButton(title: "RATE") {

    }

    // Add buttons to dialog
    popup.addButtons([buttonOne, buttonTwo])

    // Present dialog
    navigationController.presentViewController(popup, animated: true, completion: nil)
```

here is the result:
![simulator screen shot aug 29 2016 7 09 02 pm](https://cloud.githubusercontent.com/assets/1132303/18050990/1f1d0330-6e1c-11e6-8ef3-fa87ae2e4111.png)

**Comment by mwfire** [comment]
Hey @hainguyen86!
When adding custom view controllers, you have to make sure all layout constraints are being taken care of. Have a look at the example folder, the rating view controller is instantiated with its corresponding view from Storyboard. Moreover, issue #12 was solved by adding missing constraints.

Hope that helps :)

**Comment by haithngnbak** [comment]
@mwfire ,
Thanks for your quickly support,
I tried copy your view ("RatingView") to my controller (separated to xib file), it worked.
I will fill the missing constraints in the storyboard.

**Comment by mwfire** [comment]
@hainguyen86 Perfect, glad I could help :)

**Comment by ghost** [comment]
I am facing the similar issues. In my custom controller which I am loading from storyboard, there is noting but a label which is properly constrained. No autolayout issues on console yet I am not able to see any of it except added buttons.

**Comment by var1ableX** [comment]
I had the same problem. Solved by: **explicitly setting height constraint of the SubView.**
View
+- **SubView** <- Set height constraint

Please bear in mind that even adding an empty ViewController and setting the identical constraints as the sample doesn't work in Xcode 10. Would be interesting to see whether you can get this work with an empty ViewController and minimal constraints ...

**Comment by ingouackaz** [comment]
Hello @var1ableX  could you please share an example of your solution?
