### ISSUE TITLE
CAMediaTimingFillMode' (aka 'NSString') has no member 'forwards'

### ISSUE THREAD

**Issue by xhidnoda** [Orderella/PopupDialog#283]
Hi, don't why show me this error:
**CAMediaTimingFillMode' (aka 'NSString') has no member 'forwards'**

**Details:**

- **Where?:**

 UIView+Animations.swift, line 51 and 68 (line 68 error: Type 'CAMediaTimingFunctionName' (aka 'NSString') has no member 'linear'.

- I use swift 4.2 and xcode 10. The library version is: 0.9.1

Can help me pls?

**Comment by xhidnoda** [comment]
OK, i solved after update all again...

**Comment by animaonline** [comment]
What update? How did you solve it?

**Comment by YeagGarage** [comment]
> What update? How did you solve it?

kCAFillModeForwards
