### ISSUE TITLE
Header 'PopupDialog-Swift.h' not found

### ISSUE THREAD

**Issue by renestimu** [Orderella/PopupDialog#284]
i have problem  clean and build but error version 0.9.1 

<img width="1405" alt="ekran resmi 2018-10-11 23 16 23" src="https://user-images.githubusercontent.com/5146055/46831333-d1eef400-cdab-11e8-9be8-a172cfbd02a3.png">

**Comment by ismailtosun** [comment]
same problem

**Comment by mwfire** [comment]
Hey there, please file a new issue while filling in the issue template, I cannot reproduce this so far.
