### ISSUE TITLE
How to pass data back from PopupDialog

### ISSUE THREAD

**Issue by herotheone** [Orderella/PopupDialog#286]
I am initializing my secondViewController like this. See below.

```
let StoryBoard = UIStoryboard.init(name: "Main", bundle: nil)
                
                let customVC = StoryBoard.instantiateViewController(withIdentifier: "popUpController") as! popUpController
                customVC.modalPresentationStyle = UIModalPresentationStyle.custom
                
                let popup = PopupDialog(viewController: customVC)
               
                self.present(popup, animated: true, completion: nil)
```
I want to call a function on mainVC from this dialog. That means i need to pass data back from this dialog. I can't use protocols and delegates unless i called the "performSegue" function which covers full size.

Do you have any idea how to pass data back to mainVC and run a function ?

**Comment by herotheone** [comment]
https://github.com/herotheone/myAdMobProject

This is the repo as an example project.

https://imgur.com/a/V16hFo6

https://imgur.com/a/vBmUZOF

**Comment by mwfire** [comment]
Hey @herotheone,

have a look at https://github.com/mwfire/PopupDialogCustomExample
You should be able achieve what you are aiming for by passing a weak reference of PopupDialog to your custom view controller.

Does that help?
