### ISSUE TITLE
PanGestureDismissal calls viewWillAppear

### ISSUE THREAD

**Issue by nflows** [Orderella/PopupDialog#288]
Hi Orderella
I'm using this awesome library for a while now and i run into some struggles.

If you init a PopupDialog with a custom viewcontroller and you don't set the _panGestureDismissal_ property to false, then the presented PopupDialog calls the **viewWillAppear** method on each swipe/pan gesture. So if you call that property "panGestureDismissal" it should dismiss that one not only call viewWillAppear or do i misunterstand something here?
 
It is getting very strange and confusing if you are implementing a TableView. The rows / cells editing methods are not called properly - because the viewWillAppear blocks the process.

**Comment by mwfire** [comment]
Hey there! Thanks for the heads up, I will check as soon as possible. Thx!

**Comment by mwfire** [comment]
Sry, reopening this as it is still valid.
