### ISSUE TITLE
Add input to the popup?

### ISSUE THREAD

**Issue by Dbigshooter** [Orderella/PopupDialog#29]
Hi there,

I want to add an input field to the popup, when prompting the user for input, is this possible?

Cheers

**Comment by mwfire** [comment]
Hi @Dbigshooter! Yes, definitely, but it requires a custom view controller. Have a look at the example that comes with this library, there is one with star rating and input field that should fit your requirements more or less.

Hope that helps :)

**Comment by Dbigshooter** [comment]
Thanks, @mwfire! I didn't even notice the input field at first. Is it possible to do without making a .xib?

**Comment by mwfire** [comment]
@Dbigshooter Yes of course, that was just an example. You can write your view controller's views in code as well, that's totally independent from PopupDialog. :)

**Comment by Dbigshooter** [comment]
@mwfire Thanks! I'm not very experienced in using .xibs, I've always been taught it's kinda deprecated? Is the choice only between code or .xib? It is not possible to use .storyboard?

**Comment by mwfire** [comment]
@Dbigshooter Yep, you can instantiate view controllers from storyboards, with XIBs or entirely programmatically. Instantiate them in your code and pass them to the initializer of PopupDialog.
