### ISSUE TITLE
Table not showing

### ISSUE THREAD

**Issue by aabanaag** [Orderella/PopupDialog#290]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): ℹ 10.1
- PopupDialog version (e.g. 0.5.0): ℹ 0.9.1
- Minimum deployment target (e.g. 9.0): ℹ 9.0
- Language (Objective-C / Swift): ℹ Swift
- In case of Swift - Version (e.g. 4): ℹ Swift 4.2

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): ℹ Carthage
- Version (e.g. 1.3.1): ℹ 

## What did you do?
Created a ViewController to show within the PopupDialog. I did referenced this (https://github.com/mwfire/PopupDialogCustomExample) also I'm using RxDatasources to handle the data+table part.

## What did you expect to happen?
It will show the view controller as a popup with the dynamic data.

## What happened instead?
It showed the ViewController but not the table nor the data.

## Project that demonstrates the issue

I'm using RxSwift to bind the UI and the data which list the printers within the network. I can see the rxswift side working without an issue. The UI is not showing the whole table.
![image](https://user-images.githubusercontent.com/2245822/47871092-2125c300-de46-11e8-944c-29959864149e.png)

**Comment by RafalManka** [comment]
+1

**Comment by RafalManka** [comment]
@aabanaag UICollectionView seems to work. Maybe try giving it a shot?

**Comment by mwfire** [comment]
It should work once you give your table view a fixed height. There is a pinned issue with a link to a table view example here.

**Comment by RafalManka** [comment]
@mwfire I tried giving UITableView a fixed height and it didn't help. I found the pinned example, I'll give it a shot: https://github.com/Orderella/PopupDialog/issues/87
