### ISSUE TITLE
How to catch gesture dismissal without deiniting the popup?

### ISSUE THREAD

**Issue by ghost** [Orderella/PopupDialog#292]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10.0
- PopupDialog version (e.g. 0.5.0): 0.9.1
- Minimum deployment target (e.g. 9.0): 12.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4.2

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): Carthage
- Version (e.g. 1.3.1): 0.31.2

## What did you do?

I am showing a popup dialog box using the following code
```swift
popupDialog = PopupDialog(viewController: newController) {
    print("dialog was dismissed")
}
                    
currentViewController.present(popupDialog!, animated: true, completion: nil)
```

The dialog box is shown as expected.

If I click on the background, the dialog box disappears as expected.

## What did you expect to happen?

After I click on the background, the dialog box disappears as expected. Since I have provided the `completion` parameter, I expected that the completion handler will be executed and `dialog was dimissed` will be printed to console

## What happened instead?

The `completion` handler is not executed.

## Additional Information

According to this [PR](https://github.com/Orderella/PopupDialog/pull/244), completion handler is executed when popup is deinited.

The readme says `This completion handler is called when the dialog was dismissed. This is especially useful for catching a gesture dismissal`

Is there any way to catch a gesture dismissal without deiniting the popup

**Comment by mwfire** [comment]
Hey there! The completion is indeed called whenever the dialog is dismissed. As the handler is called on deinit, my guess is that deinit is not called. This can be caused by a retain cycle. Do you have a small example project I can check out?

Thanks!

**Comment by ghost** [comment]
Reference to the popup dialog was stored in a variable due to which the popup dialog did not get deinited and handler did not get called.

After making the reference weak, the handler gets called.
