### ISSUE TITLE
Popup appears with delay when presenting on uicollectionview

### ISSUE THREAD

**Issue by miki9938** [Orderella/PopupDialog#295]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10.1
- PopupDialog version (e.g. 0.5.0): 0.9.2
- Minimum deployment target (e.g. 9.0): 11.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4.2

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.3.1): 1.5.3

## What did you do?

When I display a popup over a view controller with UICollectionView inside it appears with a delay. It only occurs when the collection have 10 or more elements inside - cells have simple label inside. The popup is launched by clicking a button (outside of the collection view). This issue affects only the PopupDialog view, different views appears immediately  (I use `self.present(popup, animated: true, completion: nil)`)

## What did you expect to happen?

Popup to appear immediately.  

## What happened instead?

Popup appears with a delay.

## Project that demonstrates the issue

A simple collection view and popup launched over it.

**Comment by Maryom** [comment]
Hey,
I have the same issue, any help?
