### ISSUE TITLE
Use Image Cache from kingfisher or link

### ISSUE THREAD

**Issue by ghost** [Orderella/PopupDialog#296]
This is more of a good enhancement for future release,

 We can only pass a UIImage to PopupDialog, but it will be great if we can pass the link of the image and use the cache function like kingfisher. 
It takes a little time to open the popup when the internet is slow.

Thank you for keeping up this  repo its great

**Comment by valterh4ck3r** [comment]
Waiting...

**Comment by mwfire** [comment]
Hey there. For async loading, I would suggest to create a custom view controller. There are a lot of popular image loading/caching libraries out there, so with a custom VC you can use the library of your choice. We try to keep PopupDialog as lightweight as possible, which also means not introducing additional dependencies if it can be avoided. Hope that makes sense :)
