### ISSUE TITLE
Swift 4 Support/Compatibilty

### ISSUE THREAD

**Issue by AlexGZC** [Orderella/PopupDialog#298]
Hi, I would like to be supported, I am still working with Swift 4, however, when I install it throught Cocoapod i get a lot of issues:

- Xcode version (e.g. 10.1)
- PopupDialog version (e.g. 0.8.1)
- Minimum deployment target (e.g. 12.1)
- Language (Swift): 
- In case of Swift - 4

Please help me, i love this pod.
I am such in rush in order to use it

**Comment by rob8861** [comment]
@AlexGZC 
please do the following to get swift 4.0 support

open up your Podfile and replace the line for popupdialog with this one

pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :tag => '0.8.1'

then recompile and it should work.

**Comment by mwfire** [comment]
Hey there!

As @rob8861 suggests. Please check out the release section to see when new versions are introduced, so you can pick the version before. To ensure backward compatibility, I usually do version increments when supporting a new Swift version. You can specify a specific version in your Podfile like

```
pod 'PopupDialog', '~> 0.8'
```

However, you should be able to use the latest PopupDialog and mix versions in your project. Afaik CocoaPods assumes the same for all libraries by default. See https://github.com/CocoaPods/CocoaPods/issues/8118 for a post-install action that allows for different Swift versions per library.

Hope that helps.

**Comment by carlosvalenzuela0193** [comment]
i have problems with swift 4.2
it throws me several errors

**Comment by ardee19** [comment]
> i have problems with swift 4.2
> it throws me several errors

Are your errors something with the NSNotification?

Ex. 'orientationDidChangeNotification' has been renamed to 'NSNotification.Name.UIDeviceOrientationDidChange'

**Comment by carlosvalenzuela0193** [comment]
> > i have problems with swift 4.2
> > it throws me several errors
> 
> Are your errors something with the NSNotification?
> 
> Ex. 'orientationDidChangeNotification' has been renamed to 'NSNotification.Name.UIDeviceOrientationDidChange'

I don't remember I decide not to use this framework because it throws to many errors

**Comment by mwfire** [comment]
Hey there,

this library is Swift 4.2 compatible. Please make sure your parent project was fully migrated to Swift 4.2 and run pod install again. More information can be found here: https://swift.org/migration-guide-swift4.2/

Moreover, you can check out the example project, which is Swift 4.2 as well.
@carlosvalenzuela0193 Can you confirm the example project works for you?

Thx, all!

**Comment by arealdeadone** [comment]
> Hey there,
> 
> this library is Swift 4.2 compatible. Please make sure your parent project was fully migrated to Swift 4.2 and run pod install again. More information can be found here: https://swift.org/migration-guide-swift4.2/
> 
> Moreover, you can check out the example project, which is Swift 4.2 as well.
> @carlosvalenzuela0193 Can you confirm the example project works for you?
> 
> Thx, all!

The project worked after renaming and refactoring several lines of code according to the compiler. My parent project was fully migrated to Swift 4.2.

**Comment by mwfire** [comment]
Hey there! Please check out version 1.0.0. Looking forward to your feedback.

**Comment by mwfire** [comment]
Closing this as of related feedback after release of 1.0.0
