### ISSUE TITLE
bug - PopupDialog resets styling of UITextField

### ISSUE THREAD

**Issue by rob8861** [Orderella/PopupDialog#299]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10.1
- PopupDialog version (e.g. 0.5.0): 0.8.1
- Minimum deployment target (e.g. 9.0): 11.4
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 4.0

## Dependency management

- Dependency manager (e.g. CocoaPods): CocaPods
- Version (e.g. 1.3.1): latest 

## What did you do?

Created a UITextField
changed the textfield border to red and thickness to 1
create a basic PopupDialog and invoked it
after the popup dialog is dismissed, the border color goes back to white. 

## What did you expect to happen?

border color should remain Red!

## What happened instead?

border color changed to white

## Project that demonstrates the issue
it is pretty simple to repro. 
just throw in a UITextField, change it's border color to red and call the popup dialog.

**Comment by mwfire** [comment]
Hey there!

I am not able to reproduce this, it works for me in the [RatingViewController](https://github.com/Orderella/PopupDialog/blob/master/Example/PopupDialog/RatingViewController.swift) of the example project.

Make sure to also set borderWidth explicitly, like

```swift
commentTextField.layer.borderColor = UIColor.red.cgColor
commentTextField.layer.borderWidth = 1
```

If you are still experiencing problems, please create a tiny example project showcasing the issue.
Thanks!
