### ISSUE TITLE
Swift 2.3 Compatibility?

### ISSUE THREAD

**Issue by sansari** [Orderella/PopupDialog#30]
Hi! Just wondering, is there a branch or commit where Swift 2.3 support was added? I'm trying to build my app for iOS10 using XCode 8 Beta 6, and so I've got pretty much everything on Swift 2.3 now except for this one. I noticed a Swift3 branch, but didn't see one for Swift 2.3.

These are the errors I'm seeing right now (same errors when I try against the master branch):

```
- PresentationController.swift:35:14: Initializer does not override a designated initializer from its superclass

- PresentationManager.swift:40:10: Parameter of 'presentationControllerForPresentedViewController(_:presentingViewController:sourceViewController:)' has different optionality than required by protocol 'UIViewControllerTransitioningDelegate'

- TransitionAnimator.swift:54:62: Cannot force unwrap value of non-optional type 'UIView'
```

**Comment by mwfire** [comment]
@sansari Ah, to be honest, I have skipped Swift 2.3. compatibility. However, let me see how much work that is going to be. I'd expect migration to do all the work. I'll keep you updated.

**Comment by sansari** [comment]
Yeah, I figured -- I considered just going for Swift3, but many of the libraries I'm using don't have Swift3 compatibility yet so it's a bit of a chicken-egg situation.

I took a stab at forking it and the changes to get it to build were pretty minor: https://github.com/sansari/PopupDialog/commit/3e81410d56eb62fac94315a334c6f7f97e25f3dc. Mostly given the change that the presentingViewController parameter in the init of a UIPresentationController class is now an optional. I suppose one should add handling in that init for when it isn't present, but I was just working on getting it building first.

Just doing some basic sanity tests on my app showed that the popup is still working as expected. Have to run for a bit but can do some more checking later on it.

**Comment by sansari** [comment]
I will also say, I was a bit confused by the changes as they seemed to be more around a change in the optionality of a parameter in the SDK, not a specific "Swift syntax" change. Maybe just am lacking some understanding in terms of the changes from XCode 7 to XCode 8 Beta (but, for example, it was compiling fine with the same code on iOS 9 and iOS 10, so that change wasn't an iOS SDK change...)

**Comment by mwfire** [comment]
Yeah, I did not dive into Swift 2.3 really. As far as I understood it, it was not about syntax changes but better Objective-C interoperability. Would you mind doing a pull request against the Swift 2.3 branch I just added? That would be great :) Thanks!

**Comment by sansari** [comment]
Done! This may be a dumb question (I'm new to contributing to pods), but how would I run the tests for the project? I couldn't find an actual workspace/project file to open (other than the Example one). I wanted to run those before submitting a PR, but couldn't figure out how.

**Comment by mwfire** [comment]
Thanks a bunch! I'll have a look at the PR asap. In order to run the tests, open the example project and either "long press" the Build&Run/Play button and change it to Test, or, the preferred way: the ⌘ + U shortcut.

Travis will run the tests automatically anyhow. Not sure if it's configured correctly for the beta, though.

**Comment by sansari** [comment]
Cool -- I just opened the Example project in XCode8 Beta 6, and in order to run it, it had to do the migration to both the PopupDialog and the Pods project to enable Swift 2.3. Once I did that, the tests appear to run successfully: https://cloudup.com/cZZW5JxXeEP.

Would it be useful to check in the changes to the projects, or is that not necessary given it's a temporary branch? Let me know.

**Comment by mwfire** [comment]
@sansari Thanks for the PR! I have merged it and added my changes. Travis does not pass at the moment, but given that this is more or less an intermediate version, it should do.

Thanks again!
Martin

**Comment by sansari** [comment]
You're welcome! Happy to help. Thanks for building this great tool. We are using it to prompt users for feedback in our next release :)

**Comment by haithngnbak** [comment]
Now, it's time to move to swift 3 :D
