### ISSUE TITLE
Latest version does not compile with Swift 4.2 or 5

### ISSUE THREAD

**Issue by sofierPoS** [Orderella/PopupDialog#304]
As soon as I upgrade to latest 
Installing PopupDialog 0.9.2 (was 0.8.1)

I get tons of compile errors with both Swift 4.2 and 5

Pls fix...

**Comment by mwfire** [comment]
Please give it a try with version 1.0.0 and the latest Cocoapods. PopupDialog has been Swift 4.2 compatible for almost half a year now (check out the example project), but projects with mixed Swift versions seem to cause trouble sometimes.

I did not check with Swift 5 so far, so please report your findings. Thx!

**Comment by sofierPoS** [comment]
works now - thanks!
