### ISSUE TITLE
UIView instead of UIButton

### ISSUE THREAD

**Issue by alexisbar** [Orderella/PopupDialog#306]
Hello !

I was wondering if there was an easy way to add an UIView to the stackView instead of a subclass of PopupDialogButton. 
I need some padding and shadow around my UIButton. Something like this :

![Capture d’écran 2019-04-03 à 14 18 12](https://user-images.githubusercontent.com/8861304/55478198-5c0d6c00-561b-11e9-897a-ea9ce4761a78.png)

Thanks for this amazing lib. It's saving me a lot of time ✌️

**Comment by alexisbar** [comment]
I did It by adding my UIStackView into my custom popup controller. I do not add any buttons. 
Best I found.

**Comment by mwfire** [comment]
Hey there! Yeah, that's currently how to achieve this. You have full access to PopupDialog from your custom view controller if you hold a (weak) reference to the PopupDialog in your custom view controller. Hope that works for you :)
