### ISSUE TITLE
Portrait only 

### ISSUE THREAD

**Issue by jonas-sleepcycle** [Orderella/PopupDialog#311]
Is it possible to enable portrait only mode when showing a dialog?

I do not want to use a global extension to override supportedInterfaceOrientations as it's a bad practice to do this and I may need landscape support in the future. Could this be a parameter on PopupDialog?

**Comment by mwfire** [comment]
Hi @jonas-sleepcycle, sorry for my late reply, I will check on this asap.

**Comment by pontusm** [comment]
I made a simple fix in my fork:
https://github.com/pontusm/PopupDialog/commit/2a3cf010a05b9e2e483f9b26f36be29de448d4eb

**Comment by mwfire** [comment]
Thanks, and sorry again for my late reply. I will check out your fork, @pontusm

**Comment by pontusm** [comment]
Thanks, I also added support for action sheet style similar to UIAlertController and a few other improvements. Maybe we can merge this into the main fork somehow. 🤔
