### ISSUE TITLE
using the popupdialog with an activityindicator

### ISSUE THREAD

**Issue by jrumol** [Orderella/PopupDialog#313]
I have been thinking about using popupdialog to load an activity indicator when loading a viewcontroller, until the data is loaded into a tableview. However, I don't know how to dismiss the dialog when the data load has finished.

**Comment by mwfire** [comment]
Hey there!

This should be possible by keeping a reference to the dialog, e.g. as a property of the view controller:

```swift
let acitivityDialog: PopupDialog = {
    let dialog = PopupDialog(...)
   // ...
    return dialog
}()
```

When loading starts, you present the dialog like `present(activityDialog, animated: true)`, while you can dismiss it via `activityDialog.dismiss()`.

Does that work for you?

**Comment by Kirow** [comment]
@mwfire this will not work correctly on second `present`. Related to #43
