### ISSUE TITLE
define the size of an image in a Popup

### ISSUE THREAD

**Issue by FabriceBali** [Orderella/PopupDialog#316]
Hello, I added an image at the top of the Popup. But I can't give it a precise size. Can you help me?
Thank you. Thank you..

- Xcode version (10.2.1): ℹ
- PopupDialog version (e.g. 0.5.0): ℹ

**Comment by mwfire** [comment]
Hey there! The default dialog will always try to pin left - top - right while keeping the aspect ratio.
If you have other requirements, you might want to give it a shot using a custom view controller where you have full control.

Hope that helps :)

**Comment by purepure** [comment]
Your lib is great!
I am with @FabriceBali, it is more awesome if we could setup the size of image or it's margin
