### ISSUE TITLE
CocoaPods could not find compatible versions for pod "PopupDialog":   In Podfile:     PopupDialog (~> 1.1.0)

### ISSUE THREAD

**Issue by allen8517** [Orderella/PopupDialog#317]
!] CocoaPods could not find compatible versions for pod "PopupDialog":
  In Podfile:
    PopupDialog (~> 1.1.0)

Specs satisfying the `PopupDialog (~> 1.1.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by allen8517** [comment]
platform :ios, '9.0'

**Comment by mwfire** [comment]
Hey there, we needed to drop iOS 9 support with version 1.0.0. You can specify any previous version if you need to support iOS 9.

Hope that helps :)
