### ISSUE TITLE
Nothing show if custom view have a scroll view

### ISSUE THREAD

**Issue by VitoLeeLee** [Orderella/PopupDialog#32]
it will show if I set a fix height for the scroll view.

**Comment by mwfire** [comment]
Have you tried placing the UIScrollView inside a UIView? If you set the final dimensions for this parent UIView via Autolayout and align the UIScrollview to those, it should work as expected.

There is a neat tutorial on Scrollviews and Autolayout by Natasha the Robot here: https://www.natashatherobot.com/ios-autolayout-scrollview/

**Comment by VitoLeeLee** [comment]
![screen shot 2016-09-09 at 5 05 03 pm](https://cloud.githubusercontent.com/assets/22041714/18381636/bec38c1a-76af-11e6-8c25-a1f8d3ffd526.png)
That's my setting. If I set a fix height for scroll view and it will show. If not just nothing showing.

**Comment by mwfire** [comment]
Hard to tell, though this issue only arises with missing/wrong constraints. Best practice would be to have only a single contentView as child of scrollview. Your label was added to the scrollview directly, though. Have a look at the link I have posted above, that might be helpful :)

**Comment by VitoLeeLee** [comment]
[testtest.zip](https://github.com/Orderella/PopupDialog/files/466428/testtest.zip)
Here is a demo project. Please point out if any constraint is setting wrong.
Thanks for the answer and a great library.

**Comment by mwfire** [comment]
@VitoLeeLee Sorry for my late reply. I have a lot of things to do these days, but I will look into it asap.

**Comment by VitoLeeLee** [comment]
@mwfire Any feedback? :)

**Comment by gallynero** [comment]
[testtest.zip](https://github.com/Orderella/PopupDialog/files/499998/testtest.zip)

@VitoLeeLee i fix your project, i add a hidden view with absolutes values y have the same problem with a tableview and i found this solution.

Regards.

**Comment by VitoLeeLee** [comment]
@gallynero Thanks for the reply. 
In my opinion, I think thats not a good solution to adding fixed height value to the hidden view.

**Comment by mwfire** [comment]
@VitoLeeLee Thanks! I just had a quick look and I can see conflicting constraints in the console. I made a demo project with a scroll view, I'll attach it as soon as it's finished.

**Comment by VitoLeeLee** [comment]
@mwfire Its that the demo project ready?
