### ISSUE TITLE
Message becomes too long and the view doesn't allow scrolling to keep the popup within a certain size

### ISSUE THREAD

**Issue by tcheek-bw** [Orderella/PopupDialog#325]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10.3
- PopupDialog version (e.g. 0.5.0): 1.1
- Minimum deployment target (e.g. 9.0): 10.3
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 5

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.3.1): 1.1

## What did you do?

Created a popup with a long message text.

## What did you expect to happen?

The view would limit itself to a margin of the screen height and turn the message subview/container view into a scroll view so that the message could scroll and not push the popup to be too long.

## What happened instead?

Popup ended up being too long for the screen size. I'm trying to create an info popup with important information and I can't really remove any of it to make it shorter :/

## Project that demonstrates the issue

github.com/Hoid/FCS_Mock_Season_Creator

**Comment by Hoid** [comment]
Bump, still an issue

**Comment by adeiry** [comment]
@Hoid I have the same issue!! did you find a solution?

**Comment by tcheek-bw** [comment]
No, unfortunately :(

**Comment by mwfire** [comment]
Hey there! I will be looking into this. This was not yet implemented as there was no clear requirements ;) This can be achieved right now by using a custom view controller, which gives you more fine grained control.

However, as far as it concerns the default dialog:  I would suggest making only the message scrollable. It will not solve all of the issues but multiline messages should be handled like this. This would also require defining a max height. I guess it would make sense to do this internally by calculating the screen/dialog size ratio. What do you think?
