### ISSUE TITLE
How to apply a border

### ISSUE THREAD

**Issue by otymartin** [Orderella/PopupDialog#33]
@mwfire 
Can I or How can I apply say a 2pt border around the whole dialogue box?

Its to conform to my UI style

**Comment by mwfire** [comment]
Hey there! Unfortunately, that's not officially supported. There is a more or less hacky workaround for this:

```
// Swift 3 - change syntax accordingly for Swift 2.X
let popup = PopupDialog(...) {}

let view = popup.view.subviews[0].subviews[0]
view.layer.borderColor = UIColor.red.cgColor
view.layer.borderWidth = 2
```

However, this could potentially break with future versions.

Cheers
Martin

**Comment by otymartin** [comment]
@mwfire 
Thanks, I tried it and it looked absolutley horrible ahaha. I went with a shadow instead, looks clean.
Thanks so much for the library 💯 

UPDATE:
On second thought, I now think it looks dope! 😂

**Comment by mwfire** [comment]
😂 Perfect!
