### ISSUE TITLE
Required swipe amount to dismiss is too much

### ISSUE THREAD

**Issue by ergunkocak** [Orderella/PopupDialog#331]
When popup is half size of screen i need to swipe all the way top to be able to dismiss. Also a fast minor swap does not dismiss the popup.

- Xcode version : 10.3.2
- PopupDialog version : 0.9.2
- Minimum deployment target : 11.4
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): Swift 5

- Dependency manager : Cocoapods 
- Version : 1.8.1

**Comment by mwfire** [comment]
Hi there! True, there is no special handling of the swipe gesture per dialog/screen size. I will look into it :)

**Comment by ergunkocak** [comment]
Hi @mwfire ,
Is there any update or suggestions for the moment?
Best

**Comment by ergunkocak** [comment]
Hi @mwfire ,
Is there any update or suggestions for the moment?
Best

**Comment by ergunkocak** [comment]
For the ones who need it. You can use this: 

https://github.com/ergunkocak/PopupDialog/tree/swipeVelocity
