### ISSUE TITLE
Attributed text feature addition

### ISSUE THREAD

**Issue by chandan276** [Orderella/PopupDialog#332]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 9.1): 10.2
- PopupDialog version (e.g. 0.5.0): 1.1
- Minimum deployment target (e.g. 9.0): 11.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 4): 5

## Dependency management
If you are not using any dependency managers, you can remove this section.

- Dependency manager (e.g. CocoaPods): Cocoapods
- Version (e.g. 1.3.1): 1.7.5

## What did you do?

Tried to add attributed text to title and message.

## What did you expect to happen?

Should be able to add attributed text to title and message.

## What happened instead?

adding attributed text provision is not present. Can we please have that feature too? I am in urgent need for that. Thanks.

**Comment by mwfire** [comment]
This might definitely be useful. I will add this to the roadmap, however I cannot guarantee quick implementation. Another option would be: you can fork this repo and implement it and we will eventually merge it back :)
