### ISSUE TITLE
Re-present dialog after it is dismissed

### ISSUE THREAD

**Issue by simonhopkin** [Orderella/PopupDialog#351]
# Report

## Environment

- Xcode version: 11.4.1
- PopupDialog version: 1.1.0
- Minimum deployment target: iOS 10
- Language (Objective-C / Swift): Swift
- In case of Swift - Version: 5

## Dependency management

- Dependency manager: CocoaPods
- Version: 1.7.5

## What did you do?

I tried to present a popup dialog after it has been previously dismissed.
## What did you expect to happen?

The popup dialog should re-appear.

## What happened instead?

The background blurred but no popup dialog appeared.

However if you use the .fadeIn transition style the popup dialog does appear.  The issue is only caused with bounce and zoom transition styles.

## Project that demonstrates the issue

The code below reproduces the issue:

```
    let popupDialog = PopupDialog(title: "Dialog Title", message: "Dialog Message", transitionStyle: .bounceUp)

    viewController.present(popupDialog, animated: true, completion: {
        popupDialog.dismiss {
            viewController.present(popupDialog, animated: true, completion: nil)
        }
    })
```

You can see the popup initially appears, and is then dismissed.  An attempt is made to present the dialog again but all that appears is the background blur.

If you replace the transitionStyle with .fadeIn you can see the popup appear, disappear and re-appear as expected.

I have submitted the following pull request to fix this issue: https://github.com/Orderella/PopupDialog/pull/350

**Comment by simonhopkin** [comment]
bump

**Comment by ahmedsafadii** [comment]
@simonhopkin you need to know that you are trying to preset the popup inside the popup which already has been dismissing.

the solution for this is just to create delegate or nonfiction center, I prefer to delegate to trigger when the popup dialog dismiss.

**Comment by ahmedsafadii** [comment]
Simple Example would be like this
```
// PopupDialog Controller

// Outer Class
protocol ShowAnotherPopUpDelegate: class {
   func didDismiss()
}

// Insider Class
weak var dismissDelegate: ShowAnotherPopUpDelegate?

// Now inside the button that dismisses the popup call
dismissDelegate.didDismiss()


// Home Control that preset the pop-up

let popupDialog = PopupDialog(title: "Dialog Title", message: "Dialog Message", transitionStyle: .bounceUp)
popupDialog.dismissDelegate = self

viewController.present(popupDialog, animated: true, completion: nil)

Now just inheritance ShowAnotherPopUpDelegate
extension ViewController: ShowAnotherPopUpDelegate {

func didDismiss() {
// show the pop here or do something
}
} 
```
Another solution I don't know if it will works

```
        let popupDialog = PopupDialog(title: "Dialog Title", message: "Dialog Message", transitionStyle: .bounceUp)
        
        viewController.present(popupDialog, animated: true, completion: {
            popupDialog.dismiss {
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                    viewController.present(popupDialog, animated: true, completion: nil)
                }
            }
        })
```
