### ISSUE TITLE
Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by DK-Web** [Orderella/PopupDialog#37]
- `PopupDialog (~> 0.5)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `PopupDialog (~> 0.5)`.

What does it mean?

**Comment by mwfire** [comment]
I am not entirely sure there, but one thing could be an iOS version that is not supported specified in your Podfile, like this:

```
platform :ios, '8.0'
```

The current version is only iOS 9+ compatible. I am guessing a bit at the moment. Does that help?

**Comment by DK-Web** [comment]
In my podfile i have "platform :ios, '10.0'" hmm not work :(

**Comment by mwfire** [comment]
Ok, so I'll see if I can reproduce it. Have you had a look at this StackOverflow thread? http://stackoverflow.com/questions/38030317/pod-repo-update-does-not-happen-error-in-cocoapods
