### ISSUE TITLE
PresentationManager

### ISSUE THREAD

**Issue by cesarmtz93** [Orderella/PopupDialog#40]
Parameter of presentationControllerForPresentedViewController(_:presentingViewController:sourceViewController:)' has different optionality than required by protocol 'UIViewControllerTransitioningDelegate'

Initializer does not override a designated initializer from its superclass

Cannot force unwrap value of non-optional type 'UIView'

I´m getting this errors in my project notice that i'm still using this 
pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :tag => '0.4.0'

**Comment by mwfire** [comment]
Hey there! So just to get this right: you are using Xcode 7, Swift 2.2 with a minimum deployment target of 8.0?

**Comment by cesarmtz93** [comment]
Hi no, i'm using Xcode 8, Swift 2.3 with deployment target of 9.0

**Comment by mwfire** [comment]
I see. The release 0.4.0 depends on Swift 2.2. Unfortunately, as of the official release of Swift 3, there is no version of PopupDialog that supports Swift 2.3. 0.5.0 supports Swift 3.0 only.
