### ISSUE TITLE
Popup doesn't pop the second time.

### ISSUE THREAD

**Issue by jimijon** [Orderella/PopupDialog#43]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.
# Report
## Environment

Please provide information on your development environment, so we can build with the same scenario.
- Mac OS version (e.g. 10.12): 9.3
- Xcode version (e.g. 8.0): 8
- PopupDialog version (e.g. 0.5.0): .5
- Minimum deployment target (e.g. 9.0): 9
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3
## Dependency management

If you are not using any dependency managers, you can remove this section.

> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.
- Dependency manager (e.g. CocoaPods): cocoapods
- Version (e.g. 1.1.0): 1.1.0
## What did you do?

I have a popup for two rows on a static table. The first time I touch, it works, the second time I touch I get a dark screen with no dialog.

To always appear.

A blank dark overlay

**Comment by mwfire** [comment]
@jimijon Thanks for taking the time and your detailed bug report. I will look into this!

**Comment by mwfire** [comment]
I cannot seem to replicate this. Would it be possible to attach a small project where this specific problem occurs? Thanks!

**Comment by ExplosiveBattery** [comment]
I meet the same problem even if when I use the demo.
I move the code of create custom dialog to a data member of ViewController：
```
    lazy var test :PopupDialog = {
        // Create a custom view controller
        let ratingVC = RatingViewController(nibName: "RatingViewController", bundle: nil)
        
        // Create the dialog
        let popup = PopupDialog(viewController: ratingVC, buttonAlignment: .horizontal, transitionStyle: .bounceDown, gestureDismissal: true)
        
        // Create first button
        let buttonOne = CancelButton(title: "CANCEL", height: 60) {
            self.label.text = "You canceled the rating dialog"
        }
        
        // Create second button
        let buttonTwo = DefaultButton(title: "RATE", height: 60) {
            self.label.text = "You rated \(ratingVC.cosmosStarRating.rating) stars"
        }
        
        // Add buttons to dialog
        popup.addButtons([buttonOne, buttonTwo])
        
        return popup
    }()
```
At the same time， change the display function
```
    func showCustomDialog(animated: Bool = true) {


        // Present dialog
        present(test, animated: animated, completion: nil)
    } 
```
Because of the reference named test, dismiss function won't call deinit function to release memory, but the second time I use the present function to display , I just see a blank dark overlay.

Thanks for your devices in advance.

**Comment by ExplosiveBattery** [comment]
I don't want to create the dialog again and again when I need to use it, so move the creating code. @mwfire 

There is a solution： [Dismiss and Present](https://stackoverflow.com/questions/30353499/dismiss-and-present-same-view-controller)

1. Change the public dismiss function to: 

```
        view.removeFromSuperview()
        removeFromParentViewController()
```

2. display the dialog:

```
        addChildViewController(popup)
        view.addSubview(popup.view)
```

3. Last change the code to achieve the blank dark overlay and the animation of the dialog.

**Comment by ExplosiveBattery** [comment]
I find there has a memory leak problem in demo.
when dismiss the image dialog, deinit function will not be called.

**Comment by ExplosiveBattery** [comment]
Closure causes a memory leak
`popup.shake()`

**Comment by dariatsenter** [comment]
Any updates on the issue? I have the same problem..

**Comment by dariatsenter** [comment]
Solved it!

If you put call to present(...) in another function (wrap it), instead of calling it from within IBAction, then it works second, third and many more times without a problem!

**Comment by kornha** [comment]
Same issue. dariatsenter solution does not work for me. I call mine from a function called in tableview didSelectRowAt

**Comment by Kirow** [comment]
issue still exist
