### ISSUE TITLE
Popup with transparent background

### ISSUE THREAD

**Issue by gallynero** [Orderella/PopupDialog#44]
I try make a popup with transparent background but always have white color in the background.

Someone has make this?

Thank you and regards.

**Comment by mwfire** [comment]
Hey @gallynero! You can either set the background color for the popup globally via appearance:

`let pv = PopupDialogDefaultView.appearance()`
`pv.backgroundColor      = UIColor(red: 1, green: 0, blue: 0, alpha: 0.4)`

or on the view directly:

`popup.view.backgroundColor = UIColor(red: 1, green: 0, blue: 0, alpha: 0.4)`

Hope that helps :)
