### ISSUE TITLE
Dark mode not working with Swift 3 Example Project

### ISSUE THREAD

**Issue by X901** [Orderella/PopupDialog#47]
Hi , 
I tried The Demo version and also in my app
nothing happened when Uncomment lines in AppDelegate !

Is there something else I should do to enable Dark Mode ?

**Comment by X901** [comment]
I Found out the reason 
function didFinishLaunchingWithOptions
should not be Private

**Comment by mwfire** [comment]
Will be fixed in 0.5.1. Thanks for investigating, @X901!
