### ISSUE TITLE
?Custom Height?

### ISSUE THREAD

**Issue by dm-katsubo** [Orderella/PopupDialog#49]
It's possible to set custom height for dialog window? thanks

**Comment by mwfire** [comment]
@dm-katsubo For the default dialog view, it's currently not possible to set a custom height. If you are defining a custom view controller, you can set the height dynamically. The default view scales to content and text automatically.

**Comment by morganzysman** [comment]
Hello,
I'm trying to use a larger height that the default custom view controller example.
But when set to larger, the popup doesn't get displayed.

Regards,

Morgan

**Comment by mwfire** [comment]
The height of the standard PopupDialog is defined by its content size, that is image (if any), title and body. If you want to set a custom height other than the one calculated for you out of the box, you have to use your own custom view controller. Having said that, make sure to set constraints correctly. Check the example in this repo or #87 for further reference.
