### ISSUE TITLE
contentMode for ImageView?

### ISSUE THREAD

**Issue by bgdavidx** [Orderella/PopupDialog#51]
# Report
## Environment
- Mac OS version (e.g. 10.12): 10.12
- Xcode version (e.g. 8.0): 8.0
- PopupDialog version (e.g. 0.5.0): 0.5.0
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Swift 3
- In case of Swift - Version (e.g. 3.0): 3.0
## Dependency management
- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.1.0
## What did you do?

ImageView in PopupDialog gets cropped and stretched:

![14055789_10206167811988826_1992036122_n](https://cloud.githubusercontent.com/assets/4666573/19664457/a838d72c-99fd-11e6-987b-886259eaaf6e.jpg) 

I did some debugging and it looks like this has to do with the contentMode of the UIImageView.
## What did you expect to happen?

The entire image should have been shown
## What happened instead?

The image was cropped, and stretched
## Code that demonstrates the issue

``` swift
let popup = PopupDialog(title: "Awesome!", message: "A message here", image: UIImage(named: "test"))
```

Test graphic: test@2x.png:
![confirmemailsenticon 2x](https://cloud.githubusercontent.com/assets/4666573/19666064/6e674436-9a05-11e6-859a-7f3fefca7ed6.png)

**Comment by dvluong** [comment]
Running into the same problem. My image heights are pretty big and it does not automatically adjust the image. I checked the source code in PopupDialog and see that the image view has content mode set to 'aspect fill', which should adjust the image, but it isn't.

**Comment by dvluong** [comment]
If you're still having trouble with the image height being too big, I followed this article on how to resize an image before it is thrown into an image view, I hope this helps everyone else who is running into this problem: http://nshipster.com/image-resizing/
