### ISSUE TITLE
Custom button height

### ISSUE THREAD

**Issue by rock-starr** [Orderella/PopupDialog#54]
Is there anyway to customize the button's height, currently the only way around it would be to use custom views that include the buttons, but that is hacky, and defeats the purpose and the flexibility of adding the buttons in the popup dialogue

**Comment by mwfire** [comment]
@rockstar Hey there, just pushed this feature to the development branch. You can give it a try, specifying the pod as follows in your Podfile:
 `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

Usage:

`let buttonThree = DefaultButton(title: "BUY CAR", height: 60) { ... }`

Please let me know if that makes sense :)
