### ISSUE TITLE
UITapGesture for dismissal interrupts UITableView cell selection

### ISSUE THREAD

**Issue by bevbomb** [Orderella/PopupDialog#56]
> Please fill out this template when filing an issue.
> All ℹ symbols should be replaced with information on the issue.
> Please remove this line and all above before submitting.

# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Xcode version (e.g. 8.0): 8.1
- PopupDialog version (e.g. 0.5.0): 0.5.0
- Minimum deployment target (e.g. 9.0): 9
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.1.0

## What did you do?

Created a custom view controller with a table view inside and used at the view controller for the dialog, I had gestures enabled.

## What did you expect to happen?

I was going to use the table as a picker, when you select a row and handles the selection.

## What happened instead?

The Tap gesture for dismissal prevents the touches on the cells which prevents the default didSelectRow methods from working

**Comment by mwfire** [comment]
Hey @bevbomb. Unfortunately, gesture dismissal and tableviews don't work very well together as of 0.5. At the moment, the solution is to turn off gesture dismissal in the intializer.

```
// Create the dialog
let popup = PopupDialog(title: ..., message: ..., image: ...)

// Present dialog
self.presentViewController(popup, animated: true, gestureDismissal: false) {
    ...
}
```

This also disables tap on backgrounds dismissal, which I'd love to separate in future versions.

**Comment by bevbomb** [comment]
Hey, a simple solution would be to use the gesture delegates and allow simultaneous gestures for the tap only, which will allow all taps to work, also applying the gesture to the background view only will help

**Comment by bevbomb** [comment]
I'd be able to make some adjustments and submit a pull request if you'd like?

**Comment by mwfire** [comment]
I will close this for now, will be reopened on demand.

**Comment by aviralveddis** [comment]
Hi, I too need a fix for this. I want both the operations to be able to remove the popup on tap and select from tableView

**Comment by almaskz** [comment]
Yes, that functionality would be really useful to have. Any work arounds for the mean time?

**Comment by almaskz** [comment]
Just figured that adding a button to cell's content view works. Button touchUpInside does not conflict with gesture dismissal.
