### ISSUE TITLE
How could you pass value to popUp?

### ISSUE THREAD

**Issue by MaeseppTarvo** [Orderella/PopupDialog#57]
Hey! I would like to know, how you are able to pass value to popUp vc if you are using customVC. Because if you do like this it doesn't work:

```
// Create a custom view controller
                    let ratingVC = RatingViewController(nibName: "RatingView", bundle: nil)
                    
                    // Create the dialog
                    let popup = PopupDialog(viewController: ratingVC, buttonAlignment: .horizontal, transitionStyle: .bounceDown, gestureDismissal: true)

ratingVC.selectedProduct = self.products[indexPath.row]
                    
                    
                    
                    // Present dialog
                    self.present(popup, animated: true, completion: nil)
```

**Comment by moonvader** [comment]
@MaeseppTarvo did you find the answer?

**Comment by mwfire** [comment]
Hey there! Have a look at the example at #87. In this example, a reference to PopupDialog is passed to the custom view controller. Make sure to use a weak reference in order to avoid retain cycles.

**Comment by moonvader** [comment]
@mwfire I want to send data to popup not to get if from popup.
Or I missing something?

**Comment by mwfire** [comment]
Hey @moonvader. I am not sure if I understand correctly. Could you please file a new issue with a more detailed description? Thanks!

**Comment by moonvader** [comment]
@mwfire thank you - I already found what I needed

**Comment by MaeseppTarvo** [comment]
@mwfire I've learned alot since I posted this stupid "issue". I suggest you to learn delegates to do the think you want. This question("issue") is not related to this library at all.
