### ISSUE TITLE
Swift 3.0 as Master?

### ISSUE THREAD

**Issue by SaifAlDilaimi** [Orderella/PopupDialog#58]
## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.12.1
- Xcode version (e.g. 8.0): 8.0
- PopupDialog version (e.g. 0.5.0): actuall
- Minimum deployment target (e.g. 9.0): 10.0
- Language (Objective-C / Swift): swift
- In case of Swift - Version (e.g. 3.0): 3.0

Any eta on switching Swift3.0 branch to Master? Xcode still gives warnings to convert to 3.0 when opening the example project..

**Comment by mwfire** [comment]
Hey @deada92. the master branch is Swift 3 compatible. I have several test implementations, as well as error free Travis tests. The current Swift3 branch will be removed soon, just kept it for the people still using it.
- Can you please specify what exactly Xcode wants to convert?
- Are you using CocoaPods? If so, are you on version 1.1.0 or later?

**Comment by SaifAlDilaimi** [comment]
I'm sorry, I was to quick with posting a issue. I was using a older cocoapod version.. Thx for the quick answer and this repository!

**Comment by mwfire** [comment]
No problem, you are always welcome. Thanks!
