### ISSUE TITLE
Disable defaultButton dismiss

### ISSUE THREAD

**Issue by MaeseppTarvo** [Orderella/PopupDialog#59]
Hey. I need that it doesn't dismiss the popUp if textField is empty. So I tried to disable `buttonOne.dismissOnTap = false` but it does nothing. How should I disable it and manually popUp.dismiss() ?

**Comment by mwfire** [comment]
Hey there! At the moment, `dismissOnTap` only works on initialization. You would have to dismiss the dialog manually in the completion block of your button if you disable this feature.

**Comment by MaeseppTarvo** [comment]
Yes that is what I want to do but for some reason I can't disable it to do it manually.
