### ISSUE TITLE
Custom image button

### ISSUE THREAD

**Issue by yuchenglin** [Orderella/PopupDialog#64]
Is there anyway to customize the button using images (icons)?
I could only use custom views to add custom buttons recently, but it seems not so flexible.

**Comment by mwfire** [comment]
Hey @yuchenglin. Could you give me an example of an initializer and/or methods to accomplish this? This seems like a special case, can this be kept generic?

**Comment by yuchenglin** [comment]
Thanks for your reply!
In UIButton, can use `. setImage()` method to set a button's image and ignore its title. The custom view could only control the ***content*** of popup windows. So this feature might enhance the UI flexibility of ***button*** part. I'm not sure whether it's a special case. 
```
var buttonAppearance = DefaultButton.appearance()

// Default button
//buttonAppearance.titleFont      = UIFont.systemFont(ofSize: 14)
//buttonAppearance.titleColor     = UIColor(red: 0.25, green: 0.53, blue: 0.91, alpha: 1)
buttonAppearance.buttonImage = UIImage(named: "camera-icon")
```

FYI Thanks!

**Comment by mwfire** [comment]
Hey @yuchenglin,

ah, I see. With the dialog buttons being a subclass of UIButton `setBackgroundImage(_ image: UIImage?, for state: UIControlState)` and `setImage(_ image: UIImage?, for state: UIControlState)` are accessible. Thus,  the following example will work:

```
// Customize default button appearance
let db = DefaultButton.appearance()
let image = UIImage(named:"pexels-photo-103290")
db.setImage(image, for: .normal)

// Alternatively, to keep the title
db.setBackgroundImage(image, for: .normal)
```

Hope that helps :)
Martin

**Comment by yuchenglin** [comment]
I see. Thanks a lot!!
