### ISSUE TITLE
UIStackView has ambiguous layout

### ISSUE THREAD

**Issue by HighmoreJx** [Orderella/PopupDialog#65]
Customer View Controller

Here is my controller layout code:

`
let width = (UIScreen.main.bounds.width - 100) / 2

        let height = width * 3 / 4

       self.view.snp.makeConstraints { (make) in
            make.width.equalTo(width)
            make.height.equalTo(height)
        }

        let view = UIView()

        self.view.addSubview(view)
        view.snp.makeConstraints { (make) in
            make.center.equalTo(self.view)
            make.height.width.equalTo(50)
        }

`

then i got .... UIStackView has ambiguous layout

**Comment by mwfire** [comment]
It's not recommended to add width and height constraints with fixed values to your custom view, as PopupDialog should handle this for you. Does it work as expected if you align the view to just the superview or omit these completely?
