### ISSUE TITLE
layout issue on iPhone 4 screen

### ISSUE THREAD

**Issue by chrischenyc** [Orderella/PopupDialog#69]
reproduce step:
1. download example project
2. change target Devices from "universal" to "iPhone"
3. run example app
4. open popup dialogue, you can see it takes too much space
![simulator screen shot 30 nov 2016 4 47 54 pm](https://cloud.githubusercontent.com/assets/334233/20742120/8e874e8e-b722-11e6-93f3-20cb55201aaa.png)

question: PopupDialog works well if the app is Universal, but I can't simply convert my iPhone-only app to Universal. Apple rejected my app because they found this issue on iPad devices.

**Comment by chrischenyc** [comment]
i reckon it's Line 160 in PopupDialog.swift causing the issue
`
        view = PopupDialogContainerView(frame: UIScreen.main.bounds)
`

**Comment by mwfire** [comment]
Thanks for reporting this. I will look into this asap!

**Comment by chrischenyc** [comment]
@mwfire any luck reproducing the issue? cheers!

**Comment by chrischenyc** [comment]
by looking into the code, I reckon it's the auto-layout constraints that cause the issue.

I did followings:
1. download the project
2. run the example on iPhone 4S

I got this screenshot

![simulator screen shot 12 dec 2016 6 13 03 pm](https://cloud.githubusercontent.com/assets/334233/21090887/d9abc6ba-c096-11e6-87d5-4a5babae5228.png)

**Comment by mwfire** [comment]
Hi @chenyuan!

I had a look at the code, ran examples on several devices and could not find any auto layout related issues. Although not a nice example for the iPhone 4S screen, having an image, title, text and three buttons just exceeds the screen height. I am not applying any extra scrolling logic to keep it simple.

The solution would be to either reduce your image heights for the smaller iPhones or use custom view controllers.
