### ISSUE TITLE
Swift 3.0 Compatibility

### ISSUE THREAD

**Issue by mwfire** [Orderella/PopupDialog#7]
The title speaks for itself: update syntax to Swift 3

**Comment by mwfire** [comment]
First implementation of Swift 3 syntax is done, commit 5238eec to branch Swift3

**Comment by mwfire** [comment]
Please note that at the moment the Swift 3 branch is not up to date in terms of features. As the production version is still subject to change, I will port this library to Swift 3 within the next weeks/months.

**Comment by animaonline** [comment]
Hi, any updates? Swift 3 support would totally be great now as Xcode 8 is released :)

**Comment by mwfire** [comment]
@animaonline Hey there! The Swift 3 branch contains all latest features now. There might be warnings until the final release, but for now you can just use the Swift3 branch in your podfile.

**Comment by animaonline** [comment]
that's great man! Thanks (Y)

**Comment by DK-Web** [comment]
Don´t work. Get an error "...not compatible with Swift..."

**Comment by mwfire** [comment]
@DK-Webentwicklung Just to be sure, you are using the Swift3 branch, right? Specified in your Podfile like:
`pod 'PopupDialog', :git => '/github.com/Orderella/PopupDialog/PopupDialog.git', :branch => 'Swift3'`

I will merge this branch with master in the following days.

**Comment by DK-Web** [comment]
Yes but not work

**Comment by Reedyuk** [comment]
im also getting the same problem. Looks like the stack view library you are using isn't using swift 3.0
![screen shot 2016-09-15 at 09 11 55](https://cloud.githubusercontent.com/assets/3853006/18542782/87f7b7b4-7b24-11e6-85b9-4cdb89479342.png)

**Comment by mwfire** [comment]
@Reedyuk Hey there! yep, that's indeed the issue. I have just forked another fork that supports Swift3 to https://github.com/mwfire/TZStackView/tree/swift-3

I'll see how to implement that best asap.

**Comment by Reedyuk** [comment]
Just a thought, any chance you can create an iOS 9 branch and only use the default stack view. Most if not all projects using Swift 3.0 will probably be on 9 and above.

**Comment by mwfire** [comment]
Yeah, originally, this library was iOS9+, using only native stack views. iOS 8 support was added by popular demand as of #13. Dropping that now would almost be a step back, but I agree that a iOS9 branch without TZStackViews makes sense.

**Comment by Reedyuk** [comment]
Here is a working version using the Apple Stackviews.
https://github.com/Reedyuk/PopupDialog/tree/Swift3

If you want to use this in your project for now:
`pod 'PopupDialog', :git => 'https://github.com/Reedyuk/PopupDialog.git', :branch => 'Swift3'`

**Comment by Reedyuk** [comment]
How about using a compiler flag, to switch, would that work?

**Comment by mwfire** [comment]
That was my initial approach. It did not work out, though, really :(

The Swift 3 branch made it to the development branch. As soon as I have tested Objective-C and Carthage compatibility, I will merge it to master.

**Comment by mwfire** [comment]
Now merged to master branch, release 0.5.
