### ISSUE TITLE
Clang importer creation failed

### ISSUE THREAD

**Issue by ollyde** [Orderella/PopupDialog#72]
Environment
MacOSX version 10.12.1 (16B2555)
xCode version Version 8.1 (8B62)
PopupDialog version 5.0
Minimum deployment target 9.0
Language Swift 3.0

Using CocoPods:

```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Where\'s Hot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Where's Hot
  pod 'PopupDialog', '~> 0.5'

end
```

**Report**

```
<unknown>:0: error: invalid virtual filesystem overlay file '/Users/me/Library/Developer/Xcode/DerivedData/Where's_Hot-bxklmcdlmeyvnadlffefxdgnqpti/Build/Intermediates/Pods.build/Debug-iphonesimulator/PopupDialog.build/unextended-module-overlay.yaml'
<unknown>:0: error: clang importer creation failed
```

This happens only to this library when trying to add it to my project.

**Comment by caraballoj** [comment]
Any idea why you were receiving this error?

**Comment by mwfire** [comment]
This is most likely due to the fact that the target name `Where's_Hot` contains non-alphanumeric characters, specifically `'`.  Xcode seems to have problems with this. As seen at https://github.com/CocoaPods/CocoaPods/issues/3555
