### ISSUE TITLE
Dropped iOS 8 compatibility is unadvised.

### ISSUE THREAD

**Issue by zzyspace** [Orderella/PopupDialog#74]
Hope compatibility iOS 8 again

**Comment by mwfire** [comment]
Actually Apple advises to do that ;) iOS8 is down to 8%, rest of iPhone users are either on iOS9 or iOS10. However, I do understand that some apps still need to support iO8, so I merged @trungp pull request to development.

Please help with testing. You can add the development version of the dialog to your app via your Podifle:
`pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`

Thanks in advance!
