### ISSUE TITLE
Image is oversized

### ISSUE THREAD

**Issue by OozoraHaruto** [Orderella/PopupDialog#78]
# Report

## Environment
Please provide information on your development environment, so we can build with the same scenario.

- Mac OS version (e.g. 10.12): 10.12.3 Beta (16D17a)
- Xcode version (e.g. 8.0): 8.2 beta (8C30a)
- PopupDialog version (e.g. 0.5.0): 0.5.1
- Minimum deployment target (e.g. 9.0): 9.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): 3.0

## Dependency management
If you are not using any dependency managers, you can remove this section.
> Please note: If you are using CocoaPods with Xcode 8, CocoaPods 1.1.0 is required.

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.1.1

## What did you do?

Use the default popupDialog init function wanting to show a pic that the user had selected from his library in the popup view

## What did you expect to happen?

I expected the image to resized properly and fit in the popupdialog view (Image Below)
![simulator screen shot 27 dec 2016 7 06 19 pm](https://cloud.githubusercontent.com/assets/3457550/21498462/9b7dc208-cc67-11e6-838a-87768c4470d5.png)

## What happened instead?

Image was way oversized and was even over the screen size and wasn't able to see the full image and the text message (Image Below)
![simulator screen shot 27 dec 2016 7 06 30 pm](https://cloud.githubusercontent.com/assets/3457550/21498464/9bc91848-cc67-11e6-87d1-580aa1b40a53.png)

Is there away i can do it automatically to resize the image or do i have to do it everytime i call this function?

Best regards,
Malcolm

**Comment by mwfire** [comment]
Hey @taiyoOzora,

thanks for reporting this. Images should be scaled to fit the dialog automatically (however, they are not resized as in calculating a new, smaller image). The image should align to the width of the dialog automatically, while maintaining the correct aspect ratio. Having said that, it is possible that the PopupDialog exceeds the screen if the image height is too big.

It seems this image is not scaled correctly, though. Would it be possible to send me this image so I can investigate further?

Cheers
Martin

**Comment by OozoraHaruto** [comment]
Hi @mwfire thanks for the quick reply.
The image in the screenshot #1 is a pic i made but the image that I used in scrrenshot #2 is a pic from ios simulator 
Seems like any hi-res image work. Here's an [image](https://drive.google.com/open?id=0BxfO3GBC-1gfX3Q1VGtuY0MwR0U). Hope it helps you guys.

Best Regards,
Malcolm

**Comment by mwfire** [comment]
Hi @taiyoOzora,

I have tested with the image you provided and it indeed looks sh**ty ;) I have added some calculations and pushed the fixes to the development branch. I'd love to get your feedback on this. You can get the dev version via `pod 'PopupDialog', :git => 'https://github.com/Orderella/PopupDialog.git', :branch => 'development'`.

Please let me know if that works for you!

Cheers
Martin

**Comment by OozoraHaruto** [comment]
Hi @mwfire ,
It works great for landscape photos and some potrait photos however if you take any photos that are longer (eg. Just a screenshot from the simulator) the photo will still overshot but looks good. It's gonna be difficult to calculate too. I'm good with the current setup as iPhone generally don't take photos in that aspect ratio. Thanks for the quick follow up.

- The bug I was talking about
![simulator screen shot 29 dec 2016 12 24 33 pm](https://cloud.githubusercontent.com/assets/3457550/21536778/23dded0c-cdc2-11e6-9d6d-196bc6fbb655.png)

- Looks great :D Thanks
![simulator screen shot 29 dec 2016 12 28 59 pm](https://cloud.githubusercontent.com/assets/3457550/21536790/63905228-cdc2-11e6-8f80-b900f43e78bb.png)

Best Regards,
Malcolm

**Comment by mwfire** [comment]
Hi @taiyoOzora,

thanks for testing, very much appreciated! Portrait images are not well suited for a popup dialog at all, that's true. Overshooting can only be compensated by adding scroll bars, which is a weird user experience in the context of this dialog. The basic default view does not handle these cases and works best with landscape images. That is why I added the custom view controller setting to allow for better design in special cases.

Thanks again, I will push the fix asap to master!

Cheers
Martin

**Comment by OozoraHaruto** [comment]
Hi @mwfire,
Thanks for the quick replies. I understand what you mean.
Thanks for the cool framework too.

Best Regards,
Malcolm

**Comment by mwfire** [comment]
Hey @taiyoOzora, sure thing! Thanks for helping improve PopupDialog 👍
