### ISSUE TITLE
Custom animation duration

### ISSUE THREAD

**Issue by mwfire** [Orderella/PopupDialog#85]
Up to now, the animation duration for the PopupDialog is set to fixed values of `0.6` and `0.22`. To maintain Objc-C compatibility the animation enums do not have associated values. As I am planning on dropping Objc-C compatibility with version 1.0, this feature can be implemented.

Example:

```
let dialog = PopupDialog(transitionStyle: .bounceUp(durationIn: 0.6, durationOut: 0.22))
```

**Comment by pontusm** [comment]
Sounds like a great idea! Any eta for this? :)

**Comment by Ljuka** [comment]
Any update on this? Will we have this feature sometime in future? 😃
