### ISSUE TITLE
Is it possible to modify presentation origin point and width?

### ISSUE THREAD

**Issue by nick-iCars** [Orderella/PopupDialog#86]
I'm trying to use PopupDialog so that when users tap a tableview a popupdialog instance is presented as if from the table view cell, but I want it to be presented directly over the tapped cell. Is there any way to achieve this currently? I'd also like to make the dialog a bit wider. The effect I'm going for is to make it look like the table view cell kind of pops out and covers the rest of the content in the tableview. I know this isn't really what popupdialog was designed for but I'm having trouble finding the right solution and I'm now grabbing at straws. I've tried using collectionview but was unable to achieve the proper animation. Thanks for any help.

**Comment by mwfire** [comment]
Hey @nick-iCars,

I do understand what you are up to, however PopupDialog is not designed to support this :(
You seem to be looking for custom view transitions, this [article](http://blog.matthewcheok.com/design-teardown-preview-expanding-cells/) might be interesting :)

Cheers
Martin
