### ISSUE TITLE
dismiss callback not working with custom VC 

### ISSUE THREAD

**Issue by jf-gallo** [Orderella/PopupDialog#92]
# Report

## Environment
- Mac OS version (e.g. 10.12):  10.12.2
- Xcode version (e.g. 8.0): 8.1
- PopupDialog version (e.g. 0.5.0):  Latest 
- Minimum deployment target (e.g. 9.0): 9
- Language (Objective-C / Swift): swift
- In case of Swift - Version (e.g. 3.0): 3 

## Dependency management

- Dependency manager (e.g. CocoaPods):  Cocoapods
- Version (e.g. 1.1.0):  1.1 .1

## What did you do?

create a custom view controller Popup view with dismiss callback

        let popup = storyboard?.instantiateViewController(withIdentifier: "alerts") as! AlertsViewController

        let alert = PopupDialog(viewController: popup, gestureDismissal: true) {
            print("dismiss callback")
         }

        self.present(alert, animated: true) {
        }

## What did you expect to happen?

callback to be triggered on dismiss

## What happened instead?

callback was not triggered on dismiss. 

Also wanted to add, that I have done this exact procedure with a Normal Popup Dialogue,  (e.g not custom) and the callback WAS triggered.

**Comment by mwfire** [comment]
@huffmann the default dialog is also using a custom view controller internally. When you are using your own custom view controller and the completion handler is not triggered, this usually hints to a retain cycle related to your custom view controller. Instruments and/or memory graph debugger will help you to identify the problem.

**Comment by mwfire** [comment]
You can also have a look at the example at #87, which covers some best practices when using custom view controllers.

**Comment by jf-gallo** [comment]
Awesome that was it! 

Just for anyone's reference,  to stop retain cycle simply add **weak** to your mainViewController reference in customViewController. 
(e.g)
weak var homeVC : HomeViewController?

Thanks a lot. Its all working now.
