### ISSUE TITLE
[Feature Request] support navigation inside popups

### ISSUE THREAD

**Issue by arielpollack** [Orderella/PopupDialog#94]
# Report
Would be great to have a `UINavigationController` like navigation inside popups.
Best result will be like the native share extension popup's navigation.

![nav-popup](https://cloud.githubusercontent.com/assets/1862153/21964087/42d141e8-db4e-11e6-8d82-bf3b7cb2759b.gif)

## Environment

- Mac OS version: 10.12.2
- Xcode version: 8.2
- PopupDialog version: 0.5.0
- Minimum deployment target: 9.0
- Language: Swift
- In case of Swift - Version: 3.0

## Dependency management

- Dependency manager: CocoaPods
- Version: 1.1.1

**Comment by mwfire** [comment]
Hey @arielpollack. As PopupDialog supports custom view controllers, you can also use navigation controllers. Here is a basic example I quickly made up: https://www.dropbox.com/s/zvcacqvi4jl8qk4/PopupDialogNavigationExample.zip?dl=1

Example:

```
let nav = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "NavigationController")
nav.view.translatesAutoresizingMaskIntoConstraints = false
nav.view.heightAnchor.constraint(equalToConstant: 400).isActive = true

let popup = PopupDialog(viewController: nav, gestureDismissal: false)
let ok = DefaultButton(title: "OK", action: nil)
popup.addButton(ok)

present(popup, animated: true, completion: nil)
```

**Comment by arielpollack** [comment]
Awesome! I've actually tried it but haven't put any height constraint so probably that's why it didn't work.
Thanks!

**Comment by mwfire** [comment]
Sure thing! 👍
