### ISSUE TITLE
button with text and image

### ISSUE THREAD

**Issue by yuchenglin** [Orderella/PopupDialog#95]
Hi,

I proposed a similar issue at #64 . After I implemented, I found that
First,
```
// Customize default button appearance
let db = DefaultButton.appearance()
let image = UIImage(named:"pexels-photo-103290")
db.setImage(image, for: .normal)
```
The text is also displayed (at the right of the image and might be truncated)

```
// Alternatively, to keep the title
db.setBackgroundImage(image, for: .normal)
```
In this method, the text would be overlayed by image

Also,
I need to write many new PopupDialogButton classes, so I can set each unique button icon. (`DefaultButton.appearance()`)

Below is my mockup of button UI, please let me know if I missed something. Or it might be a great enhancement :)
![screen shot 2017-01-15 at 9 43 27 am](https://cloud.githubusercontent.com/assets/5432898/21964770/6d257df2-db07-11e6-9250-290a95f2e210.png)

**Comment by kjantzer** [comment]
Why was this closed?
