### ISSUE TITLE
How to not dismiss the previous PopupDialog if I have more than one PopupDialog?

### ISSUE THREAD

**Issue by dhafinmuktafin** [Orderella/PopupDialog#96]
I'm creating a signup form that consist of UITextFields. I want to show more than one PopUps. There is another popup to show after users clicking the First-Popup's button

I want my Second-Popup doesn't override the First-Popup after clicking the First-Popup's button. I need that feature because I want to be able to go back (by touching outside of Popup) and still can correcting the data that has been filled in the First-Popup.

But when I'm triggering to show my Second-Popup by clicking the button of First-Popup, the First-Popup disappear along with the input value from TextFields.

Any solution to this?

**Comment by mwfire** [comment]
I am not sure if this is that related to PopupDialog. How would you do that with UIViewControllers? Can you please provide an example project? 

Thanks

**Comment by dhafinmuktafin** [comment]
@mwfire 
![screen shot 2017-01-16 at 2 47 52 am](https://cloud.githubusercontent.com/assets/2961392/21965619/3e1799fc-db96-11e6-95a5-f4d6acb4b693.png)

In my picture above, I have "Forgot Password" Button and "Next" Button.
Code below is triggered when I click "Forgot Password" to show a new PopupDialog.
```
    @IBAction func btnForgotPasswordPressed(_ sender: Any) {
        ShowForgotPassword()
    }
    func ShowForgotPassword(){
        let submitEmail = SubmitEmailViewController(nibName: "SubmitEmailViewController", bundle: nil)
        
        let popup = PopupDialog(viewController: submitEmail, buttonAlignment: .horizontal, transitionStyle: .zoomIn, gestureDismissal: true)
        
        let buttonOne = DefaultButton(title: "Submit"){
        }
        var buttonAppearance = DefaultButton.appearance()
        buttonAppearance.titleFont = UIFont.systemFont(ofSize: 20)
        buttonAppearance.titleColor = UIColor.blue
        popup.addButtons([buttonOne])
        buttonOne.isEnabled = false
        present(popup, animated: true, completion: nil)
    }
```
Then there will be a new PopupDialog on top of the previous PopupDialog (stacked) like in picture below:
![screen shot 2017-01-16 at 2 48 06 am](https://cloud.githubusercontent.com/assets/2961392/21965620/400f08a8-db96-11e6-95b5-cf29bb79b71b.png)

But it will be different if I triggered a new popup by clicking "Next" Button, a new PopupDialog still show up but the previous Popup will disappear (not stacked like in the 2nd picture above). In my case, I need to make it stacked when I click "Next" Button. How to achieve it?

Thanks in advance.

**Comment by mwfire** [comment]
If I do understand you correctly, you don't want to dismiss the first PopupDialog when tapping the `Next` button. You can prevent auto-dismissal on button tap by setting `dismissOnTap = false` on the button. This way, the button action would still be called but the dialog is not dismissed.

```
let buttonOne = DefaultButton(title: "Submit") { }
buttonOne.dismissOnTap = false
```

This feature is indeed badly documented. I will update the ReadMe accordingly soon.

**Comment by dhafinmuktafin** [comment]
@mwfire Thanks for your reply! Yes, you're right, I want to show the second PopupDialog (by clicking "Next") without dismissing the first PopupDialog. I just  tried these lines of code:
```
let buttonOne = DefaultButton(title: "Next") {
     self.ShowSecondPopup()
}
buttonOne.dismissOnTap = false
```
And I got this error when I clicked "Next":
![screen shot 2017-01-16 at 1 00 16 pm](https://cloud.githubusercontent.com/assets/2961392/21972408/e1436e62-dbeb-11e6-89de-ff86253233b3.png)

Please help me to solve this because I really love your PopupDialog and I want to use it in my app.
Thanks..

**Comment by mwfire** [comment]
The problem is that you are already presenting a modal view controller on your base view controller, namely a PopupDialog. Stacking multiple modal view controllers on a single view controller is not supported by iOS. You can, however, present it on the PopupDialog that was presented before. I'd not consider this best practice though.

**Comment by dhafinmuktafin** [comment]
@mwfire ah I see. I'm new to swift programming. I will discover other solution to keep textfield text after returning from the second modal. Thanks for your reply :)

**Comment by mwfire** [comment]
Sure thing! :)

**Comment by ikyh** [comment]
Hi @mwfire What if I want to dismiss previous pop up and show a new one, when i click on tableViewCell of the previous which is a tableViewController. I have referred this example `https://github.com/mwfire/PopupDialogCustomExample`. Please help
