### ISSUE TITLE
Storyboard support?

### ISSUE THREAD

**Issue by sonifex** [Orderella/PopupDialog#98]
- Mac OS version (e.g. 10.12): 10.12.1
- Xcode version (e.g. 8.0): 8.1
- PopupDialog version (e.g. 0.5.0): 0.5.3
- Minimum deployment target (e.g. 9.0): 8.0
- Language (Objective-C / Swift): Swift
- In case of Swift - Version (e.g. 3.0): Swift 3

- Dependency manager (e.g. CocoaPods): CocoaPods
- Version (e.g. 1.1.0): 1.1.0.rc.3

I am trying to show custom view controller using storyboard. There is nothing show up just the background become blurry.
In your customvc example you use xib and i could not find information about storyboard. 

Does PopupDialog support Storyboard?

**Comment by mwfire** [comment]
Hey @sonifex, sure, you can also instantiate your view controller from storyboard. You have to make sure, though, that constraints are laid out correctly.

**Comment by sonifex** [comment]
Thank @mwfire for your answer and i figured out my problem. As you said the problem was that constraints did not lay out correctly.

**Comment by moonvader** [comment]
@mwfire, @sonifex
can you please tell more about constraints for this case?
